import {useEffect,useState} from 'react';
import type {Api} from '../api';
import {Icon} from '../icons';
import {languageLabel,modeLabels,type ReadingCopy,type SubmissionSummary,type Job,type Paginated} from '../types';
import {Thumbnail} from '../reader/Images';
import {taskText} from '../reader/presentation';
import {historyPollDelay,pollVisibleHistory} from './history-polling';

const countLabels:Record<string,string>={awaiting_upload:'等待上传',validating_upload:'校验原图',succeeded:'完成',partial:'部分保留原文',expired:'译图过期',queued:'排队',running:'翻译中',failed:'失败',cancelled:'取消',no_text:'无文字',outcome_unknown:'待核实'};
function groupState(group:SubmissionSummary){const c=group.counts??{[group.status]:group.page_count};if(c.outcome_unknown)return '需要核实';if(c.running||c.queued||c.awaiting_upload||c.validating_upload)return '正在翻译';if(c.failed)return c.failed===group.page_count?'翻译失败':'部分失败';if(c.expired)return '含过期译图';if(c.partial)return '部分文字保留原文';if(c.cancelled)return '已结束 · 含取消';if(c.no_text===group.page_count)return '未检测到文字';return '已完成';}
export function TranslationHistory({api,copies,userId,onOpen,onLogin,onDelete}:{api:Api;copies:ReadingCopy[];userId?:string;onOpen:(copy:ReadingCopy,job?:Job,group?:SubmissionSummary)=>void;onLogin:()=>void;onDelete:(job:Job,onDeleted:()=>void)=>void}){
  const [data,setData]=useState<Paginated<SubmissionSummary>>();const [offset,setOffset]=useState(0);const [error,setError]=useState('');const [refresh,setRefresh]=useState(0);const [expanded,setExpanded]=useState<string>();
  useEffect(()=>{
    if(!api.token)return;
    setData(undefined);setError('');
    return pollVisibleHistory({
      load:()=>api.history(offset),current:()=>api.isCurrent(),
      receive:value=>{setData(value);setError('');},error:error=>setError(error.message),
      delay:value=>historyPollDelay(value.items.flatMap(group=>Object.keys(group.counts??{[group.status]:group.page_count}).filter(state=>(group.counts??{[group.status]:group.page_count})[state]>0))),
    });
  },[api,offset,refresh]);
  const related=(group:SubmissionSummary)=>copies.filter(c=>c.pages.some(p=>p.ownerId===userId&&p.apiOrigin===new URL(api.base).origin&&((group.asset_ids??[]).includes(p.assetId??'')||p.jobs.some(j=>(group.job_ids??[]).includes(j.id)))));
  return <div><div className="nc-page-heading"><div><span className="nc-eyebrow">TRANSLATION JOURNAL</span><h1>翻译记录</h1><p>每次提交，都有清楚的进度与结果。</p></div>{api.token&&<button className="button secondary" onClick={()=>setRefresh(v=>v+1)}><Icon name="refresh"/>刷新记录</button>}</div>
    {!api.token?<div className="nc-empty"><Icon name="clock" size={36}/><h2>登录后找回翻译记录</h2><p>任务保存在账户中，关闭阅读器也会继续处理。</p><button className="button primary" onClick={onLogin}>登录账户</button></div>:<>{error&&<div className="nc-error" role="alert">{error}<button className="text-link" onClick={()=>setRefresh(v=>v+1)}>重试</button></div>}{!data&&!error?<p className="nc-loading">正在读取翻译记录…</p>:data&&!data.items.length?<div className="nc-empty"><Icon name="clock" size={36}/><h2>还没有翻译记录</h2><p>打开一本漫画，从需要翻译的那一页开始。</p></div>:data&&<><div className="nc-history-list">{data.items.map(group=>{const books=related(group);const copy=books[0];const matched=copy?.pages.filter(p=>(group.asset_ids??[]).includes(p.assetId??'')||p.jobs.some(j=>(group.job_ids??[]).includes(j.id)))??[];return <article className="nc-history-card" key={group.id}><div className="nc-history-summary"><Thumbnail blobKey={matched[0]?.blobKey??copy?.pages[0]?.blobKey}/><div className="nc-history-copy"><div className="nc-section-heading"><h2>{books.length>1?`${copy.title} 等 ${books.length} 本漫画`:copy?.title??'未关联本机漫画'}</h2><span className={`nc-state ${group.counts?.failed||group.counts?.outcome_unknown||group.status==='failed'?'attention':''}`}>{groupState(group)}</span></div><p>{group.page_count} 页 · {modeLabels[group.mode]??group.mode} → {languageLabel(group.target_language)}</p><p className="nc-muted">{new Date(group.created_at).toLocaleString()}</p><div className="nc-history-counts">{Object.entries(countLabels).filter(([key])=>(group.counts??{[group.status]:group.page_count})[key]).map(([key,label])=><span key={key}>{label} <b>{(group.counts??{[group.status]:group.page_count})[key]}</b></span>)}</div><div className="nc-history-bottom"><span>本次确认最多 <b>{group.quota_pages}</b> 页额度 · 按实际交付结算</span><div className="nc-inline"><button className="button secondary" aria-expanded={expanded===group.id} onClick={()=>setExpanded(v=>v===group.id?undefined:group.id)}>{expanded===group.id?'收起详情':'查看详情'}</button>{copy&&<button className="button primary" onClick={()=>onOpen(copy,undefined,group)}>继续阅读</button>}</div></div></div></div>{expanded===group.id&&<HistoryDetail api={api} group={group} copies={books} onOpen={onOpen} onDelete={job=>onDelete(job,()=>setRefresh(v=>v+1))}/>}</article>;})}</div><div className="nc-pagination"><span>共 {data.total} 次提交</span><button className="button secondary" disabled={!offset} onClick={()=>{setOffset(v=>Math.max(0,v-12));setExpanded(undefined);}}>上一页</button><button className="button secondary" disabled={data.next_offset==null} onClick={()=>{setOffset(data.next_offset!);setExpanded(undefined);}}>下一页</button></div></>}</>}
  </div>;
}
function HistoryDetail({api,group,copies,onOpen,onDelete}:{api:Api;group:SubmissionSummary;copies:ReadingCopy[];onOpen:(copy:ReadingCopy,job?:Job)=>void;onDelete:(job:Job)=>void}){
  const [data,setData]=useState<Paginated<Job>>();const [offset,setOffset]=useState(0);const [error,setError]=useState('');const [busy,setBusy]=useState('');const [refresh,setRefresh]=useState(0);
  useEffect(()=>{
    setData(undefined);setError('');
    return pollVisibleHistory({
      load:()=>api.historyJobs(group,offset),current:()=>api.isCurrent(),
      receive:value=>{setData(value);setError('');},error:error=>setError(error.message),
      delay:value=>historyPollDelay(value.items.map(job=>job.status)),
    });
  },[api,group.id,offset,refresh]);
  async function download(job:Job){setBusy(job.id);try{const latest=await api.latestResult(job.id);if(!latest.result?.output_asset_id)throw Error('当前模式的最新译图已过期、删除或尚未完成。');const blob=await api.image(latest.result.output_asset_id);if(!api.isCurrent())return;const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`漫画译图-${job.mode}-${job.target_language}.${blob.type==='image/jpeg'?'jpg':blob.type==='image/webp'?'webp':'png'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){if(api.isCurrent())setError((e as Error).message);}finally{setBusy('');}}
  return <div className="nc-history-detail">{error&&<p role="alert" className="inline-error">{error}<button className="text-link" onClick={()=>setRefresh(v=>v+1)}>重试</button></p>}{!data&&!error?<p>正在读取逐页状态…</p>:data?.items.map((job,n)=>{const copy=copies.find(c=>c.pages.some(p=>p.jobs.some(j=>j.id===job.id)||p.assetId===(job.requested_asset_id??job.input_asset_id)));const at=copy?.pages.findIndex(p=>p.jobs.some(j=>j.id===job.id)||p.assetId===(job.requested_asset_id??job.input_asset_id));const reused=job.reused??(job.cache_hit||job.submission_id!==group.id);return <div className="nc-history-page" key={`${job.id}:${n}`}><div><b>{copy&&at!=null?`第 ${at+1} 页`:`提交页 ${offset+n+1}`}</b><p>{taskText(job)} · {reused?'复用 · 本次不扣额度':job.settlement==='included'?'PLUS 常规翻译 · 不限量':job.settlement==='settled'?`已结算 ${job.quota_pages} 页`:job.settlement==='reserved'?`预占 ${job.quota_pages} 页`:'未扣页数额度'}</p>{job.error&&<p className="nc-attention">{job.error.message}</p>}<details className="nc-technical"><summary>技术详情</summary><span>任务 {job.id}<br/>{job.error?.code}</span></details></div><div className="nc-inline">{copy?<button className="button secondary" onClick={()=>onOpen(copy,job)}>打开此页</button>:job.status==='succeeded'&&<button className="button secondary" disabled={!!busy} onClick={()=>void download(job)}>保存最新译图</button>}{['awaiting_upload','validating_upload','queued','running'].includes(job.status)&&<button className="button secondary" disabled={!!busy||job.cancel_requested} onClick={async()=>{setBusy(job.id);try{await api.cancel(job.id);if(api.isCurrent())setRefresh(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy('');}}}>{job.cancel_requested?'正在停止':'停止任务'}</button>}{job.output_asset_id&&<button className="icon-button" aria-label="删除服务器译图" onClick={()=>onDelete(job)}><Icon name="trash" size={18}/></button>}</div></div>;})}{data&&data.total>30&&<div className="nc-pagination"><span>共 {data.total} 页</span><button className="button secondary" disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-30))}>上一页</button><button className="button secondary" disabled={data.next_offset==null} onClick={()=>setOffset(data.next_offset!)}>下一页</button></div>}</div>;
}
