import {Select} from './Select';
import {msg} from '../i18n/runtime';
import type {ImportAssignment,LibraryState} from '../library/types';
export function ImportAssignmentFields({value,onChange,library,workOnly=false}:{value:ImportAssignment;onChange:(v:ImportAssignment)=>void;library:LibraryState;workOnly?:boolean}){
 const targets=value.kind==='publication'?library.publications.filter(p=>p.workIds.includes(value.workId??'')):library.chapters.filter(c=>c.workId===value.workId);
 return <div className="nc-form-grid"><label className="field">{msg("归入作品")}<Select aria-label={msg("归入作品")} value={value.workId??''} onChange={e=>onChange({...value,workId:e.target.value||undefined,targetId:undefined,seriesId:undefined})}><option value="">{msg("新建作品")}</option>{library.works.map(w=><option key={w.id} value={w.id}>{w.title}</option>)}</Select></label>{!value.workId&&<label className="field">{msg("作品名称")}<input aria-label={msg("作品名称")} value={value.title} onChange={e=>onChange({...value,title:e.target.value})} maxLength={180}/></label>}
 {!workOnly&&<><label className="field">{msg("内容归属")}<Select aria-label={msg("内容归属")} value={value.kind} onChange={e=>onChange({...value,kind:e.target.value as ImportAssignment['kind'],targetId:undefined})}><option value="unclassified">{msg("待整理材料（信息不足）")}</option><option value="chapter">{msg("话／章节")}</option><option value="extra">{msg("番外章节")}</option><option value="publication">{msg("卷册／单行本")}</option><option value="work">{msg("独立作品完整副本")}</option></Select></label>
 {['chapter','extra','publication'].includes(value.kind)&&<><label className="field">{msg("关联已有条目")}<Select aria-label={msg("关联已有条目")} value={value.targetId??''} onChange={e=>onChange({...value,targetId:e.target.value||undefined})}><option value="">{msg("新建条目")}</option>{targets.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</Select></label>{!value.targetId&&<label className="field">{msg("编号（可留空）")}<input value={value.number??''} onChange={e=>onChange({...value,number:e.target.value||undefined})} placeholder={msg("如 12.5、上册")}/></label>}</>}
 {value.kind==='publication'&&!value.targetId&&library.series.some(s=>s.workIds.includes(value.workId??''))&&<label className="field">{msg("已有出版套系")}<Select aria-label={msg("出版套系")} value={value.seriesId??''} onChange={e=>onChange({...value,seriesId:e.target.value||undefined})}><option value="">{msg("不指定套系")}</option>{library.series.filter(s=>s.workIds.includes(value.workId??'')).map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</Select></label>}
 </>} </div>;
}
