import {useMemo,useState} from 'react';
import {Icon} from '../icons';
import {Modal} from './components';
import type {Chapter,Settings} from '../types';
import {languageLabel,modeLabels} from '../types';
import {readPosition} from '../reader/store';
import {Thumbnail} from '../reader/Images';
import {pageTranslation} from '../reader/presentation';

export function Library({chapters,settings,setSettings,onOpen,onImport,onDemo,onDelete,onUpdate,userId,apiOrigin}:{chapters:Chapter[];settings:Settings;setSettings:(s:Settings)=>void;onOpen:(id:string)=>void;onImport:()=>void;onDemo:()=>void;onDelete:(c:Chapter)=>void;onUpdate:(c:Chapter)=>void;userId?:string;apiOrigin:string}){
  const [search,setSearch]=useState('');const [sort,setSort]=useState(()=>localStorage.getItem('nc-library-sort')??'recent');const [edit,setEdit]=useState<Chapter>();const [title,setTitle]=useState('');const [cover,setCover]=useState('');
  const filtered=useMemo(()=>chapters.filter(c=>c.title.toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title,'zh-CN',{numeric:true}):sort==='added'?b.createdAt-a.createdAt:(b.lastReadAt??b.updatedAt)-(a.lastReadAt??a.updatedAt)),[chapters,search,sort]);
  const recent=[...chapters].filter(c=>c.lastReadAt||readPosition(c.id)).sort((a,b)=>(b.lastReadAt??b.updatedAt)-(a.lastReadAt??a.updatedAt))[0];
  const coverPage=(c:Chapter)=>c.pages.find(p=>p.id===c.coverPageId)??c.pages.find(p=>p.blobKey)??c.pages[0];
  const position=(c:Chapter)=>Math.max(1,c.pages.findIndex(p=>p.id===(readPosition(c.id)?.pageId??c.pageId))+1);
  return <div className="nc-library"><div className="nc-page-heading"><div><span className="nc-eyebrow">YOUR STORIES, YOUR PACE</span><h1>我的漫画<span className="nc-title-count">{chapters.length}</span></h1><p>下一页，继续喜欢的故事。</p></div><button className="button primary" onClick={onImport}><Icon name="plus"/>导入漫画</button></div>
    {recent&&<section className="nc-continue"><Thumbnail blobKey={coverPage(recent)?.blobKey}/><div><span className="nc-eyebrow">继续阅读</span><h2>{recent.title}</h2><p>第 {position(recent)} / {recent.pages.length} 页</p></div><button className="button primary" onClick={()=>onOpen(recent.id)}>继续读 <Icon name="arrow"/></button></section>}
    {!!chapters.length&&<div className="nc-library-tools"><label className="nc-search"><Icon name="book" size={18}/><input type="search" aria-label="搜索漫画" placeholder="搜索漫画名称" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="nc-inline"><select aria-label="漫画排序" value={sort} onChange={e=>{setSort(e.target.value);localStorage.setItem('nc-library-sort',e.target.value);}}><option value="recent">最近阅读</option><option value="added">最近导入</option><option value="title">漫画名称</option></select><div className="segmented"><button aria-label="封面网格" aria-pressed={settings.libraryLayout==='grid'} className={settings.libraryLayout==='grid'?'active':''} onClick={()=>setSettings({...settings,libraryLayout:'grid'})}><Icon name="layers"/>网格</button><button aria-label="横向卡片" aria-pressed={settings.libraryLayout==='list'} className={settings.libraryLayout==='list'?'active':''} onClick={()=>setSettings({...settings,libraryLayout:'list'})}><Icon name="list"/>列表</button></div></div></div>}
    {!chapters.length?<section className="nc-empty nc-import-empty"><span className="nc-empty-symbol">✦</span><h2>把喜欢的故事带进来</h2><p>拖入漫画图片、压缩包或未加密电子书，即可开始阅读。</p><button className="button primary" onClick={onImport}><Icon name="upload"/>选择漫画文件</button><span className="nc-muted">PNG · JPG · WEBP · MOBI · CBZ/ZIP · CBR/RAR · PDF</span><button className="text-link" onClick={onDemo}>先读原创示例「星光书店」<Icon name="arrow" size={16}/></button></section>:<>
    <div className={`nc-books ${settings.libraryLayout}`}>
      {filtered.map(c=>{const at=position(c);const read=!!(c.lastReadAt||readPosition(c.id));const translated=c.pages.filter(p=>{const t=pageTranslation(p,settings.translationMode,settings.language,userId,apiOrigin);return t.ready||t.result?.output_asset_id;}).length;const missing=c.pages.every(p=>!p.blobKey);return <article className="nc-book" key={c.id}>
        <button className="nc-book-cover" aria-label={`阅读 ${c.title}`} onClick={()=>onOpen(c.id)}><Thumbnail blobKey={coverPage(c)?.blobKey} alt={`${c.title}封面`}/><span className="nc-cover-label">{c.pages.length} 页</span></button>
        <div className="nc-book-info"><h2 title={c.title}><button onClick={()=>onOpen(c.id)}>{c.title}</button></h2><p>{c.source} · {read?`读至 ${at} / ${c.pages.length} 页`:'尚未开始'}</p><div className="nc-progress" aria-label={`阅读进度 ${read?at:0} / ${c.pages.length}`}><i style={{width:`${read?at/Math.max(1,c.pages.length)*100:0}%`}}/></div><p className={missing?'nc-attention':''}>{missing?'原图需重新导入':translated?`${modeLabels[settings.translationMode]} · ${languageLabel(settings.language)} · ${translated} 页译图`:'原图已就绪'}</p><div className="nc-book-actions"><button className="button secondary" onClick={()=>onOpen(c.id)}>{read?'继续阅读':'开始阅读'}<Icon name="arrow" size={17}/></button><details className="nc-more"><summary aria-label={`管理 ${c.title}`}>•••</summary><div className="nc-menu"><button onClick={e=>{e.currentTarget.closest('details')?.removeAttribute('open');setEdit(c);setTitle(c.title);setCover(coverPage(c)?.id??'');}}>编辑名称与封面</button><button className="nc-danger-text" onClick={e=>{e.currentTarget.closest('details')?.removeAttribute('open');onDelete(c);}}>移除本地漫画</button></div></details></div></div>
      </article>;})}
    </div>{!filtered.length&&<div className="nc-empty"><h2>没有找到这本漫画</h2><p>试试名称中的其他文字。</p></div>}<footer className="nc-library-footer"><span>原图保存在本机 · 阅读进度自动记住</span><button className="text-link" onClick={onDemo}>打开原创示例</button></footer></>}
    {edit&&<Modal title="编辑漫画" onClose={()=>setEdit(undefined)}><label className="field">漫画名称<input value={title} maxLength={180} onChange={e=>setTitle(e.target.value)}/></label><label className="field">封面页面<select value={cover} onChange={e=>setCover(e.target.value)}>{edit.pages.map((p,i)=><option key={p.id} value={p.id}>第 {i+1} 页 · {p.name}</option>)}</select></label><button className="button primary full" disabled={!title.trim()} onClick={()=>{const current=chapters.find(c=>c.id===edit.id);if(current)onUpdate({...current,title:title.trim(),coverPageId:cover});setEdit(undefined);}}>保存修改</button></Modal>}
  </div>;
}
