import {msg} from '../i18n/runtime';
import {useRef,useState} from 'react';
import type {Api} from '../api';
import {Icon} from '../icons';
import {Modal} from './components';
import type {ReadingCopy,Settings} from '../types';
import type {LibraryState} from '../library/types';
import {selectRange} from '../library/model';
import {editLibrary,removeWork,removeWorks} from '../library/store';
import {Thumbnail} from '../reader/Images';
import {AcquisitionCenter} from './library/AcquisitionCenter';
import {CopyCard,CopyDetails} from './library/CopyCards';
import {CardBody} from './library/CardBody';
import {RecentlyRead,formatReadingTime,recentCopy} from './library/RecentlyRead';
import {TranslationCopies} from './library/TranslationCopies';
import {ExportComics} from './library/ExportComics';
import type {TranslationEdition} from '../library/translations';
import {LibraryEditor} from './library/LibraryEditor';
import {PublicationContents} from './library/PublicationContents';
import {copyComplete,copyCover,savedPages,relationLabels,type EditorKind,type LibraryRun,type UndoAssignment} from './library/shared';

type Props={api?:Api;userId?:string;apiOrigin?:string;onOpenTranslation:(id:string,edition:TranslationEdition)=>void;library:LibraryState;copies:ReadingCopy[];settings:Settings;setSettings:(s:Settings)=>void;onOpen:(id:string)=>void;onImport:()=>void;onDemo:()=>void;onSource:(url:string)=>void;notify:(message:string)=>void;onChanged:()=>void};
type Feedback={tone:'busy'|'success'|'error';message:string};
function useSortPreference(key:string,fallback:string){
 const [value,setValue]=useState(()=>{try{return localStorage.getItem(key)||fallback;}catch{return fallback;}});
 return [value,(next:string)=>{setValue(next);try{localStorage.setItem(key,next);}catch{/* Sorting remains usable without persistence. */}}] as const;
}
export function Library({api,userId,apiOrigin,settings,onOpenTranslation,library:s,copies,onOpen,onImport,onDemo,onSource,notify,onChanged}:Props){
 const [exporting,setExporting]=useState(false);
 const [workId,setWorkId]=useState<string>(),[tab,setTab]=useState('chapters'),[search,setSearch]=useState(''),[entrySearch,setEntrySearch]=useState(''),[role,setRole]=useState(''),[readFilter,setReadFilter]=useState('');
 const [shelfSort,setShelfSort]=useSortPreference('nc-library-shelf-sort','recent'),[entrySort,setEntrySort]=useSortPreference('nc-library-entry-sort','asc');
 const [selecting,setSelecting]=useState(false),[selected,setSelected]=useState(new Set<string>()),[anchor,setAnchor]=useState('');
 const [editor,setEditor]=useState<{kind:EditorKind;id?:string}>(),[detail,setDetail]=useState<{kind:'content'|'copy';id:string;showRelations?:boolean}>(),[acquisition,setAcquisition]=useState<{ids?:string[]}>(),[undo,setUndo]=useState<UndoAssignment>();
 const [versionFilter,setVersionFilter]=useState('all'),[copySearch,setCopySearch]=useState(''),[copySort,setCopySort]=useState('recent');
 const [busy,setBusy]=useState(''),[feedback,setFeedback]=useState<Feedback>();const operation=useRef(false);
 const work=s.works.find(w=>w.id===workId),coverages=s.coverage.filter(c=>c.workId===workId),owned=copies.filter(c=>coverages.some(x=>x.copyId===c.id));
 const relatedCopies=(id:string)=>copies.filter(c=>s.coverage.some(x=>x.workId===id&&x.copyId===c.id));
 const bestCopy=(available:ReadingCopy[],preferredId?:string)=>available.find(c=>c.id===preferredId&&savedPages(c))??[...available].sort((a,b)=>Number(savedPages(b)>0)-Number(savedPages(a)>0)||(b.lastReadAt??0)-(a.lastReadAt??0)||b.updatedAt-a.updatedAt)[0];
 const coverFor=(id:string)=>{const current=s.works.find(w=>w.id===id),available=relatedCopies(id);return copyCover(available.find(c=>c.id===current?.coverCopyId)??bestCopy(available));};
 const rowCopies=(id:string)=>owned.filter(c=>coverages.some(x=>x.copyId===c.id&&x.target.id===id));
 const allChapters=s.chapters.filter(c=>c.workId===workId),allBooks=s.publications.filter(p=>p.workIds.includes(workId??''));
 const rows=(tab==='chapters'?allChapters:allBooks).filter(row=>(row.title+' '+(row.number??'')).toLowerCase().includes(entrySearch.toLowerCase())&&(!role||!('role' in row)||row.role===role)&&(!readFilter||(readFilter==='read'?!!row.readAt:!row.readAt))).sort((a,b)=>entrySort==='desc'?b.order-a.order:entrySort==='title'?a.title.localeCompare(b.title,'zh-CN',{numeric:true}):a.order-b.order);
 const activeTasks=s.tasks.filter(t=>['queued','running'].includes(t.status)),attentionTasks=s.tasks.filter(t=>t.status==='failed'||t.status==='paused');
 const recentByWork=new Map(s.works.map(w=>[w.id,recentCopy(relatedCopies(w.id))]));
 const matchingWorks=s.works.filter(w=>(w.title+' '+w.aliases.join(' ')).toLowerCase().includes(search.toLowerCase()));
 const recentlyRead=matchingWorks.flatMap(work=>{const copy=recentByWork.get(work.id);return copy?[{work,copy}]:[];}).sort((a,b)=>b.copy.lastReadAt!-a.copy.lastReadAt!).slice(0,2);
 const filteredWorks=[...matchingWorks].sort((a,b)=>shelfSort==='title'?a.title.localeCompare(b.title,'zh-CN',{numeric:true}):shelfSort==='created'?b.createdAt-a.createdAt:shelfSort==='updated'?b.updatedAt-a.updatedAt:(recentByWork.get(b.id)?.lastReadAt??0)-(recentByWork.get(a.id)?.lastReadAt??0)||b.updatedAt-a.updatedAt);
 const selectedCopies=work?owned.filter(c=>coverages.some(x=>x.copyId===c.id&&selected.has(x.target.id))):copies.filter(c=>s.coverage.some(x=>x.copyId===c.id&&selected.has(x.workId)));
 const visibleCopies=owned.filter(c=>(versionFilter==='all'||versionFilter==='unknown'&&!c.versionId||c.versionId===versionFilter)&&(c.title+' '+c.source).toLowerCase().includes(copySearch.toLowerCase())).sort((a,b)=>copySort==='title'?a.title.localeCompare(b.title,'zh-CN',{numeric:true}):copySort==='revision'?b.manifestRevision-a.manifestRevision:b.updatedAt-a.updatedAt);
 const run:LibraryRun=async(key,label,fn,success)=>{
  if(operation.current)return false;operation.current=true;setBusy(key);setFeedback({tone:'busy',message:label+'…'});
  try{await fn();onChanged();setFeedback({tone:'success',message:success});notify(success);return true;}catch(reason){const message=reason instanceof Error?reason.message:msg("操作失败，请重试。");setFeedback({tone:'error',message:msg("{0}失败：{1}", {"0": label.replace(/^正在/,''), "1": message})});notify(message);return false;}finally{operation.current=false;setBusy('');}
 };
 function resetSelection(){setSelected(new Set());setAnchor('');setSelecting(false);}
 function openWork(id:string){setWorkId(id);setTab('chapters');setEntrySearch('');setRole('');setReadFilter('');setVersionFilter('all');setCopySearch('');setDetail(undefined);setFeedback(undefined);resetSelection();}
 function switchTab(next:string){setTab(next);setEntrySearch('');setRole('');setReadFilter('');resetSelection();}
 function edit(kind:EditorKind,id?:string){setDetail(undefined);setFeedback(undefined);setEditor({kind,id});}
 function toggleSelection(id:string,shift=false){setSelected(previous=>{const next=new Set(previous);if(shift&&anchor){for(const item of selectRange<{id:string}>(work?rows:filteredWorks,anchor,id))next.add(item);}else{next.has(id)?next.delete(id):next.add(id);}return next;});setAnchor(id);}
 function openAcquisition(ids?:string[]){setDetail(undefined);setFeedback(undefined);setAcquisition({ids});}
 function openCopy(id:string){setFeedback(undefined);setDetail({kind:'copy',id});}
 function openContent(id:string){setFeedback(undefined);setDetail({kind:'content',id});}
 const deleteButton=<button className="button danger small" disabled={!selected.size||!!busy} onClick={()=>{const ids=filteredWorks.filter(w=>selected.has(w.id)).map(w=>w.id);if(ids.length&&window.confirm(msg("删除选中的 {0} 部作品？将从书架移除作品，并自动删除其本机原图和译图。服务器图片及其他作品仍使用的文件会保留。", {"0": ids.length})))void run('remove-works',msg("正在删除作品"),async()=>{await removeWorks(ids);resetSelection();},msg("已删除 {0} 部作品及其本机原图和译图", {"0": ids.length}));}}>{msg("删除作品")}</button>;
 const captureButton=<><button className={'button secondary nc-capture-launch '+(activeTasks.length?'is-active':'')} onClick={()=>openAcquisition()}><Icon name="download"/>{msg("采集中心")}{(activeTasks.length>0||attentionTasks.length>0)&&<span className="nc-count-pill">{activeTasks.length||attentionTasks.length}</span>}</button>{work&&<button className="button secondary nc-export-launch" onClick={()=>setExporting(true)}><Icon name="folder"/>{msg("导出漫画")}</button>}</>;
 const detailRow=detail?.kind==='content'?[...allChapters,...allBooks].find(row=>row.id===detail.id):undefined,detailCopy=detail?.kind==='copy'?owned.find(c=>c.id===detail.id):undefined;
 const hasModal=!!editor||!!detailRow||!!detailCopy||!!acquisition||exporting;
 return <div className="nc-library">
  {feedback&&!hasModal&&<div className={'nc-action-feedback '+feedback.tone} role={feedback.tone==='error'?'alert':'status'}>{feedback.tone==='busy'&&<span className="spinner"/>}<span>{feedback.message}</span>{feedback.tone!=='busy'&&<button aria-label={msg("关闭操作反馈")} onClick={()=>setFeedback(undefined)}><Icon name="close" size={16}/></button>}</div>}
  {undo&&<div className="nc-undo-notice"><span>{msg("副本归属已调整")}</span><button className="text-link" disabled={!!busy} onClick={()=>void run('undo',msg("正在撤销归属调整"),async()=>{await editLibrary(state=>{const current=state.coverage.filter(c=>c.copyId===undo.copyId);if(current.length!==undo.afterIds.length||current.some(c=>!undo.afterIds.includes(c.id)))throw Error(msg("归属已再次修改，无法撤销之前的操作。"));state.coverage=state.coverage.filter(c=>c.copyId!==undo.copyId).concat(undo.before);});setUndo(undefined);},msg("已恢复副本原来的归属"))}>{msg("撤销")}</button><button className="text-link" aria-label={msg("关闭撤销提示")} onClick={()=>setUndo(undefined)}>×</button></div>}
  {!work?<>
   <div className="nc-page-heading"><div><span className="nc-eyebrow">{msg("YOUR STORIES, YOUR PACE")}</span><h1>{msg("我的漫画")}<span className="nc-title-count">{s.works.length}</span></h1><p>{msg("把喜欢的故事放上书架，随时继续上次阅读。")}</p></div><div className="nc-inline">{captureButton}<button className="button primary" onClick={onImport}><Icon name="plus"/>{msg("导入漫画")}</button></div></div>
   <div className="nc-library-tools nc-shelf-tools"><label className="nc-search"><Icon name="book" size={18}/><input type="search" aria-label={msg("搜索漫画")} placeholder={msg("搜索作品名称")} value={search} onChange={e=>{setSearch(e.target.value);setSelected(new Set());}}/></label><div className="nc-shelf-tools-actions"><label className="nc-sort-label">{msg("排序")}<select aria-label={msg("书架排序")} value={shelfSort} onChange={e=>setShelfSort(e.target.value)}><option value="recent">{msg("最近阅读")}</option><option value="updated">{msg("最近更新")}</option><option value="created">{msg("最近加入")}</option><option value="title">{msg("名称 A–Z")}</option></select></label><button className="button secondary" disabled={!!busy} onClick={()=>{resetSelection();setSelecting(!selecting);}}>{selecting?msg("完成选择"):msg("批量管理")}</button></div></div>
   {selecting&&<div className="nc-batch-toolbar nc-shelf-batch"><div className="nc-shelf-selection-info"><strong aria-live="polite">{msg("已选 {0} 部作品", {"0": selected.size})}</strong><span>{msg("点击封面选择，按住 Shift 连选")}</span></div><div className="nc-shelf-batch-actions"><button className="text-link" onClick={()=>setSelected(new Set(filteredWorks.map(w=>w.id)))}>{msg("全选 {0} 部", {"0": filteredWorks.length})}</button><button className="text-link" disabled={!selected.size} onClick={()=>setSelected(new Set())}>{msg("取消选择")}</button>{deleteButton}</div></div>}
   {!selecting&&<RecentlyRead items={recentlyRead} onOpen={onOpen} onWork={openWork}/>}
   {!selecting&&recentlyRead.length>0&&<div className="nc-section-heading nc-shelf-heading"><h2>{msg("全部漫画")}</h2><span className="nc-muted">{msg("{0} 部作品", {"0": filteredWorks.length})}</span></div>}
   {!s.works.length?<section className="nc-empty nc-import-empty"><span className="nc-empty-symbol">✦</span><h2>{msg("把喜欢的故事带进来")}</h2><p>{msg("从漫画详情页导入整部目录，或添加本地漫画文件。")}</p><button className="button primary" onClick={onImport}>{msg("选择漫画文件")}</button><span className="nc-muted">PNG · JPG · WEBP · MOBI · CBZ/ZIP · CBR/RAR · PDF</span><button className="text-link" onClick={onDemo}>{msg("先读原创示例「星光书店」")}</button></section>:!filteredWorks.length?<div className="nc-empty nc-compact-empty"><h3>{msg("没有找到这部作品")}</h3><button className="text-link" onClick={()=>setSearch('')}>{msg("清除搜索")}</button></div>:<div className="nc-books grid nc-shelf-grid">{filteredWorks.map(item=>{
    const available=relatedCopies(item.id),recent=bestCopy(available,item.preferredCopyId),chapters=s.chapters.filter(c=>c.workId===item.id),books=s.publications.filter(p=>p.workIds.includes(item.id)),read=chapters.filter(c=>c.readAt).length,lastReadAt=recentByWork.get(item.id)?.lastReadAt;
    const label=chapters.length?msg("{0} 话", {"0": chapters.length}):books.length?msg("{0} 册", {"0": books.length}):msg("{0} 份副本", {"0": available.length});
    return <article className={"nc-book "+(selecting?"is-selecting ":"")+(selected.has(item.id)?"is-selected":"")} key={item.id}><button className="nc-book-cover" aria-label={(selecting?msg("选择 "):msg("打开作品 "))+item.title} aria-pressed={selecting?selected.has(item.id):undefined} aria-describedby={'shelf-label-'+item.id} onClick={event=>selecting?toggleSelection(item.id,event.shiftKey):openWork(item.id)}><Thumbnail blobKey={coverFor(item.id)?.blobKey} alt={msg("{0}封面", {"0": item.title})}/>{selecting&&<span className={'nc-selection-check '+(selected.has(item.id)?'checked':'')}>{selected.has(item.id)?'✓':''}</span>}<span className="nc-cover-topline" id={'shelf-label-'+item.id}><span className="nc-cover-tag">{label}</span><span className="nc-cover-tag">{chapters.length?msg("已读 {0}/{1}", {"0": read, "1": chapters.length}):lastReadAt?msg("在读"):msg("未读")}</span></span><span className="nc-cover-details"><span className="nc-cover-tag"><Icon name="layers" size={13}/>{msg("{0} 份完整副本", {"0": available.filter(copyComplete).length})}</span><span className="nc-cover-reading"><Icon name="clock" size={13}/><span>{lastReadAt?<><span>{msg("最近阅读")}</span><time dateTime={new Date(lastReadAt).toISOString()}>{formatReadingTime(lastReadAt)}</time></>:msg("还没阅读")}</span></span></span></button><CardBody heading="h2" title={item.title} onTitle={()=>selecting?toggleSelection(item.id):openWork(item.id)}>
{selecting?<button className="button secondary small" aria-pressed={selected.has(item.id)} onClick={event=>toggleSelection(item.id,event.shiftKey)}>{selected.has(item.id)?msg("✓ 已选择"):msg("选择此作品")}</button>:<><button className="button primary small" onClick={()=>recent&&savedPages(recent)?onOpen(recent.id):openWork(item.id)}>{recent&&savedPages(recent)?recent.lastReadAt?msg("继续阅读"):msg("开始阅读"):msg("查看内容")}</button></>}</CardBody></article>;
   })}</div>}
  </>:<>
   <button className="text-link nc-back-link" onClick={()=>{setWorkId(undefined);resetSelection();}}>{msg("← 我的漫画")}</button>
   <div className="nc-work-hero"><Thumbnail className="nc-work-cover" blobKey={coverFor(work.id)?.blobKey} alt={msg("{0}封面", {"0": work.title})}/><div className="nc-work-summary"><span className="nc-eyebrow">{msg("MY COLLECTION")}</span><h1>{work.title}</h1><p>{msg("{0} 话", {"0": allChapters.length})}<span className="nc-meta-dot">·</span>{msg("{0} 册", {"0": allBooks.length})}<span className="nc-meta-dot">·</span>{msg("{0} 份副本", {"0": owned.length})}</p></div><div className="nc-work-hero-actions">{captureButton}<details className="nc-more-menu"><summary aria-label={msg("作品更多操作")}>•••</summary><div><button onClick={event=>{event.currentTarget.closest('details')?.removeAttribute('open');onImport();}}>{msg("添加内容")}</button><button onClick={()=>edit('work')}>{msg("编辑作品与封面")}</button><button onClick={()=>edit('relation')}>{msg("关联其他作品")}</button><button className="nc-danger-text" disabled={!!busy} onClick={()=>{if(window.confirm(msg("删除“{0}”？将从书架移除作品，并自动删除其本机原图和译图。服务器图片及其他作品仍使用的文件会保留。", {"0": work.title})))void run('remove-work',msg("正在移除作品"),async()=>{await removeWork(work.id);setWorkId(undefined);},msg("作品及其本机副本已移除"));}}>{msg("移除作品")}</button></div></details></div></div>
   <div className="nc-work-tabs" role="tablist" aria-label={msg("作品内容")}>{[['chapters',msg("章节"),allChapters.length],['publications',msg("卷册"),allBooks.length],['sources',msg("版本与副本"),owned.length],['related',msg("相关作品"),s.relations.filter(r=>r.fromId===work.id||r.toId===work.id).length]].map(([id,label,count])=><button key={id} role="tab" aria-label={String(label)} aria-selected={tab===id} onClick={()=>switchTab(String(id))}>{label}<span>{count}</span></button>)}</div>
   {['chapters','publications'].includes(tab)?<>
    <div className="nc-library-tools nc-content-tools"><div className="nc-inline"><label className="nc-search"><input type="search" aria-label={msg("搜索章节或卷册")} placeholder={tab==='chapters'?msg("搜索章节名称或编号"):msg("搜索卷册名称或编号")} value={entrySearch} onChange={e=>{setEntrySearch(e.target.value);resetSelection();}}/></label><div className="nc-filter-chips" aria-label={msg("阅读状态筛选")}>{[['',msg("全部")],['unread',msg("未读")],['read',msg("已读")]].map(([id,label])=><button key={id} aria-pressed={readFilter===id} onClick={()=>{setReadFilter(id);resetSelection();}}>{label}</button>)}</div></div><div className="nc-inline">{tab==='chapters'&&<select aria-label={msg("章节类型")} value={role} onChange={e=>{setRole(e.target.value);resetSelection();}}><option value="">{msg("全部类型")}</option><option value="main">{msg("正文")}</option><option value="extra">{msg("番外")}</option><option value="unknown">{msg("未分类")}</option></select>}<select aria-label={msg("章节卷册排序")} value={entrySort} onChange={e=>{setEntrySort(e.target.value);setAnchor('');}}><option value="asc">{msg("正序 · 从前到后")}</option><option value="desc">{msg("倒序 · 从后到前")}</option><option value="title">{msg("名称排序")}</option></select><button className={'button '+(selecting?'primary':'secondary')} onClick={()=>{resetSelection();setSelecting(!selecting);}}>{selecting?msg("完成选择"):msg("批量管理")}</button></div></div>
    {selecting&&<div className="nc-batch-toolbar"><div><strong>{msg("已选 {0} 项", {"0": selected.size})}</strong><span>{msg("按住 Shift 可连续选择")}</span></div><div className="nc-inline"><button className="text-link" onClick={()=>setSelected(new Set(rows.map(row=>row.id)))}>{msg("全选 {0} 项", {"0": rows.length})}</button><button className="text-link" disabled={!selected.size} onClick={()=>{setSelected(new Set());setAnchor('');}}>{msg("清空")}</button><button className="button secondary small" disabled={!selected.size||!!busy} onClick={()=>void run('read-selected',msg("正在标记已读"),()=>editLibrary(state=>{for(const row of tab==='chapters'?state.chapters:state.publications)if(selected.has(row.id))row.readAt=Date.now();}),msg("已将 {0} 项标记为已读", {"0": selected.size}))}>{msg("标记已读")}</button><button className="button secondary small" disabled={!selected.size||!!busy} onClick={()=>void run('unread-selected',msg("正在标记未读"),()=>editLibrary(state=>{for(const row of tab==='chapters'?state.chapters:state.publications)if(selected.has(row.id))row.readAt=undefined;}),msg("已将 {0} 项标记为未读", {"0": selected.size}))}>{msg("标记未读")}</button><button className="button primary small" disabled={!selectedCopies.some(c=>c.sourceEntryId)} onClick={()=>openAcquisition(selectedCopies.filter(c=>c.sourceEntryId).map(c=>c.id))}>{msg("在采集中心处理")}</button></div></div>}
    <div className="nc-content-grid">{rows.map(row=>{
     const available=rowCopies(row.id),chosen=bestCopy(available,work.preferredCopyId),hasPages=!!chosen&&savedPages(chosen)>0;
     return <article className={'nc-content-card '+(selected.has(row.id)?'is-selected':'')} key={row.id}>
      <button className="nc-content-cover" aria-label={selecting?msg("选择 {0}", {"0": row.title}):msg("查看 {0}", {"0": row.title})} aria-pressed={selecting?selected.has(row.id):undefined} onClick={event=>selecting?toggleSelection(row.id,event.shiftKey):openContent(row.id)}><Thumbnail blobKey={copyCover(chosen)?.blobKey} alt={row.title}/><span className="nc-content-number">{row.number||String(row.order+1).padStart(2,'0')}</span>{selecting?<span className={'nc-selection-check '+(selected.has(row.id)?'checked':'')}>{selected.has(row.id)?'✓':''}</span>:<span className={'nc-content-read '+(row.readAt?'is-read':'')}>{row.readAt?msg("已读"):msg("未读")}</span>}</button>
      <CardBody title={row.title} eyebrow={msg("{0} · {1} 份副本", {"0": ('role' in row?{main:msg("正文"),extra:msg("番外"),unknown:msg("章节")}[row.role]:msg("卷册")), "1": available.length})} metadata={[hasPages?msg("{0} 页可读", {"0": savedPages(chosen!)}):msg("尚无本地原图"),available.length>1?msg("可在详情中切换副本"):'']}>
       {selecting?<button className="button secondary small full" aria-pressed={selected.has(row.id)} onClick={event=>toggleSelection(row.id,event.shiftKey)}>{selected.has(row.id)?msg("✓ 已选择"):msg("选择此项")}</button>:<><button className="button primary small" disabled={!hasPages} title={!hasPages?msg("尚无本地原图，可在详情中查看副本"):undefined} onClick={()=>chosen&&onOpen(chosen.id)}>{chosen?.lastReadAt?msg("继续阅读"):msg("阅读")}</button></>}
      </CardBody>
     </article>;
    })}</div>
    {!rows.length&&<div className="nc-empty nc-compact-empty"><h3>{entrySearch||readFilter||role?msg("没有匹配的内容"):tab==='chapters'?msg("还没有章节"):msg("还没有卷册")}</h3><p>{entrySearch||readFilter||role?msg("调整搜索或筛选继续查看。"):msg("已导入但未分类的材料可在“版本与副本”中整理。")}</p>{!(entrySearch||readFilter||role)&&<button className="text-link" onClick={()=>switchTab('sources')}>{msg("查看已有副本")}</button>}</div>}
   </>:tab==='sources'?<>
    <TranslationCopies copies={owned} userId={userId} origin={apiOrigin} onOpen={onOpenTranslation}/>
    <div className="nc-section-heading nc-version-heading"><div><h2>{msg("原始副本")}</h2><p className="nc-muted">{msg("网站采集与本地导入的原始内容。可标注内容版本或设置优先阅读。")}</p></div><button className="button secondary" onClick={()=>edit('version')}><Icon name="plus" size={16}/>{msg("新建内容版本")}</button></div>
    <div className="nc-version-filter-grid"><button className="nc-version-filter" aria-pressed={versionFilter==='all'} onClick={()=>setVersionFilter('all')}><span><strong>{msg("全部副本")}</strong><small>{msg("所有内容版本")}</small></span><b>{owned.length}</b></button>{s.versions.filter(v=>v.workId===work.id).map(v=>{const description=[v.language,v.translator].filter(Boolean).join(' · ')||msg("内容版本");return <button className="nc-version-filter" key={v.id} aria-pressed={versionFilter===v.id} onClick={()=>setVersionFilter(v.id)}><span><strong title={v.title}>{v.title}</strong><small title={description}>{description}</small></span><b>{owned.filter(c=>c.versionId===v.id).length}</b></button>;})}<button className="nc-version-filter" aria-pressed={versionFilter==='unknown'} onClick={()=>setVersionFilter('unknown')}><span><strong>{msg("版本未标注")}</strong><small>{msg("保留副本原始信息")}</small></span><b>{owned.filter(c=>!c.versionId).length}</b></button></div>
    <div className="nc-library-tools"><label className="nc-search"><input type="search" aria-label={msg("搜索副本")} placeholder={msg("搜索副本名称或来源")} value={copySearch} onChange={e=>setCopySearch(e.target.value)}/></label><select aria-label={msg("副本排序")} value={copySort} onChange={e=>setCopySort(e.target.value)}><option value="recent">{msg("最近更新")}</option><option value="title">{msg("名称排序")}</option><option value="revision">{msg("修订号从新到旧")}</option></select></div>
    <div className="nc-copy-grid">{visibleCopies.map(copy=><CopyCard key={copy.id} copy={copy} library={s} preferred={work.preferredCopyId===copy.id} onOpen={onOpen} onDetails={openCopy}/>)}</div>{!visibleCopies.length&&<div className="nc-empty nc-compact-empty"><h3>{msg("此视图暂无副本")}</h3><p>{msg("切换版本筛选，或添加新的漫画内容。")}</p></div>}
   </>:<>
    <div className="nc-section-heading nc-version-heading"><div><h2>{msg("相关作品")}</h2><p className="nc-muted">{msg("把续作、前传与外传放在一起。")}</p></div><button className="button secondary" onClick={()=>edit('relation')}>{msg("关联作品")}</button></div><div className="nc-related-grid">{s.relations.filter(r=>r.fromId===work.id||r.toId===work.id).map(relation=>{const related=s.works.find(w=>w.id===(relation.fromId===work.id?relation.toId:relation.fromId));if(!related)return null;const available=relatedCopies(related.id);return <article className="nc-related-card" key={relation.id}><button className="nc-content-cover" aria-label={msg("打开作品 {0}", {"0": related.title})} onClick={()=>openWork(related.id)}><Thumbnail blobKey={coverFor(related.id)?.blobKey} alt={related.title}/></button><CardBody title={related.title} onTitle={()=>openWork(related.id)} eyebrow={relationLabels[relation.kind]} metadata={[msg("{0} 话 · {1} 册", {"0": s.chapters.filter(c=>c.workId===related.id).length, "1": s.publications.filter(p=>p.workIds.includes(related.id)).length}),msg("{0} 份完整副本", {"0": available.filter(copyComplete).length})]}><button className="button secondary small" disabled={!!busy} onClick={()=>void run('unlink:'+relation.id,msg("正在解除关联"),()=>editLibrary(state=>{state.relations=state.relations.filter(r=>r.id!==relation.id);}),msg("已解除与「{0}」的关联", {"0": related.title}))}>{msg("解除关联")}</button></CardBody></article>;})}</div>{!s.relations.some(r=>r.fromId===work.id||r.toId===work.id)&&<div className="nc-empty nc-compact-empty"><h3>{msg("暂未关联其他作品")}</h3><p>{msg("通过上方“关联作品”整理同一故事的其他作品。")}</p></div>}
   </>}
  </>}
  {work&&detailRow&&<Modal title={detailRow.title} subtitle={msg("{0}详情", {"0": ('role' in detailRow?msg("章节"):msg("卷册"))})} onClose={()=>setDetail(undefined)}><div className="nc-content-detail-toolbar"><span className="nc-status-badge">{detailRow.readAt?msg("已读"):msg("未读")}</span><button className="text-link" disabled={!!busy} onClick={()=>void run('read:'+detailRow.id,msg("正在更新阅读状态"),()=>editLibrary(state=>{const row=[...state.chapters,...state.publications].find(x=>x.id===detailRow.id);if(!row)throw Error(msg("内容已移除。"));row.readAt=detailRow.readAt?undefined:Date.now();}),detailRow.title+(detailRow.readAt?msg("已标记未读"):msg("已标记已读")))}>{detailRow.readAt?msg("标记未读"):msg("标记已读")}</button><button className="text-link" onClick={()=>edit('role' in detailRow?'chapter':'publication',detailRow.id)}>{msg("编辑信息")}</button></div>{feedback&&<div className={'nc-action-feedback '+feedback.tone} role={feedback.tone==='error'?'alert':'status'}>{feedback.message}</div>}<div className="nc-copy-grid nc-modal-copy-grid">{rowCopies(detailRow.id).map(copy=><CopyCard key={copy.id} copy={copy} library={s} preferred={work.preferredCopyId===copy.id} onOpen={id=>{setDetail(undefined);onOpen(id);}} onDetails={openCopy}/>)}</div>{!rowCopies(detailRow.id).length&&<p className="nc-empty">{msg("尚无副本。导入文件后，可在副本详情中纠正归属以关联此内容。")}</p>}{!('role' in detailRow)&&<PublicationContents publicationId={detailRow.id} library={s} initiallyOpen={detail?.showRelations} onEdit={kind=>edit(kind,detailRow.id)}/>}</Modal>}
  {work&&detailCopy&&<CopyDetails copy={detailCopy} work={work} library={s} busy={busy} feedback={feedback} run={run} onOpen={onOpen} onEdit={edit} onClose={()=>setDetail(undefined)} onAcquisition={openAcquisition}/>}
  {work&&editor&&<LibraryEditor key={editor.kind+':'+editor.id} {...editor} work={work} library={s} copies={owned} run={run} busy={!!busy} onClose={()=>{if(editor.id&&(editor.kind==='inclusion'||editor.kind==='publicationRelations'))setDetail({kind:'content',id:editor.id,showRelations:true});setEditor(undefined);}} onUndo={setUndo}/>}
  {acquisition&&<AcquisitionCenter library={s} copies={copies} initialWorkId={workId} onlyIds={acquisition.ids} busy={busy} feedback={feedback} run={run} onOpen={onOpen} onSource={onSource} onClose={()=>setAcquisition(undefined)}/>}
  {work&&exporting&&<ExportComics work={work} library={s} copies={copies} settings={settings} api={api} userId={userId} apiOrigin={apiOrigin} onClose={()=>setExporting(false)}/>}
 </div>;
}
