import {useEffect,useState} from 'react';
import type {Api} from '../api';
import type {Usage,UsageSummary} from '../types';
import {Icon} from '../icons';
export function UsagePage({api,onLogin}:{api:Api;onLogin:()=>void}){
  const [days,setDays]=useState(7);const [data,setData]=useState<UsageSummary>();const [error,setError]=useState('');const [refresh,setRefresh]=useState(0);const [ledger,setLedger]=useState(false);
  const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';
  useEffect(()=>{if(!api.token)return;let live=true;let timer:ReturnType<typeof setTimeout>;setData(undefined);async function fetchSummary(){try{const d=await api.usageSummary(days,timezone);if(live&&api.isCurrent()){setData(d);setError('');}}catch(e){if(live&&api.isCurrent())setError((e as Error).message);}if(live)timer=setTimeout(fetchSummary,15000);}void fetchSummary();return()=>{live=false;clearTimeout(timer);};},[api,days,timezone,refresh]);
  const max=Math.max(1,...(data?.days.map(d=>d.settled)??[]));
  return <div><div className="nc-page-heading"><div><span className="nc-eyebrow">READ MORE, KNOW YOUR USAGE</span><h1>用量统计</h1><p>点数花在哪里，一眼就清楚。</p></div>{api.token&&<div className="nc-inline"><select aria-label="统计时间范围" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>最近 7 天</option><option value={30}>最近 30 天</option><option value={90}>最近 90 天</option></select><button className="icon-button" aria-label="刷新用量" onClick={()=>setRefresh(v=>v+1)}><Icon name="refresh"/></button></div>}</div>
    {!api.token?<div className="nc-empty"><Icon name="coin" size={36}/><h2>登录后查看用量</h2><p>成功交付后结算，预占与实际消耗分别记录。</p><button className="button primary" onClick={onLogin}>登录账户</button></div>:<>{error&&<p className="nc-error" role="alert">{error}<button className="text-link" onClick={()=>setRefresh(v=>v+1)}>重试</button></p>}{!data&&!error?<p className="nc-loading">正在汇总全部用量…</p>:data&&<><section className="nc-live-quota"><span><Icon name="coin" size={19}/>当前可用 <b>{data.available.toLocaleString()}</b> 点</span><span>任务预占 <b>{data.reserved.toLocaleString()}</b> 点</span><small>当前账户额度 · 不受日期筛选影响</small></section><div className="nc-stat-grid"><div className="nc-stat"><span>本期已结算</span><b>{data.settled.toLocaleString()}<small>点</small></b><p>按实际结算统计</p></div><div className="nc-stat"><span>本期交付</span><b>{data.delivered.toLocaleString()}<small>个结果</small></b><p>不重复计算复用结果</p></div><div className="nc-stat"><span>本期免费交付</span><b>{data.free_delivered.toLocaleString()}<small>个结果</small></b><p>含部分文字保留原文的交付</p></div></div><div className="nc-usage-charts"><section className="nc-chart-card"><h2>每日用量</h2><p>{data.start_date} — {data.end_date} · {data.timezone}</p><div className="nc-bar-chart" role="img" aria-label={`最近 ${days} 天已结算 ${data.settled} 点`}><div className="nc-chart-bars">{data.days.map(d=><div className="nc-chart-column" key={d.date} title={`${d.date}：${d.settled} 点`}><div className="nc-chart-bar" style={{height:`${d.settled/max*100}%`}}/><span>{days<=7?d.date.slice(5):''}</span></div>)}</div></div>{data.settled===0&&<p className="nc-chart-zero">本期暂无已结算用量</p>}<details className="nc-chart-data"><summary>查看每日数值</summary><div className="nc-data-table"><table><thead><tr><th>日期</th><th>常规</th><th>AI 重绘</th><th>其他</th><th>合计</th></tr></thead><tbody>{data.days.map(d=><tr key={d.date}><td>{d.date}</td><td>{d.classic}</td><td>{d.redraw}</td><td>{d.unclassified}</td><td>{d.settled}</td></tr>)}</tbody></table></div></details></section><section className="nc-chart-card"><h2>翻译方式分布</h2><p>按本期实际结算点数</p>{[['classic','常规翻译'],['redraw','AI 重绘'],...(data.by_mode.unclassified?[['unclassified','其他']]:[])].map(([mode,label])=><div className="nc-mode-usage" key={mode}><div><span>{label}</span><b>{data.by_mode[mode]??0} 点</b></div><div className="nc-progress"><i style={{width:`${(data.by_mode[mode]??0)/Math.max(1,data.settled)*100}%`}}/></div><p>{data.settled?Math.round((data.by_mode[mode]??0)/data.settled*100):0}%</p></div>)}</section></div><p className="nc-muted">按 {timezone} 的自然日统计。预占、释放和额度发放不计入消费。</p><section className="settings-card"><div className="nc-section-heading"><div><h2>点数明细</h2><p className="nc-muted">账户全部交易，包含预占与释放</p></div><button className="button secondary" aria-expanded={ledger} onClick={()=>setLedger(v=>!v)}>{ledger?'收起明细':'展开明细'}</button></div>{ledger&&<Ledger api={api}/>}</section></>}</>}
  </div>;
}
function Ledger({api}:{api:Api}){
  const [data,setData]=useState<Usage>();const [offset,setOffset]=useState(0);const [error,setError]=useState('');const [retry,setRetry]=useState(0);
  useEffect(()=>{let live=true;setData(undefined);setError('');void api.usage(offset).then(d=>{if(live&&api.isCurrent())setData(d);}).catch(e=>{if(live&&api.isCurrent())setError(e.message);});return()=>{live=false};},[api,offset,retry]);
  return <>{error?<p className="inline-error" role="alert">{error}<button className="text-link" onClick={()=>setRetry(v=>v+1)}>重试</button></p>:!data?<p className="nc-loading">正在读取明细…</p>:<><div className="nc-data-table"><table><thead><tr><th>时间</th><th>类型</th><th>点数</th><th>说明</th></tr></thead><tbody>{data.items.map(row=><tr key={row.id}><td>{new Date(row.created_at).toLocaleString()}</td><td>{{reserve:'预占额度',settle:'翻译结算',release:'释放预占',grant:'额度发放'}[row.kind]??row.kind}</td><td>{row.kind==='settle'?'−':row.kind==='grant'?'+':''}{row.amount}</td><td>{row.note|| (row.job_id?`任务 ${row.job_id.slice(0,8)}`:'—')}</td></tr>)}</tbody></table></div>{!data.items.length&&<p className="nc-empty-copy">暂无点数明细</p>}<div className="nc-pagination"><span>共 {data.total} 条</span><button className="button secondary" disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-20))}>上一页</button><button className="button secondary" disabled={data.next_offset==null} onClick={()=>setOffset(data.next_offset!)}>下一页</button></div></> }</>;
}
