import {useRef,useState} from 'react';
import {msg,formatDate} from '../i18n/runtime';
import {Icon} from '../icons';
import {Thumbnail} from '../reader/Images';
import {continueDocument,coverReference,preferredDocument,removeDocument,removeWork,type Document,type ReadingUnit,type Work} from '../comics/application/library-service';
import {moveDocument,reorderReadingUnits,setPreferredDocument,setUnitRead,setWorkCover,updateDocument,updateReadingUnit,updateWork} from '../comics/application/work-management';
import {reindexDocument} from '../comics/application/import-service';
import type {ImportAssignment,LibraryViewModel} from '../comics/application/types';
import {Modal} from './components';
import {CardBody} from './CardBody';
import {useContextMenu} from './ContextMenu';
import {SourceTag} from './SourceTag';
import {Select} from './Select';
import './work-details.css';

type Props={initialDialog?:'work'|'remove-work';work:Work;library:LibraryViewModel;onBack:()=>void;onOpen:(id:string)=>void;onImport:(assignment?:ImportAssignment)=>void;onChanged:()=>void|Promise<void>;notify:(message:string)=>void;onExport:(doc:Document)=>void};
type Dialog={kind:'work'|'unit'|'document'|'versions'|'cover'|'move'|'remove-work'|'remove-document'|'remove-selected';id?:string};
export const unitKindLabel=(kind:string)=>kind==='chapter'?msg('章节'):kind==='volume'?msg('卷册'):kind==='book'?msg('单行本'):msg('未分类');
const roleLabel=(role:string)=>role==='main'?msg('正文'):role==='extra'?msg('番外'):msg('未分类');
const readable=(doc?:Document)=>!!doc&&(doc.indexState==='ready'||doc.format==='website');
const status=(doc:Document)=>readable(doc)?msg('可以阅读'):doc.indexState==='failed'?msg('需要恢复目录'):msg('目录待完成');

export function WorkDetails({initialDialog,work,library,onBack,onOpen,onImport,onChanged,notify,onExport}:Props){
 const contextMenu=useContextMenu();
 const [kind,setKind]=useState('all'),[role,setRole]=useState('all'),[read,setRead]=useState('all'),[query,setQuery]=useState(''),[sort,setSort]=useState('order'),[offset,setOffset]=useState(0);
 const [selecting,setSelecting]=useState(false),[selected,setSelected]=useState(new Set<string>()),[ordering,setOrdering]=useState(false);
 const [dialog,setDialog]=useState<Dialog|undefined>(initialDialog?{kind:initialDialog}:undefined),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const operating=useRef(false),anchor=useRef<string|undefined>(undefined);
 const units=library.units.filter(u=>u.workId===work.id).sort((a,b)=>a.order-b.order||a.id.localeCompare(b.id)),unitIds=new Set(units.map(u=>u.id));
 const docs=library.documents.filter(d=>unitIds.has(d.unitId)),documentsFor=(unitId:string)=>docs.filter(d=>d.unitId===unitId);
 const next=continueDocument(work.id,library),cover=docs.find(d=>d.id===work.cover?.documentId&&d.revisionId===work.cover.revisionId)??next;
 const positions=library.positions??[],readCount=units.filter(u=>u.readAt).length;
 const matching=units.filter(u=>(kind==='all'||u.kind===kind)&&(role==='all'||u.role===role)&&(read==='all'||(read==='read'?!!u.readAt:!u.readAt))&&(u.title+' '+documentsFor(u.id).map(d=>d.title+' '+(d.versionLabel??'')).join(' ')).toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title,undefined,{numeric:true}):sort==='newest'?b.createdAt-a.createdAt:a.order-b.order);
 const pageOffset=Math.min(offset,Math.max(0,Math.floor((matching.length-1)/48)*48)),shown=matching.slice(pageOffset,pageOffset+48);
 const chosen=units.filter(u=>selected.has(u.id));
 const unit=units.find(u=>u.id===dialog?.id),document=docs.find(d=>d.id===dialog?.id);
 const openDialog=(value:Dialog)=>{setError('');setDialog(value);};
 const closeDialog=()=>{if(!busy){setDialog(undefined);setError('');}};
 async function run(action:()=>Promise<unknown>,success:string,close=false){
  if(operating.current)return false;operating.current=true;setBusy(true);setError('');
  try{await action();await onChanged();notify(success);if(close)setDialog(undefined);return true;}catch(reason){const message=reason instanceof Error?reason.message:msg('操作失败，请重试。');setError(message);return false;}finally{operating.current=false;setBusy(false);}
 }
 function toggle(id:string,shift:boolean){
  setSelected(previous=>{const value=new Set(previous),from=matching.findIndex(u=>u.id===anchor.current),to=matching.findIndex(u=>u.id===id);const ids=shift&&from>=0?matching.slice(Math.min(from,to),Math.max(from,to)+1).map(u=>u.id):[id];for(const key of ids)previous.has(id)?value.delete(key):value.add(key);return value;});anchor.current=id;
 }
 function importInto(target?:ReadingUnit){onImport({workId:work.id,title:work.title,kind:target?.kind??(kind==='all'?'unclassified':kind as ReadingUnit['kind']),role:target?.role??'unknown',unitId:target?.id});}
 function changeOrder(id:string,delta:number){const order=units.map(u=>u.id),at=order.indexOf(id),to=at+delta;if(to<0||to>=order.length)return;[order[at],order[to]]=[order[to],order[at]];void run(()=>reorderReadingUnits(work.id,order),msg('阅读顺序已更新'));}
 return <div className="nc-library nc-work-detail">
  <button className="text-link nc-back-link" onClick={onBack}>{msg('← 我的漫画')}</button>
  <section className="nc-work-hero nc-work-overview" aria-label={msg('作品概览')}>
   <div className="nc-work-identity"><button className="nc-work-cover-button" aria-label={msg('更换作品封面')} onClick={()=>openDialog({kind:'cover'})}><Thumbnail className="nc-work-cover" blobKey={cover&&coverReference(cover)} alt={work.title}/><span>{msg('更换封面')}</span></button>
   <div className="nc-work-summary"><span className="nc-eyebrow">MY COLLECTION</span><h1>{work.title}</h1>{!!work.creators?.length&&<p className="nc-work-creators">{work.creators.join(' / ')}</p>}{!!work.aliases?.length&&<p className="nc-work-aliases">{work.aliases.join(' · ')}</p>}<dl className="nc-work-stats"><div className="nc-work-stat is-source"><dt><Icon name="globe" size={14}/>{msg('来源')}</dt><dd><SourceTag sources={library.workSources?.[work.id]}/></dd></div><div className="nc-work-stat"><dt><Icon name="list" size={14}/>{msg('阅读单元')}</dt><dd>{units.length}</dd></div><div className="nc-work-stat"><dt><Icon name="layers" size={14}/>{msg('版本')}</dt><dd>{docs.length}</dd></div><div className="nc-work-stat is-read"><dt><Icon name="check" size={14}/>{msg('已读')}</dt><dd>{readCount}<span> / {units.length}</span></dd></div></dl>{work.description&&<p className="nc-work-description">{work.description}</p>}
   </div></div>
   <div className="nc-work-action-panel"><div className="nc-work-primary-actions"><button className="button primary" disabled={!readable(next)} onClick={()=>next&&onOpen(next.id)}><Icon name="book"/>{work.lastReadAt?msg('继续阅读'):msg('开始阅读')}</button><details className="nc-more-menu nc-work-more"><summary aria-label={msg('更多作品操作')}><span className="nc-more-dots" aria-hidden="true"><i/><i/><i/></span></summary><div onClick={event=>{if((event.target as HTMLElement).closest('button'))event.currentTarget.parentElement?.removeAttribute('open');}}><button onClick={()=>importInto()}>{msg('添加内容')}</button><button onClick={()=>openDialog({kind:'work'})}>{msg('编辑作品')}</button><button className="nc-danger-text" onClick={()=>openDialog({kind:'remove-work'})}>{msg('移除作品')}</button></div></details></div>
    <p className="nc-work-resume"><Icon name="clock" size={15}/>{work.lastReadAt?<span>{msg('最近阅读')}<time dateTime={new Date(work.lastReadAt).toISOString()}>{formatDate(work.lastReadAt,true)}</time></span>:<span>{msg('还没阅读')}</span>}</p>
   </div>
  </section>
  {error&&!dialog&&<p className="nc-action-feedback error" role="alert">{error}</p>}
  <nav className="nc-work-tabs" aria-label={msg('内容分类')}>{['all','chapter','volume','book','unclassified'].map(value=><button key={value} aria-current={kind===value?'page':undefined} aria-pressed={kind===value} disabled={ordering} onClick={()=>{setKind(value);setOffset(0);}}>{value==='all'?msg('全部内容'):unitKindLabel(value)}<span>{value==='all'?units.length:units.filter(u=>u.kind===value).length}</span></button>)}</nav>
  <div className="nc-work-toolbar"><label className="nc-search"><Icon name="list" size={17}/><input type="search" aria-label={msg('搜索章节或卷册')} placeholder={msg('搜索章节或卷册')} value={query} disabled={ordering} onChange={e=>{setQuery(e.target.value);setOffset(0);}}/></label><label>{msg('内容性质')}<Select aria-label={msg('内容性质筛选')} disabled={ordering} value={role} onChange={e=>{setRole(e.target.value);setOffset(0);}}><option value="all">{msg('全部')}</option><option value="main">{msg('正文')}</option><option value="extra">{msg('番外')}</option><option value="unknown">{msg('未分类')}</option></Select></label><label>{msg('阅读状态')}<Select aria-label={msg('阅读状态筛选')} disabled={ordering} value={read} onChange={e=>{setRead(e.target.value);setOffset(0);}}><option value="all">{msg('全部')}</option><option value="unread">{msg('未读')}</option><option value="read">{msg('已读')}</option></Select></label><label>{msg('排序')}<Select aria-label={msg('目录排序')} disabled={ordering} value={sort} onChange={e=>{setSort(e.target.value);setOffset(0);}}><option value="order">{msg('阅读顺序')}</option><option value="title">{msg('按名称')}</option><option value="newest">{msg('最近添加')}</option></Select></label></div>
  <div className="nc-section-heading nc-work-list-heading"><span className="nc-muted">{msg('{0} 个阅读单元',{'0':matching.length})}</span><div><button className="text-link" disabled={busy||!units.length||selecting} onClick={()=>{setOrdering(!ordering);setKind('all');setRole('all');setRead('all');setQuery('');setSort('order');setOffset(0);}}>{ordering?msg('完成排序'):msg('调整顺序')}</button><button className="button secondary small" disabled={busy||ordering||!units.length} onClick={()=>{setSelecting(!selecting);setSelected(new Set());}}>{selecting?msg('完成整理'):msg('批量整理')}</button></div></div>
  {selecting&&<div className="nc-batch-toolbar" aria-label={msg('批量整理')}><div><strong>{msg('已选择 {0} 项',{'0':chosen.length})}</strong><button className="text-link" onClick={()=>setSelected(new Set(matching.map(u=>u.id)))}>{msg('全选筛选结果')}</button><button className="text-link" onClick={()=>setSelected(new Set())}>{msg('清空选择')}</button></div><div className="nc-inline"><button className="button secondary small" disabled={busy||!chosen.length} onClick={()=>void run(()=>setUnitRead(chosen.map(u=>u.id),true),msg('阅读状态已更新'))}>{msg('标记已读')}</button><button className="button secondary small" disabled={busy||!chosen.length} onClick={()=>void run(()=>setUnitRead(chosen.map(u=>u.id),false),msg('阅读状态已更新'))}>{msg('标记未读')}</button><button className="text-link nc-danger-text" disabled={busy||!chosen.length} onClick={()=>openDialog({kind:'remove-selected'})}>{msg('移除所选')}</button></div></div>}
  {ordering&&<p className="notice">{msg('使用上移、下移调整阅读顺序，每次调整自动保存。')}</p>}
  <div className="nc-content-grid nc-work-content-grid">{shown.map(item=>{
   const versions=documentsFor(item.id),doc=preferredDocument(item,versions,positions),hasPosition=doc&&positions.some(p=>p.documentId===doc.id&&p.revisionId===doc.revisionId),at=units.findIndex(u=>u.id===item.id);
   return <article className={'nc-content-card'+(selected.has(item.id)?' is-selected':'')} key={item.id} data-unit-id={item.id} {...contextMenu.bind(item.title,[
    {label:msg('版本与来源'),disabled:busy,onSelect:()=>openDialog({kind:'versions',id:item.id})},
    {label:msg('编辑条目'),disabled:busy,onSelect:()=>openDialog({kind:'unit',id:item.id})},
    {label:item.readAt?msg('标记未读'):msg('标记已读'),disabled:busy,onSelect:()=>void run(()=>setUnitRead([item.id],!item.readAt),msg('阅读状态已更新'))},
   ])}>
    <button className="nc-content-cover" aria-label={selecting?msg('选择 {0}',{'0':item.title}):msg('查看 {0}',{'0':item.title})} aria-pressed={selecting?selected.has(item.id):undefined} onClick={event=>selecting?toggle(item.id,event.shiftKey):openDialog({kind:'versions',id:item.id})}>
     <Thumbnail blobKey={doc&&coverReference(doc)} alt={item.title}/>
     <span className="nc-cover-topline"><span className="nc-cover-tag">{unitKindLabel(item.kind)}{item.role!=='unknown'?' · '+roleLabel(item.role):''}</span></span>
     <span className="nc-cover-details"><span className="nc-cover-tag-row"><span className="nc-cover-tag">{doc?.pageCount!==undefined?msg('{0} 页',{'0':doc.pageCount}):msg('页数待确认')}</span><span className="nc-cover-tag">{msg('{0} 个版本',{'0':versions.length})}</span></span><SourceTag sources={versions.flatMap(version=>library.documentSources?.[version.id]?[library.documentSources[version.id]]:[])}/>{(doc?.versionLabel||doc?.language)&&<span className="nc-cover-tag nc-version-tag" title={[doc.versionLabel,doc.language].filter(Boolean).join(' · ')}>{[doc.versionLabel,doc.language].filter(Boolean).join(' · ')}</span>}{doc&&!readable(doc)&&<span className="nc-cover-tag nc-cover-status">{status(doc)}</span>}</span>
     {selecting?<span className={'nc-selection-check'+(selected.has(item.id)?' checked':'')}>{selected.has(item.id)&&<Icon name="check" size={15}/>}</span>:<span className="nc-content-read" data-state={item.readAt?'read':hasPosition?'reading':'unread'}><Icon name={item.readAt?'check':hasPosition?'clock':'book'} size={12}/>{item.readAt?msg('已读'):hasPosition?msg('阅读中'):msg('未读')}</span>}
    </button>
    <CardBody title={item.title} heading="h2" onTitle={()=>openDialog({kind:'versions',id:item.id})}>
     <button className="button primary small" disabled={!readable(doc)} onClick={()=>doc&&onOpen(doc.id)}>{hasPosition?msg('继续阅读'):msg('开始阅读')}</button>
    </CardBody>
    {ordering&&<div className="nc-order-controls"><button className="button secondary small" aria-label={msg('上移 {0}',{'0':item.title})} disabled={busy||at===0} onClick={()=>changeOrder(item.id,-1)}>{msg('上移')}</button><span>{at+1}</span><button className="button secondary small" aria-label={msg('下移 {0}',{'0':item.title})} disabled={busy||at===units.length-1} onClick={()=>changeOrder(item.id,1)}>{msg('下移')}</button></div>}
   </article>;
  })}</div>
  {!matching.length&&<div className="nc-empty nc-compact-empty"><h3>{units.length?msg('没有符合筛选条件的内容'):msg('还没有阅读内容')}</h3><p>{units.length?msg('试试其他关键词或清除筛选。'):msg('将文件加入这部作品，按章节或卷册整理。')}</p><button className="button secondary" onClick={()=>{if(units.length){setQuery('');setKind('all');setRole('all');setRead('all');}else importInto();}}>{units.length?msg('清除筛选'):msg('添加内容')}</button></div>}
  {matching.length>48&&<nav className="nc-card-actions" aria-label={msg('目录分页')}><button className="button secondary" disabled={!pageOffset} onClick={()=>setOffset(pageOffset-48)}>{msg('上一页')}</button><span>{msg('第 {0}–{1} 项',{'0':pageOffset+1,'1':Math.min(pageOffset+48,matching.length)})}</span><button className="button secondary" disabled={pageOffset+48>=matching.length} onClick={()=>setOffset(pageOffset+48)}>{msg('下一页')}</button></nav>}
  {contextMenu.menu}
  {dialog?.kind==='work'&&<MetadataEditor kind="work" work={work} busy={busy} error={error} onClose={closeDialog} onSave={value=>void run(()=>updateWork(work.id,value),msg('作品资料已更新'),true)}/>}
  {dialog?.kind==='unit'&&unit&&<MetadataEditor key={unit.id} kind="unit" unit={unit} busy={busy} error={error} onClose={closeDialog} onSave={value=>void run(()=>updateReadingUnit(unit.id,value),msg('条目已更新'),true)}/>}
  {dialog?.kind==='document'&&document&&<MetadataEditor key={document.id} kind="document" document={document} busy={busy} error={error} onClose={closeDialog} onSave={value=>void run(()=>updateDocument(document.id,value),msg('版本资料已更新'),true)}/>}
  {dialog?.kind==='versions'&&unit&&<Modal title={msg('版本与来源')} subtitle={unit.title} onClose={closeDialog} className="nc-work-versions-modal"><p className="nc-muted">{msg('首选版本用于目录阅读；每个版本保留独立阅读位置。')}</p><div className="nc-version-list">{documentsFor(unit.id).map(doc=><article key={doc.id} className="nc-version-row" data-document-id={doc.id}><Thumbnail blobKey={coverReference(doc)} alt={doc.title}/><div><div className="nc-version-title"><h3>{doc.title}</h3>{unit.preferredDocumentId===doc.id&&<span className="nc-count-pill">{msg('首选版本')}</span>}</div><p>{doc.format.toUpperCase()}{doc.versionLabel?' · '+doc.versionLabel:''}{doc.language?' · '+doc.language:''} · {doc.pageCount!==undefined?msg('{0} 页',{'0':doc.pageCount}):msg('页数待确认')}</p><p>{library.documentSources?.[doc.id]?.label}{library.documentSources?.[doc.id]?.label?' · ':''}{status(doc)}</p>{doc.error&&<p className="error-message">{doc.error}</p>}<div className="nc-version-actions">{readable(doc)?<button className="button primary small" onClick={()=>onOpen(doc.id)}>{positions.some(p=>p.documentId===doc.id&&p.revisionId===doc.revisionId)?msg('继续阅读'):msg('开始阅读')}</button>:<button className="button secondary small" disabled={busy} onClick={()=>void run(()=>reindexDocument(doc.id),msg('目录已恢复'))}>{msg('恢复目录')}</button>}<button className="button secondary small" disabled={busy||unit.preferredDocumentId===doc.id} onClick={()=>void run(()=>setPreferredDocument(unit.id,doc.id),msg('首选版本已更新'))}>{unit.preferredDocumentId===doc.id?msg('已设为首选'):msg('设为首选')}</button></div><details className="nc-detail-more nc-version-more"><summary>{msg('更多版本操作')}</summary><div className="nc-detail-action-list"><button className="text-link" disabled={doc.indexState!=='ready'} onClick={()=>{setDialog(undefined);onExport(doc);}}>{msg('导出')}</button><button className="text-link" onClick={()=>openDialog({kind:'document',id:doc.id})}>{msg('编辑版本')}</button><button className="text-link" onClick={()=>openDialog({kind:'move',id:doc.id})}>{msg('纠正归属')}</button><button className="text-link nc-danger-text" onClick={()=>openDialog({kind:'remove-document',id:doc.id})}>{msg('移除版本')}</button></div></details></div></article>)}</div>{error&&<p role="alert" className="error-message">{error}</p>}<div className="nc-modal-footer"><button className="button secondary" disabled={busy} onClick={closeDialog}>{msg('关闭')}</button><button className="button primary" disabled={busy} onClick={()=>{setDialog(undefined);importInto(unit);}}><Icon name="plus"/>{msg('添加其他版本')}</button></div></Modal>}
  {dialog?.kind==='cover'&&<Modal title={msg('更换作品封面')} subtitle={msg('选择一个版本的封面作为作品封面。')} className="nc-work-versions-modal" onClose={closeDialog}><div className="nc-cover-choices">{docs.filter(d=>d.coverPageId).map(doc=><button key={doc.id} className="nc-cover-choice" aria-pressed={work.cover?.documentId===doc.id} disabled={busy} onClick={()=>void run(()=>setWorkCover(work.id,doc.id),msg('作品封面已更新'),true)}><Thumbnail blobKey={coverReference(doc)} alt={doc.title}/><span>{doc.title}</span>{work.cover?.documentId===doc.id&&<Icon name="check"/>}</button>)}</div>{!docs.some(d=>d.coverPageId)&&<p>{msg('暂无可用封面，请先完成内容导入。')}</p>}{error&&<p role="alert">{error}</p>}</Modal>}
  {dialog?.kind==='move'&&document&&<MoveDocumentDialog key={document.id} document={document} units={units} busy={busy} error={error} onClose={closeDialog} onSave={target=>void run(()=>moveDocument(document.id,target),msg('版本归属已更新'),true)}/>}
  {dialog?.kind.startsWith('remove-')&&<Modal title={dialog.kind==='remove-work'?msg('移除作品'):dialog.kind==='remove-selected'?msg('移除所选内容'):msg('移除版本')} onClose={closeDialog}><div className="nc-removal-summary"><strong>{dialog.kind==='remove-work'?work.title:dialog.kind==='remove-selected'?msg('已选择 {0} 项',{'0':chosen.length}):document?.title}</strong><p>{dialog.kind==='remove-work'?msg('{0} 个阅读单元 · {1} 个版本',{'0':units.length,'1':docs.length}):dialog.kind==='remove-selected'?msg('{0} 个版本',{'0':docs.filter(d=>selected.has(d.unitId)).length}):document?.format.toUpperCase()}</p></div><p>{msg('将移除所选书架内容，并释放插件保存的源文件引用和本机阅读资料。其他版本仍使用的源文件会保留。')}</p><p className="nc-muted">{msg('电脑上的外部原文件、云盘文件及服务端翻译结果不受影响。')}</p>{error&&<p role="alert" className="error-message">{error}</p>}<div className="nc-modal-footer"><button className="button secondary" disabled={busy} onClick={closeDialog}>{msg('取消')}</button><button className="button danger" disabled={busy} onClick={()=>void run(async()=>{if(dialog.kind==='remove-work'){await removeWork(work.id);onBack();}else if(dialog.kind==='remove-document'){if(document)await removeDocument(document.id);}else{for(const doc of docs.filter(d=>selected.has(d.unitId)))await removeDocument(doc.id,{expectedUnitId:doc.unitId});setSelected(new Set());setSelecting(false);}},msg('已从书架移除'),true)}>{busy?msg('正在移除…'):msg('确认移除')}</button></div></Modal>}
 </div>;
}

type MetadataValues={title:string;aliases?:string[];creators?:string[];description?:string;kind?:ReadingUnit['kind'];role?:ReadingUnit['role'];language?:string;versionLabel?:string};
function MetadataEditor({kind,work,unit,document,busy,error,onClose,onSave}:{kind:'work'|'unit'|'document';work?:Work;unit?:ReadingUnit;document?:Document;busy:boolean;error:string;onClose:()=>void;onSave:(values:MetadataValues)=>void}){
 const [title,setTitle]=useState(work?.title??unit?.title??document?.title??''),[aliases,setAliases]=useState(work?.aliases?.join('\n')??''),[creators,setCreators]=useState(work?.creators?.join('\n')??''),[description,setDescription]=useState(work?.description??'');
 const [unitKind,setUnitKind]=useState(unit?.kind??'unclassified'),[role,setRole]=useState(unit?.role??'unknown'),[language,setLanguage]=useState(document?.language??''),[versionLabel,setVersionLabel]=useState(document?.versionLabel??'');
 const lines=(text:string)=>text.split('\n').map(s=>s.trim()).filter(Boolean);
 return <Modal title={kind==='work'?msg('编辑作品'):kind==='unit'?msg('编辑条目'):msg('编辑版本')} onClose={onClose} className="nc-metadata-modal"><form onSubmit={e=>{e.preventDefault();onSave(kind==='work'?{title,aliases:lines(aliases),creators:lines(creators),description}:kind==='unit'?{title,kind:unitKind,role}:{title,language,versionLabel});}}><fieldset disabled={busy} className="nc-editor-fields"><label className="field">{kind==='work'?msg('作品名称'):msg('名称')}<input autoFocus required maxLength={300} value={title} onChange={e=>setTitle(e.target.value)}/></label>{kind==='work'?<><div className="nc-form-grid"><label className="field">{msg('作者（每行一位，选填）')}<textarea rows={3} maxLength={2000} value={creators} onChange={e=>setCreators(e.target.value)}/></label><label className="field">{msg('别名（每行一个，选填）')}<textarea rows={3} maxLength={4000} value={aliases} onChange={e=>setAliases(e.target.value)}/></label></div><label className="field">{msg('作品简介（选填）')}<textarea rows={4} maxLength={4000} value={description} onChange={e=>setDescription(e.target.value)}/></label></>:kind==='unit'?<div className="nc-form-grid"><label className="field">{msg('内容类型')}<Select value={unitKind} onChange={e=>setUnitKind(e.target.value as ReadingUnit['kind'])}>{['chapter','volume','book','unclassified'].map(value=><option key={value} value={value}>{unitKindLabel(value)}</option>)}</Select></label><label className="field">{msg('内容性质')}<Select value={role} onChange={e=>setRole(e.target.value as ReadingUnit['role'])}>{['main','extra','unknown'].map(value=><option key={value} value={value}>{roleLabel(value)}</option>)}</Select></label></div>:<div className="nc-form-grid"><label className="field">{msg('版本说明（选填）')}<input maxLength={180} value={versionLabel} onChange={e=>setVersionLabel(e.target.value)} placeholder={msg('例如：彩色版、修订版')}/></label><label className="field">{msg('语言（选填）')}<input maxLength={80} value={language} onChange={e=>setLanguage(e.target.value)}/></label></div>}</fieldset>{error&&<p role="alert" className="error-message">{error}</p>}<div className="nc-modal-footer"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>{msg('取消')}</button><button className="button primary" disabled={busy||!title.trim()}>{busy?msg('保存中…'):msg('保存修改')}</button></div></form></Modal>;
}
function MoveDocumentDialog({document,units,busy,error,onClose,onSave}:{document:Document;units:ReadingUnit[];busy:boolean;error:string;onClose:()=>void;onSave:(id:string)=>void}){
 const [target,setTarget]=useState('');
 return <Modal title={msg('纠正归属')} subtitle={document.title} onClose={onClose}><p className="nc-muted">{msg('将此版本归入本作品的另一个条目，独立阅读位置保留。')}</p><label className="field">{msg('目标条目')}<Select value={target} disabled={busy} onChange={e=>setTarget(e.target.value)}><option value="">{msg('请选择')}</option>{units.filter(u=>u.id!==document.unitId).map(u=><option key={u.id} value={u.id}>{u.title} · {unitKindLabel(u.kind)}</option>)}</Select></label>{units.length<2&&<p>{msg('请先添加另一个阅读条目。')}</p>}{error&&<p role="alert" className="error-message">{error}</p>}<div className="nc-modal-footer"><button className="button secondary" disabled={busy} onClick={onClose}>{msg('取消')}</button><button className="button primary" disabled={busy||!target} onClick={()=>onSave(target)}>{msg('确认调整')}</button></div></Modal>;
}
