import 'fake-indexeddb/auto';
import {describe,expect,it,vi} from 'vitest';
import {catalog,openCatalog} from '../src/comics/repositories';
import {seedComic} from './comic-fixture';
describe('single-source catalog and stale-write protection',()=>{
 it('has a fresh baseline without old management tables',async()=>{const db=await openCatalog();for(const table of ['works','units','documents','bindings','revisions','acquisitionTasks'])expect(db.objectStoreNames.contains(table)).toBe(false);expect([...db.objectStoreNames]).toContain('comics');expect([...db.objectStoreNames]).toContain('entries');});
 it('paginates page metadata and retains stable page identity on index retries',async()=>{
  const {entry,page}=await seedComic();await catalog.putPages(entry.id,entry.contentId,Array.from({length:205},(_,i)=>page(i)),1);expect(await catalog.listPages(entry.contentId)).toHaveLength(100);expect((await catalog.listPages(entry.contentId,{offset:100}))[0].ordinal).toBe(100);await catalog.putPages(entry.id,entry.contentId,[{...page(20),pageId:'incorrect-new-id',width:800}],1);expect(await catalog.get('pageDescriptors',[entry.contentId,page(20).pageId])).toMatchObject({width:800});expect(await catalog.count('pageDescriptors',{index:'contentId',range:entry.contentId})).toBe(205);
 });
 it('updates only one comic entry and broadcasts committed changes',async()=>{const a=await seedComic(),b=await seedComic(),listener=vi.fn(),stop=catalog.subscribe(listener);await catalog.patch('entries',a.entry.id,{error:'source unavailable'});expect(await catalog.get('entries',b.entry.id)).toEqual(b.entry);expect(await catalog.listEntries(a.comic.id)).toHaveLength(1);expect(listener).toHaveBeenCalledWith({table:'entries',ids:[a.entry.id]});stop();});
 it('rejects late page and materialization writes after content changes or deletion',async()=>{
  const {entry,page,comic}=await seedComic();await catalog.putPages(entry.id,entry.contentId,[page(0)],1);const value={id:'materialized:'+entry.id,pageId:page(0).pageId,contentId:entry.contentId,renderProfileId:'original-v1',imageSha256:'a'.repeat(64),width:20,height:30,byteSize:40,mime:'image/png',updatedAt:1};expect(await catalog.putMaterialization(value,1)).toBe(true);await catalog.patch('entries',entry.id,{generation:2});await expect(catalog.putPages(entry.id,entry.contentId,[page(1)],1)).rejects.toThrow('已变化');expect(await catalog.putMaterialization(value,1)).toBe(false);await catalog.deleteComic(comic.id);expect(await catalog.putMaterialization(value,2)).toBe(false);await expect(catalog.put('entries',entry)).rejects.toThrow('已变化');expect(await catalog.listPages(entry.contentId)).toEqual([]);
 });
 it('ignores stale positions, wrong parent identity and changed content',async()=>{const {entry,comic,page}=await seedComic();await catalog.putPages(entry.id,entry.contentId,[page(0)],1);const position={id:entry.id,entryId:entry.id,comicId:comic.id,contentId:entry.contentId,pageId:page(0).pageId,relativeOffset:.6,updatedAt:100};await catalog.savePosition(position);for(const values of [{updatedAt:99},{comicId:'other'},{contentId:'other'},{pageId:'missing'}])await catalog.savePosition({...position,updatedAt:101,relativeOffset:.1,...values});expect(await catalog.get('positions',entry.id)).toEqual(position);});
 it('enforces one comic per source resource atomically',async()=>{const {comic}=await seedComic(),id=crypto.randomUUID();await expect(catalog.commit([{table:'metadata',value:{id}},{table:'comics',value:{...comic,id}}])).rejects.toThrow();expect(await catalog.get('metadata',id)).toBeUndefined();expect(await catalog.get('comics',id)).toBeUndefined();});
 it('removes only the selected comic and its own entries',async()=>{const a=await seedComic(),b=await seedComic();await catalog.deleteComic(a.comic.id);expect(await catalog.get('comics',a.comic.id)).toBeUndefined();expect(await catalog.get('entries',b.entry.id)).toEqual(b.entry);});
 it('does not mark incomplete or failed entries read',async()=>{for(const values of [{discoveryComplete:false,pageCount:1},{discoveryComplete:true,pageCount:0},{discoveryComplete:true,pageCount:1,error:'failed'}]){const {entry}=await seedComic(values);await catalog.markRead(entry.id);expect((await catalog.get('entries',entry.id))?.readAt).toBeUndefined();}});
});
