import 'fake-indexeddb/auto';
import {beforeAll,describe,expect,it,vi} from 'vitest';
import {emptyPage} from '../src/reader/model';
import {emptyLibrary,makeCopy,attachCopy,selectRange,validateLibrary,suggestedKind} from '../src/library/model';
import {commitCopies,deleteCopy,readCopies,readLibrary,putBlob,getBlob,saveCopy,editLibrary,savePosition,readPosition,forkSourceRevision,enforceCacheBudget,removeWorks} from '../src/library/store';
import type {SourceCatalog,SourceEntry} from '../src/library/types';
beforeAll(()=>{const data=new Map<string,string>();vi.stubGlobal('localStorage',{getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>data.set(k,v),removeItem:(k:string)=>data.delete(k)});});
const evidence={status:'user' as const,source:'测试用户确认'};
describe('comic content and publication identity',()=>{
 it('keeps chapters independent from books and preserves editions with the same number',()=>{
  const s=emptyLibrary();const c=makeCopy('第12.5话',[]);const workId=attachCopy(s,c,{title:'作品',kind:'extra',number:'12.5'});const chapter=s.chapters[0];
  for(const title of ['普通版','完全版']){const seriesId=crypto.randomUUID();s.series.push({id:seriesId,title,workIds:[workId],evidence});attachCopy(s,makeCopy('第1卷',[]),{title:'作品',workId,seriesId,kind:'publication',number:'1'});}
  for(const p of s.publications)s.inclusions.push({id:crypto.randomUUID(),publicationId:p.id,target:{kind:'chapter',id:chapter.id},order:0,evidence});
  validateLibrary(s);expect(s.works).toHaveLength(1);expect(s.chapters).toHaveLength(1);expect(chapter).not.toHaveProperty('pages');expect(chapter).toMatchObject({role:'extra',number:'12.5'});expect(s.publications).toHaveLength(2);expect(s.inclusions).toHaveLength(2);
 });
 it('allows a book with unknown chapter contents and a standalone work without a fake first chapter',()=>{const s=emptyLibrary();attachCopy(s,makeCopy('全一册',[]),{title:'短篇',kind:'work'});attachCopy(s,makeCopy('某本CBZ',[]),{title:'未知目录',kind:'publication'});expect(s.chapters).toHaveLength(0);expect(s.inclusions).toHaveLength(0);validateLibrary(s);});
 it('rejects a cyclic omnibus/reprint relation',()=>{const s=emptyLibrary();const id=attachCopy(s,makeCopy('卷1',[]),{title:'作品',kind:'publication'});attachCopy(s,makeCopy('卷2',[]),{title:'作品',kind:'publication',workId:id});const [a,b]=s.publications;s.publicationRelations=[{id:'r1',fromId:a.id,toId:b.id,kind:'collects',evidence},{id:'r2',fromId:b.id,toId:a.id,kind:'reprint',evidence}];expect(()=>validateLibrary(s)).toThrow('循环');});
 it('selects actual endpoints including decimals across display pages',()=>{const values=['第1卷','番外','第12.5话','前篇','第71话'].map((title,n)=>({id:String(n),title}));expect(selectRange(values,'1','3')).toEqual(['1','2','3']);expect(()=>selectRange(values,'x','3')).toThrow();});
 it('retains ambiguous extra titles and separates related works',()=>{const entry={related:false,rawTypes:['話'],title:'番外篇01'} as SourceEntry;expect(suggestedKind(entry)).toBe('chapter');expect(suggestedKind({...entry,related:true})).toBe('unclassified');});
});
describe('new library transactions and resource lifecycle',()=>{
 it('serializes duplicate imports from two tabs without duplicate work or copy records',async()=>{const key=crypto.randomUUID(),a=makeCopy('同一来源',[],'test',key),b=makeCopy('另一个标签页标题',[],'test',key);const results=await Promise.all([commitCopies([a],[{title:'并发作品',kind:'chapter'}]),commitCopies([b],[{title:'并发作品',kind:'chapter'}])]);expect(results.map(r=>r.created).sort()).toEqual([0,1]);expect(results[0].copyIds).toEqual(results[1].copyIds);});
 it('does not merge identical titles from unrelated sources',async()=>{const a=makeCopy('同名',[]),b=makeCopy('同名',[]);await commitCopies([a],[{title:'同名',kind:'chapter'}]);await commitCopies([b],[{title:'同名',kind:'chapter'}]);const s=await readLibrary();expect(s.coverage.find(c=>c.copyId===a.id)?.workId).not.toBe(s.coverage.find(c=>c.copyId===b.id)?.workId);});
 it('restores exact file identities and keeps translation/page anchors',async()=>{const page={...emptyPage('1',100,200),imageSha256:'digest',blobKey:'restore-first'};await putBlob('restore-first',new Blob(['1']));const copy=makeCopy('用户标题',[page],'local','file:restore');await commitCopies([copy],[{title:'作品',kind:'chapter'}]);savePosition(copy.id,1,{pageId:page.id,relativeOffset:.42});await putBlob('restore-again',new Blob(['1']));const incoming=makeCopy('新文件名',[{...page,id:'another-slot',blobKey:'restore-again'}],'local','file:restore');await commitCopies([incoming],[{title:'不要新建',kind:'publication'}]);const result=(await readCopies()).find(c=>c.id===copy.id)!;expect(result).toMatchObject({title:'用户标题',pageId:page.id,relativeOffset:.42});expect(result.pages[0]).toMatchObject({id:page.id,blobKey:'restore-again'});});
 it('preserves shared bytes and never recreates a removed copy from an old reader',async()=>{const page={...emptyPage('共享页',10,10),blobKey:'shared-byte'};await putBlob(page.blobKey,new Blob(['shared']));const a=makeCopy('a',[page]),b=makeCopy('b',[{...page,id:'second-slot'}]);await commitCopies([a,b],[{title:'共享',kind:'chapter'},{title:'共享',kind:'publication'}]);await deleteCopy(a);await saveCopy(a);expect((await readCopies()).some(c=>c.id===a.id)).toBe(false);expect(await getBlob(page.blobKey)).toBeInstanceOf(Blob);await deleteCopy(b);expect(await getBlob(page.blobKey)).toBeUndefined();});
 it('preserves incremental acquisition when a stale reader saves a shorter manifest',async()=>{const a=emptyPage('1',10,10),b=emptyPage('2',10,10),copy=makeCopy('增量',[a]);await commitCopies([copy],[{title:'作品',kind:'chapter'}]);await editLibrary((_s,copies)=>{copies.find(c=>c.id===copy.id)!.pages.push(b);});await saveCopy(copy);expect((await readCopies()).find(c=>c.id===copy.id)!.pages).toHaveLength(2);});
 it('keeps offline copies outside cache eviction',async()=>{await putBlob('offline-byte',new Blob(['important']));const c=makeCopy('离线',[{...emptyPage('1',10,10),blobKey:'offline-byte'}]);await commitCopies([c],[{title:'离线',kind:'work'}]);await enforceCacheBudget(await readCopies(),0);expect(await getBlob('offline-byte')).toBeInstanceOf(Blob);});
 it('creates source revisions without borrowing old exact positions or pages',async()=>{const c={...makeCopy('修订',[emptyPage('old',10,10)]),sourceEntryId:'entry'};await commitCopies([c],[{title:'修订',kind:'chapter'}]);savePosition(c.id,1,{pageId:c.pages[0].id,relativeOffset:.6});const id=await forkSourceRevision(c.id);const next=(await readCopies()).find(c=>c.id===id)!;expect(next.pages).toHaveLength(0);expect(next.manifestRevision).toBe(2);expect(readPosition(id,2)).toBeNull();expect((await readCopies()).find(copy=>copy.id===c.id)!.pages).toHaveLength(1);});
 it('remembers explicit source exclusions across re-discovery',async()=>{const c={...makeCopy('删除的条目',[],'source','excluded-entry'),sourceEntryId:'excluded-entry'};const catalog:SourceCatalog={id:'catalog',sourceId:'test',url:'https://example.test',title:'来源',observedAt:1,complete:true,note:'',groups:[],entries:[{id:'excluded-entry',catalogId:'catalog',remoteId:'remote',url:'https://example.test/1',title:'a',groupIds:[],rawTypes:[],order:0,related:false}],excludedEntryIds:[]};await commitCopies([c],[{title:'排除',kind:'chapter'}],catalog);await deleteCopy(c);expect((await readLibrary()).catalogs.find(x=>x.id==='catalog')!.excludedEntryIds).toContain('excluded-entry');});
});

it('removes selected works and both image kinds while preserving other works and shared bytes',async()=>{
 const page={...emptyPage('bulk',10,10),blobKey:'bulk-work-original',outputBlobs:{job:'bulk-work-result'}};
 await putBlob(page.blobKey,new Blob(['original']));await putBlob(page.outputBlobs.job,new Blob(['translation']));
 const a=makeCopy('selected a',[page]),b=makeCopy('selected b',[{...page,id:'b'}]),keep=makeCopy('keep',[{...page,id:'keep'}]);
 const workIds=[];for(const copy of [a,b,keep]){const result=await commitCopies([copy],[{title:copy.title,kind:'chapter'}]);workIds.push(result.workIds[0]);}
 await removeWorks(workIds.slice(0,2));await saveCopy(a);
 const state=await readLibrary(),copies=await readCopies();
 for(const id of workIds.slice(0,2)){expect(state.works.some(w=>w.id===id)).toBe(false);expect(state.chapters.some(c=>c.workId===id)).toBe(false);expect(state.coverage.some(c=>c.workId===id)).toBe(false);}
 expect(copies.some(c=>c.id===a.id||c.id===b.id)).toBe(false);expect(copies.some(c=>c.id===keep.id)).toBe(true);
 expect(await getBlob(page.blobKey)).toBeInstanceOf(Blob);expect(await getBlob(page.outputBlobs.job)).toBeInstanceOf(Blob);
 await removeWorks([workIds[2]]);expect(await getBlob(page.blobKey)).toBeUndefined();expect(await getBlob(page.outputBlobs.job)).toBeUndefined();
});
