import 'fake-indexeddb/auto';
import {describe,expect,it} from 'vitest';
import {catalog} from '../src/comics/repositories';
import {importCatalog,importManifest,publishWebsiteManifest} from '../src/comics/application/import-service';
import {comicDirectory,continueEntry,readerSequence,removeComic} from '../src/comics/application/library-service';
import {sourceFor,type PageManifest,type SourceCatalogSnapshot} from '../src/sources';
function source():SourceCatalogSnapshot{
 const slug='fixture-'+crypto.randomUUID(),id='mangacopy:'+slug;
 const entries=Array.from({length:4},(_,order)=>{const remoteId=crypto.randomUUID();return {id:id+':'+remoteId,catalogId:id,remoteId,url:'https://mangacopy.com/comic/'+slug+'/chapter/'+remoteId,title:'Content '+order,order,groupIds:order<2?['custom']:['other'],rawTypes:['站点自定义类型'],related:order===3,sequenceId:order<2?'first':'second'};});
 return {id,sourceId:'mangacopy',url:'https://mangacopy.com/comic/'+slug,title:'Source comic',observedAt:1,complete:true,note:'',groups:[{id:'root',title:'自由分类',entryIds:[],complete:true},{id:'custom',parentId:'root',title:'特别企划',entryIds:entries.slice(0,2).map(e=>e.id),complete:true},{id:'other',title:'另一种阅读顺序',entryIds:entries.slice(2).map(e=>e.id),complete:true}],entries};
}
const manifest=(url:string,adapter='mangacopy'):PageManifest=>({id:crypto.randomUUID(),revision:1,title:'Source content',url,adapter,direction:'rtl',discoveryComplete:true,note:'',items:[{id:'slot-1',url:'https://images.example/page.png',width:800,height:1200,order:0}]});
describe('adapter-only imports and read-only navigation',()=>{
 it('rejects generic webpages and forged adapter IDs without creating comics',async()=>{const before=await catalog.count('comics');await expect(importManifest(manifest('https://example.org/page','generic'))).rejects.toThrow('专门适配');await expect(importManifest(manifest('https://www.gunnerkrigg.com/?p=123','generic'))).rejects.toThrow('专门适配');expect(await catalog.count('comics')).toBe(before);expect(sourceFor('https://example.org/page').definition.capabilities.importable).not.toBe(true);});
 it('rejects invalid adapted images and catalog URLs before creating a comic',async()=>{const before=await catalog.count('comics'),input=manifest('https://www.gunnerkrigg.com/?p=345','gunnerkrigg');input.items[0].url='javascript:alert(1)';await expect(importManifest(input)).rejects.toThrow('无效');await expect(importManifest(manifest('https://mangacopy.com/comic/invalid'))).rejects.toThrow('无效');expect(await catalog.count('comics')).toBe(before);});
 it('imports only navigation metadata and exposes custom groups and labels without standard type mapping',async()=>{const snapshot=source(),comic=await importCatalog(snapshot),entries=await catalog.listEntries(comic.id);expect(entries).toHaveLength(3);expect(entries.every(e=>e.indexState==='pending')).toBe(true);expect(await continueEntry(comic.id)).toBeUndefined();const directory=await comicDirectory(comic.id);expect(directory.groups.find(g=>g.id==='custom')).toMatchObject({title:'特别企划',parentId:'root'});expect(directory.entries[0].tags).toEqual(['站点自定义类型']);expect(directory.related).toHaveLength(1);expect(entries[0]).not.toHaveProperty('kind');expect(entries[0]).not.toHaveProperty('role');});
 it('uses explicit defaults and never continues across unrelated reading sequences',async()=>{const snapshot=source();snapshot.defaultEntryId=snapshot.entries[0].id;const comic=await importCatalog(snapshot),first=(await continueEntry(comic.id))!;expect((await readerSequence(first.id)).copies).toHaveLength(2);const third=(await catalog.listEntries(comic.id))[2];expect((await readerSequence(third.id)).copies).toHaveLength(1);});
 it('reuses one entry and one reading position across multiple classification references',async()=>{const snapshot=source();snapshot.entries[0].groupIds.push('other');snapshot.groups[2].entryIds.unshift(snapshot.entries[0].id);const comic=await importCatalog(snapshot),item=await importManifest(manifest(snapshot.entries[0].url));expect(item.comicId).toBe(comic.id);expect(await catalog.listEntries(comic.id)).toHaveLength(3);const entry=(await catalog.get('entries',item.id))!,[page]=await catalog.listPages(entry.contentId);await catalog.savePosition({id:entry.id,entryId:entry.id,comicId:comic.id,contentId:entry.contentId,pageId:page.pageId,relativeOffset:.5,updatedAt:100});const directory=await comicDirectory(comic.id,entry.id);expect(directory.groups.filter(g=>g.entryIds.includes(entry.id))).toHaveLength(2);expect(await continueEntry(comic.id)).toMatchObject({id:entry.id});});
 it('keeps page identities on discovery retry, rejects silent replacement, and explicitly replaces current content',async()=>{const snapshot=source(),input=manifest(snapshot.entries[0].url),result=await importManifest(input),entry=(await catalog.get('entries',result.id))!,old=await catalog.listPages(entry.contentId);await publishWebsiteManifest(entry,{...input,id:'second-discovery'});expect((await catalog.listPages(entry.contentId))[0].pageId).toBe(old[0].pageId);const changed={...input,items:[{...input.items[0],url:'https://images.example/changed.png'}]};await expect(publishWebsiteManifest(entry,changed)).rejects.toThrow('已变化');await publishWebsiteManifest(entry,changed,true);const current=(await catalog.get('entries',entry.id))!;expect(current.contentId).not.toBe(entry.contentId);expect(await catalog.listPages(entry.contentId)).toEqual([]);expect(await catalog.listEntries(result.comicId)).toHaveLength(1);});
 it('can replace changed image bytes at the same URL on explicit reload',async()=>{const input=manifest('https://www.gunnerkrigg.com/?p=999','gunnerkrigg'),result=await importManifest(input),entry=(await catalog.get('entries',result.id))!;await publishWebsiteManifest(entry,input,true);expect((await catalog.get('entries',entry.id))?.contentId).not.toBe(entry.contentId);});
 it('can remove and reimport the same website catalog without reviving old records',async()=>{const snapshot=source(),first=await importCatalog(snapshot);await removeComic(first.id);const second=await importCatalog(snapshot);expect(second.id).not.toBe(first.id);expect(await catalog.get('comics',first.id)).toBeUndefined();expect(await catalog.listEntries(second.id)).toHaveLength(3);});
});
