export interface BillingOffer {id:string;name:string;currency:string;unit_amount:number;interval:'month'|'year';monthly_redraw_pages:number;trial_days:number;trial_redraw_pages:number}
export interface Billing {enabled:boolean;trial_eligible:boolean;checkout_pending:boolean;checkout_price:BillingOffer|null;offers:BillingOffer[];subscription:{price:BillingOffer;status:string;next_billed_at:string|null;cancel_at:string|null;paid_ends_at:string|null;trial_ends_at:string|null}|null}
const labels:Record<string,{plan:string;month:string;year:string;unavailable:string;loading:string;error:string;classic:string;quota:(n:number)=>string;trial:(days:number,pages:number)=>string;renew:(annual:boolean)=>string}>={
  'zh-CN':{plan:'订阅套餐',month:'月',year:'年',unavailable:'订阅暂未开放',loading:'正在读取套餐…',error:'暂时无法读取套餐，请刷新重试。',classic:'常规翻译不限页数',quota:n=>`每月 ${n} 页 AI 重绘，剩余不累积`,trial:(d,p)=>`首次绑卡试用 ${d} 天，含 ${p} 页重绘。`,renew:a=>a?'按年自动续费，重绘额度逐月生效。':'按月自动续费。'},
  'zh-TW':{plan:'訂閱方案',month:'月',year:'年',unavailable:'訂閱尚未開放',loading:'正在讀取方案…',error:'暫時無法讀取方案，請重新整理。',classic:'一般翻譯不限頁數',quota:n=>`每月 ${n} 頁 AI 重繪，餘額不累積`,trial:(d,p)=>`首次綁卡試用 ${d} 天，含 ${p} 頁重繪。`,renew:a=>a?'按年自動續訂，重繪額度逐月生效。':'按月自動續訂。'},
  en:{plan:'Subscription plan',month:'month',year:'year',unavailable:'Subscriptions are not available yet',loading:'Loading plans…',error:'Unable to load plans. Please refresh.',classic:'Unlimited classic translation',quota:n=>`${n} AI redraw pages each month, with no rollover`,trial:(d,p)=>`First card-backed trial: ${d} days and ${p} redraw pages.`,renew:a=>a?'Renews annually. Redraw quotas become available monthly.':'Renews monthly.'},
  ja:{plan:'購読プラン',month:'月',year:'年',unavailable:'購読受付は準備中です',loading:'プランを読み込み中…',error:'プランを取得できません。再読み込みしてください。',classic:'通常翻訳はページ数無制限',quota:n=>`AI 再描画は毎月 ${n} ページ、繰り越しなし`,trial:(d,p)=>`カード登録による初回体験は ${d} 日間、再描画 ${p} ページ。`,renew:a=>a?'毎年自動更新。再描画枠は毎月有効になります。':'毎月自動更新。'},
  ko:{plan:'구독 요금제',month:'월',year:'년',unavailable:'구독 서비스 준비 중',loading:'요금제 불러오는 중…',error:'요금제를 불러올 수 없습니다. 새로고침해 주세요.',classic:'일반 번역 페이지 무제한',quota:n=>`매월 AI 다시 그리기 ${n}페이지, 이월 불가`,trial:(d,p)=>`카드 등록 첫 체험 ${d}일, 다시 그리기 ${p}페이지 포함.`,renew:a=>a?'매년 자동 갱신되며 다시 그리기 한도는 매월 제공됩니다.':'매월 자동 갱신됩니다.'},
};
export const billingCopy=(locale:string)=>labels[locale]??labels.en;
export function amount(offer:BillingOffer,locale:string){const f=new Intl.NumberFormat(locale,{style:'currency',currency:offer.currency});const digits=['isk','ugx'].includes(offer.currency)?2:f.resolvedOptions().maximumFractionDigits??2;return f.format(offer.unit_amount/10**digits);}
export const offerLabel=(offer:BillingOffer,locale:string)=>`${offer.name} · ${amount(offer,locale)} / ${offer.interval==='year'?billingCopy(locale).year:billingCopy(locale).month}`;
