import type { Locale } from '../types';

export const localImportSteps: Record<Locale, string[]> = {
  'zh-CN': ['在插件“我的漫画”中点击“导入漫画”，选择一个受支持的文件。', '导入后直接进入阅读器；左侧“目录”可查看页序或切换章节。', '在“阅读设置”调整布局、方向和缩放。先确认原图正常，需要翻译时再选择渠道与目标语言。'],
  'zh-TW': ['在擴充功能「我的漫畫」點選「匯入漫畫」，選擇支援的檔案。', '匯入後直接進入閱讀器；左側目錄可查看頁序或切換章節。', '在閱讀設定調整版面、方向和縮放。先確認原圖正常，需要翻譯時再選擇管道與目標語言。'],
  en: ['In My comics, choose Import comics and select a supported file.', 'The reader opens after import. Use the directory on the left to inspect page order or switch chapters.', 'Adjust layout, direction and zoom in Reading settings. Check the originals before choosing a translation channel and target language.'],
  ja: ['「マイコミック」で「漫画を読み込む」を選び、対応ファイルを指定します。', '読み込み後にリーダーが開きます。左側の目次でページ順や章を確認できます。', '読書設定でレイアウト、方向、拡大率を調整します。まず原画像を確認し、必要な場合に翻訳サービスと言語を選びます。'],
  ko: ['내 만화에서 만화 가져오기를 선택하고 지원되는 파일을 고르세요.', '가져온 뒤 리더가 열립니다. 왼쪽 목차에서 페이지 순서를 보거나 장을 바꿀 수 있습니다.', '읽기 설정에서 레이아웃, 방향, 배율을 조정하세요. 원본을 먼저 확인한 뒤 필요한 경우 번역 채널과 언어를 선택하세요.'],
  fr: ['Dans Mes mangas, choisissez l’importation et sélectionnez un fichier compatible.', 'Le lecteur s’ouvre après l’importation. Le sommaire à gauche permet de vérifier les pages ou de changer de chapitre.', 'Réglez la disposition, le sens et le zoom. Vérifiez les originaux avant de choisir un canal et une langue de traduction.'],
  es: ['En Mis cómics, elige importar y selecciona un archivo compatible.', 'El lector se abre al importar. El índice de la izquierda permite revisar páginas o cambiar de capítulo.', 'Ajusta el diseño, dirección y zoom. Comprueba los originales antes de elegir un canal e idioma de traducción.'],
  'pt-BR': ['Em Meus quadrinhos, escolha importar e selecione um arquivo compatível.', 'O leitor abre após a importação. Use o índice à esquerda para conferir páginas ou mudar de capítulo.', 'Ajuste layout, direção e zoom. Confira os originais antes de escolher canal e idioma de tradução.'],
  de: ['Wähle in Meine Comics den Import und eine unterstützte Datei aus.', 'Nach dem Import öffnet sich der Reader. Links kannst du die Seitenfolge prüfen oder das Kapitel wechseln.', 'Passe Layout, Leserichtung und Zoom an. Prüfe zuerst die Originale und wähle erst bei Bedarf Übersetzungsdienst und Zielsprache.'],
  it: ['In I miei fumetti, scegli l’importazione e seleziona un file compatibile.', 'Il lettore si apre dopo l’importazione. L’indice a sinistra permette di controllare le pagine o cambiare capitolo.', 'Regola layout, direzione e zoom. Verifica gli originali prima di scegliere canale e lingua di traduzione.'],
  ru: ['В разделе «Мои комиксы» выберите импорт и поддерживаемый файл.', 'После импорта откроется читалка. Слева можно проверить порядок страниц или сменить главу.', 'Настройте вид, направление и масштаб чтения. Проверьте оригиналы, затем при необходимости выберите канал и язык перевода.'],
  pl: ['W Moich komiksach wybierz import i wskaż obsługiwany plik.', 'Po imporcie otworzy się czytnik. Spis po lewej pozwala sprawdzić strony lub zmienić rozdział.', 'Ustaw układ, kierunek i powiększenie. Sprawdź oryginały przed wyborem kanału i języka tłumaczenia.'],
  uk: ['У розділі «Мої комікси» виберіть імпорт і підтримуваний файл.', 'Після імпорту відкриється читач. Зміст ліворуч допоможе перевірити сторінки або змінити розділ.', 'Налаштуйте вигляд, напрямок і масштаб. Перевірте оригінали, а потім за потреби виберіть канал та мову перекладу.'],
  tr: ['Çizgi romanlarım bölümünde içe aktarmayı seçip desteklenen bir dosya açın.', 'İçe aktarma sonrasında okuyucu açılır. Soldaki dizinden sayfa sırasını kontrol edebilir veya bölüm değiştirebilirsiniz.', 'Düzen, yön ve yakınlaştırmayı ayarlayın. Önce özgün sayfaları kontrol edin, sonra gerekirse çeviri kanalı ve dilini seçin.'],
  vi: ['Trong Truyện của tôi, chọn nhập truyện rồi chọn một tệp được hỗ trợ.', 'Trình đọc mở sau khi nhập. Dùng mục lục bên trái để kiểm tra thứ tự trang hoặc chuyển chương.', 'Chỉnh bố cục, hướng và độ phóng đại. Kiểm tra ảnh gốc trước khi chọn kênh và ngôn ngữ dịch.'],
  id: ['Di Komik saya, pilih impor lalu pilih berkas yang didukung.', 'Pembaca terbuka setelah impor. Gunakan daftar isi di kiri untuk memeriksa urutan halaman atau mengganti bab.', 'Atur tata letak, arah, dan pembesaran. Periksa gambar asli sebelum memilih kanal dan bahasa terjemahan.'],
  ar: ['في قسم قصصي المصورة اختر الاستيراد وحدد ملفاً مدعوماً.', 'يفتح القارئ بعد الاستيراد. استخدم الفهرس على اليسار لفحص ترتيب الصفحات أو تغيير الفصل.', 'اضبط التخطيط والاتجاه والتكبير. تحقق من الصور الأصلية أولاً ثم اختر قناة الترجمة ولغتها عند الحاجة.'],
};
