import { defineBackground } from 'wxt/utils/define-background';
import { safeImageUrl, type ChapterManifest } from '../src/sources/adapters';
function trusted(sender: chrome.runtime.MessageSender) {const base=chrome.runtime.getURL('');return sender.id===chrome.runtime.id&&!!sender.url?.startsWith(base);}
async function storeAndOpen(manifest:ChapterManifest){await chrome.storage.local.set({[`manifest:${manifest.id}`]:manifest});await chrome.tabs.create({url:chrome.runtime.getURL(`/reader.html?manifest=${manifest.id}`)});}
export default defineBackground(()=>{
  chrome.runtime.onInstalled.addListener(()=>{chrome.contextMenus.removeAll(()=>chrome.contextMenus.create({id:'nc-read-image',title:'在 Node Comics 中阅读 / 翻译',contexts:['image']}));});
  chrome.contextMenus.onClicked.addListener(async(info,tab)=>{if(info.menuItemId!=='nc-read-image'||!tab?.id||!tab.url)return;const url=safeImageUrl(info.srcUrl??'',tab.url);if(!url)return;await chrome.scripting.executeScript({target:{tabId:tab.id},files:['content-scripts/content.js']});const source=await chrome.tabs.sendMessage(tab.id,{type:'NC_NAVIGATION'});if(source?.url!==tab.url||typeof source.navigationId!=='string')return;const key=crypto.randomUUID();await storeAndOpen({version:1,id:key,sourceTabId:tab.id,navigationId:source.navigationId,revision:1,title:(tab.title??'网页图片').slice(0,160),url:tab.url,adapter:'context-menu',direction:'rtl',discoveryComplete:false,note:'通过图片右键导入的单张图片。',items:[{id:crypto.randomUUID(),url,width:800,height:1200,order:0}]});});
  chrome.runtime.onMessage.addListener((message,sender,respond)=>{if(!trusted(sender))return;
    (async()=>{
      if(message?.type==='NC_DISCOVER_TAB') { const tabId=Number(message.tabId);if(!Number.isInteger(tabId))throw Error('无效标签页');const tab=await chrome.tabs.get(tabId);if(!tab.url||!safeImageUrl(tab.url,tab.url))throw Error('请在普通 HTTP / HTTPS 漫画网页使用插件。');await chrome.scripting.executeScript({target:{tabId},files:['content-scripts/content.js']});const result=await chrome.tabs.sendMessage(tabId,{type:'NC_DISCOVER'});if(!result||result.url!==tab.url||!Array.isArray(result.items))throw Error('来源页面已变化，请重新发现图片。');const id=crypto.randomUUID();const manifest={...result,id,sourceTabId:tabId} as ChapterManifest;manifest.items=manifest.items.slice(0,300).filter(i=>safeImageUrl(i.url,tab.url!)===i.url);await chrome.storage.local.set({[`manifest:${id}`]:manifest});return manifest; }
      if(message?.type==='NC_SOURCE_IMAGE'){ const key=String(message.manifestId);const data=await chrome.storage.local.get(`manifest:${key}`);const manifest=data[`manifest:${key}`] as ChapterManifest|undefined;if(!manifest)throw Error('来源清单已失效，请重新发现图片。');const item=manifest.items.find(i=>i.id===message.pageId);if(!item||!safeImageUrl(item.url,manifest.url))throw Error('图片不在当前来源清单内。');const tab=await chrome.tabs.get(manifest.sourceTabId).catch(()=>null);if(!tab||tab.url!==manifest.url)throw Error('来源标签页已关闭或导航，请重新打开原网页再发现图片。');{const current=await chrome.tabs.sendMessage(manifest.sourceTabId,{type:'NC_NAVIGATION'}).catch(()=>null);if(!current||current.navigationId!==manifest.navigationId||current.url!==manifest.url)throw Error('来源页面已重新加载，请重新发现图片。');}return {url:item.url}; }
      throw Error('不支持的消息');
    })().then(data=>respond({ok:true,data})).catch(error=>respond({ok:false,error:error.message}));return true;
  });
});
