import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Icon} from '../../src/icons';
import type {ChapterManifest} from '../../src/sources/adapters';
import '../../src/styles.css';
function Popup(){const [manifest,setManifest]=useState<ChapterManifest>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [language,setLanguage]=useState('zh-Hans');
async function discover(){setBusy(true);setError('');try{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id||!tab.url)throw Error('请先打开漫画网页。');const origin=new URL(tab.url).origin;if(!origin.startsWith('http'))throw Error('此页面无法读取，请切换到漫画网页。');const granted=await chrome.permissions.request({origins:[origin+'/*']});if(!granted)throw Error('未取得本站访问权限，也可以在阅读器中导入本地图片。');const r=await chrome.runtime.sendMessage({type:'NC_DISCOVER_TAB',tabId:tab.id});if(!r.ok)throw Error(r.error);setManifest(r.data);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
async function open(){await chrome.storage.local.set({pendingLanguage:language});await chrome.tabs.create({url:chrome.runtime.getURL(`/reader.html${manifest?`?manifest=${manifest.id}`:''}`)});window.close();}
return <div className="popup-shell"><div className="brand"><span className="brand-mark"><Icon name="book"/></span><b>Node Comics<span>漫游</span></b><span className="mini-label">BETA</span></div><div className="popup-hero"><span className="eyebrow">YOUR NEXT CHAPTER</span><h1>下一页，<br/>没有语言的距离。</h1><span className="pink-spark">✦</span></div><div className="popup-status"><Icon name="image"/><div><b>{manifest?`发现 ${manifest.items.length} 张图片`:'发现当前网页的故事'}</b><p>{manifest?manifest.note:'只读取你主动授权的网站'}</p></div></div><label className="field">目标语言<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="zh-Hans">简体中文</option><option value="zh-Hant">繁體中文</option><option value="en">English</option><option value="ja">日本語</option></select></label>{error&&<p className="error-message" role="alert">{error}</p>}<button className="button primary full" disabled={busy} onClick={manifest?open:discover}><Icon name={manifest?'book':'spark'}/>{busy?'正在发现…':manifest?'进入阅读器':'发现网页图片'}<Icon name="arrow"/></button><button className="button plain full" onClick={open}>打开书架 / 导入本地图片</button><footer className="popup-footer"><span>让故事跨越语言</span><button onClick={()=>chrome.runtime.openOptionsPage()}>设置 <Icon name="settings" size={14}/></button></footer></div>;}createRoot(document.getElementById('root')!).render(<Popup/>);
