import type { Locale } from '../types';

interface ShowcaseCopy {
  title: [string, string];
  description: string;
  compare: string;
  mono: string;
  color: string;
  original: string;
  translated: string;
  searchTitle: string;
  searchBody: string;
  cta: string;
  translator: string;
}

export const showcaseCopy: Record<Locale, ShowcaseCopy> = {
  'zh-CN': { title: ['不离开网页', '读懂眼前的漫画'], description: '就在当前标签页翻译，继续熟悉的阅读方式。', compare: '同一页漫画，换一种语言。', mono: '黑白漫画', color: '彩色漫画', original: '原图', translated: '译图', searchTitle: '在适配网站中，找到想看的漫画。', searchBody: '搜索漫画名称，查看不同来源。', cta: '开始你的下一页阅读。', translator: '图片翻译' },
  'zh-TW': { title: ['不離開網頁，', '讀懂眼前的漫畫。'], description: '直接在目前分頁翻譯，延續熟悉的閱讀方式。', compare: '同一頁漫畫，換一種語言。', mono: '黑白漫畫', color: '彩色漫畫', original: '原圖', translated: '譯圖', searchTitle: '在支援的網站中，找到想看的漫畫。', searchBody: '搜尋漫畫名稱，查看不同來源。', cta: '開始你的下一頁閱讀。', translator: '圖片翻譯' },
  en: { title: ['Stay on the page.', 'Read beyond the language.'], description: 'Translate in your current tab. Keep reading the way you like.', compare: 'The same page. Another language.', mono: 'Black & white', color: 'Color', original: 'Original', translated: 'Translation', searchTitle: 'Find your next manga on supported sites.', searchBody: 'Search a manga title and explore different sources.', cta: 'Your next page starts here.', translator: 'Image translator' },
  ja: { title: ['ページを離れず、', '目の前の漫画を読もう。'], description: '今のタブで翻訳。いつもの読み方をそのままに。', compare: '同じ漫画のページを、別の言語で。', mono: 'モノクロ', color: 'カラー', original: '原画像', translated: '翻訳画像', searchTitle: '対応サイトで、読みたい漫画を見つけよう。', searchBody: '漫画のタイトルを検索し、さまざまな配信元を確認。', cta: '次のページを、ここから。', translator: '画像翻訳' },
  ko: { title: ['페이지를 떠나지 않고,', '눈앞의 만화를 읽으세요.'], description: '현재 탭에서 번역하고 익숙한 방식으로 계속 읽으세요.', compare: '같은 만화 페이지, 다른 언어.', mono: '흑백 만화', color: '컬러 만화', original: '원본', translated: '번역본', searchTitle: '지원 사이트에서 읽고 싶은 만화를 찾으세요.', searchBody: '만화 제목을 검색하고 여러 출처를 확인하세요.', cta: '다음 페이지를 시작하세요.', translator: '이미지 번역' },
  fr: { title: ['Restez sur la page.', 'Lisez au-delà des langues.'], description: 'Traduisez dans votre onglet actuel et gardez vos habitudes de lecture.', compare: 'La même page, une autre langue.', mono: 'Noir et blanc', color: 'Couleur', original: 'Original', translated: 'Traduction', searchTitle: 'Trouvez votre prochain manga sur les sites compatibles.', searchBody: 'Recherchez un titre et découvrez différentes sources.', cta: 'Votre prochaine page commence ici.', translator: 'Traduction d’images' },
  es: { title: ['Sin salir de la página.', 'Lee más allá del idioma.'], description: 'Traduce en tu pestaña actual y sigue leyendo como te gusta.', compare: 'La misma página, otro idioma.', mono: 'Blanco y negro', color: 'Color', original: 'Original', translated: 'Traducción', searchTitle: 'Encuentra tu próximo manga en sitios compatibles.', searchBody: 'Busca un título y explora diferentes fuentes.', cta: 'Tu próxima página empieza aquí.', translator: 'Traducir imágenes' },
  'pt-BR': { title: ['Sem sair da página.', 'Leia além do idioma.'], description: 'Traduza na aba atual e continue lendo do seu jeito.', compare: 'A mesma página, outro idioma.', mono: 'Preto e branco', color: 'Colorido', original: 'Original', translated: 'Tradução', searchTitle: 'Encontre seu próximo mangá nos sites compatíveis.', searchBody: 'Pesquise um título e explore diferentes fontes.', cta: 'Sua próxima página começa aqui.', translator: 'Traduzir imagens' },
  de: { title: ['Bleib auf der Seite.', 'Lies über Sprachgrenzen hinweg.'], description: 'Übersetze im aktuellen Tab und lies wie gewohnt weiter.', compare: 'Dieselbe Seite. Eine andere Sprache.', mono: 'Schwarz-Weiß', color: 'Farbe', original: 'Original', translated: 'Übersetzung', searchTitle: 'Finde deinen nächsten Manga auf unterstützten Seiten.', searchBody: 'Suche nach einem Titel und entdecke verschiedene Quellen.', cta: 'Deine nächste Seite beginnt hier.', translator: 'Bildübersetzung' },
  it: { title: ['Resta sulla pagina.', 'Leggi oltre la lingua.'], description: 'Traduci nella scheda attuale e continua a leggere come preferisci.', compare: 'La stessa pagina, un’altra lingua.', mono: 'Bianco e nero', color: 'Colore', original: 'Originale', translated: 'Traduzione', searchTitle: 'Trova il tuo prossimo manga sui siti supportati.', searchBody: 'Cerca un titolo ed esplora diverse fonti.', cta: 'La tua prossima pagina inizia qui.', translator: 'Traduci immagini' },
  ru: { title: ['Не покидайте страницу.', 'Читайте без языковых границ.'], description: 'Переводите в текущей вкладке и читайте привычным способом.', compare: 'Та же страница. Другой язык.', mono: 'Чёрно-белая', color: 'Цветная', original: 'Оригинал', translated: 'Перевод', searchTitle: 'Найдите следующую мангу на поддерживаемых сайтах.', searchBody: 'Ищите по названию и сравнивайте источники.', cta: 'Ваша следующая страница — здесь.', translator: 'Перевод изображений' },
  pl: { title: ['Zostań na stronie.', 'Czytaj ponad granicami języków.'], description: 'Tłumacz w bieżącej karcie i czytaj tak, jak lubisz.', compare: 'Ta sama strona. Inny język.', mono: 'Czarno-biała', color: 'Kolorowa', original: 'Oryginał', translated: 'Tłumaczenie', searchTitle: 'Znajdź kolejną mangę w obsługiwanych serwisach.', searchBody: 'Wyszukaj tytuł i sprawdź różne źródła.', cta: 'Twoja następna strona zaczyna się tutaj.', translator: 'Tłumacz obrazów' },
  uk: { title: ['Залишайтеся на сторінці.', 'Читайте без мовних меж.'], description: 'Перекладайте в поточній вкладці й читайте звичним способом.', compare: 'Та сама сторінка. Інша мова.', mono: 'Чорно-біла', color: 'Кольорова', original: 'Оригінал', translated: 'Переклад', searchTitle: 'Знайдіть наступну манґу на підтримуваних сайтах.', searchBody: 'Шукайте за назвою та переглядайте різні джерела.', cta: 'Ваша наступна сторінка починається тут.', translator: 'Переклад зображень' },
  tr: { title: ['Sayfadan ayrılmadan,', 'dil sınırlarını aşarak okuyun.'], description: 'Geçerli sekmede çevirin, alıştığınız şekilde okumaya devam edin.', compare: 'Aynı sayfa, başka bir dil.', mono: 'Siyah beyaz', color: 'Renkli', original: 'Orijinal', translated: 'Çeviri', searchTitle: 'Desteklenen sitelerde okuyacağınız mangayı bulun.', searchBody: 'Bir manga adı arayın, farklı kaynakları keşfedin.', cta: 'Bir sonraki sayfanız burada başlıyor.', translator: 'Görsel çevirisi' },
  vi: { title: ['Không cần rời trang,', 'đọc truyện vượt rào cản ngôn ngữ.'], description: 'Dịch ngay trong thẻ hiện tại và tiếp tục cách đọc quen thuộc.', compare: 'Cùng một trang truyện, một ngôn ngữ khác.', mono: 'Truyện đen trắng', color: 'Truyện màu', original: 'Ảnh gốc', translated: 'Bản dịch', searchTitle: 'Tìm truyện muốn đọc trên các trang được hỗ trợ.', searchBody: 'Tìm theo tên truyện và khám phá nhiều nguồn khác nhau.', cta: 'Bắt đầu trang truyện tiếp theo.', translator: 'Dịch hình ảnh' },
  id: { title: ['Tetap di halaman.', 'Baca melampaui batas bahasa.'], description: 'Terjemahkan di tab saat ini dan lanjutkan membaca dengan cara favoritmu.', compare: 'Halaman yang sama, bahasa berbeda.', mono: 'Hitam putih', color: 'Berwarna', original: 'Asli', translated: 'Terjemahan', searchTitle: 'Temukan manga berikutnya di situs yang didukung.', searchBody: 'Cari judul manga dan jelajahi berbagai sumber.', cta: 'Halaman berikutnya dimulai di sini.', translator: 'Terjemahan gambar' },
  ar: { title: ['ابقَ في الصفحة.', 'واقرأ بلا حواجز لغوية.'], description: 'ترجم في علامة التبويب الحالية وتابع القراءة بطريقتك المعتادة.', compare: 'الصفحة نفسها، بلغة أخرى.', mono: 'أبيض وأسود', color: 'ملوّن', original: 'الأصل', translated: 'الترجمة', searchTitle: 'اعثر على المانغا التالية في المواقع المدعومة.', searchBody: 'ابحث باسم المانغا واستكشف مصادر مختلفة.', cta: 'صفحتك التالية تبدأ هنا.', translator: 'ترجمة الصور' },
};
