import {useEffect, useState} from 'react';
import {billingEndpoint, billingStatus, billingTime as time, environmentName, intervalName, money, providerName, type BillingAccountDetail, type BillingCustomer, type BillingInvoice, type BillingPage, type BillingSubscription, type BillingSubscriptionDetail, type BillingTerm} from './billing';
import {BillingBadge, BillingDialog, useBillingResource} from './BillingShared';
import {Empty, href, Table} from './ui';

type Props = {params: URLSearchParams; onNavigate: (values: Record<string, string>) => void; onUnauthorized: (message: string) => void};
function Pager({data, loading, setPage}: {data?: {total: number; page: number; page_size: number}; loading: boolean; setPage: (page: number) => void}) {
  return data && <div className="pagination"><span>共 {data.total} 条 · 第 {data.page} 页</span><div><button className="secondary" disabled={loading || data.page <= 1} onClick={() => setPage(data.page - 1)}>上一页</button><button className="secondary" disabled={loading || data.page * data.page_size >= data.total} onClick={() => setPage(data.page + 1)}>下一页</button></div></div>;
}

function AccountDetail({ownerId, onClose, onUnauthorized}: {ownerId: string; onClose: () => void; onUnauthorized: Props['onUnauthorized']}) {
  const {data, loading, error} = useBillingResource<BillingAccountDetail>(`${billingEndpoint}/accounts/${encodeURIComponent(ownerId)}`, onUnauthorized);
  return <BillingDialog title="客户试用资格" onClose={onClose}>{error && <p className="error" role="alert">{error}</p>}{!data ? <p>{loading ? '正在读取…' : '资料暂时不可用。'}</p> : <><dl className="detail-meta"><dt>用户</dt><dd>{data.owner_name}<small><code>{data.owner_id}</code></small></dd><dt>跨渠道试用占用</dt><dd>{data.trial_used_at ? `已使用 · ${time(data.trial_used_at)}` : data.trial_reserved.length ? '存在待核实试用结账' : '尚未占用试用资格'}</dd></dl><p className="muted">实际是否可试用仍取决于购买时的产品配置与当前订阅。试用资格在各渠道间共享。</p>{data.trial_reserved.length > 0 && <Table heads={['结账编号', '渠道 / 环境', '状态', '创建 / 到期']}>{data.trial_reserved.map(row => <tr key={row.id}><td><a className="text-link" href={href('orders', {q: row.id})}>{row.id}</a></td><td>{providerName(row.provider)}<small>{environmentName(row.environment)}</small></td><td>{billingStatus(row.status)}</td><td>{time(row.created_at)}<small>{time(row.expires_at)}</small></td></tr>)}</Table>}</>}</BillingDialog>;
}

function SubscriptionDetail({id, onClose, onUnauthorized}: {id: string; onClose: () => void; onUnauthorized: Props['onUnauthorized']}) {
  const [invoicePage, setInvoicePage] = useState(1), [termPage, setTermPage] = useState(1);
  const path = `${billingEndpoint}/subscriptions/${encodeURIComponent(id)}`;
  const detail = useBillingResource<BillingSubscriptionDetail>(path, onUnauthorized);
  const invoices = useBillingResource<BillingPage<BillingInvoice>>(`${path}/invoices?page=${invoicePage}`, onUnauthorized);
  const terms = useBillingResource<BillingPage<BillingTerm>>(`${path}/terms?page=${termPage}`, onUnauthorized);
  const data = detail.data, sub = data?.subscription;
  return <BillingDialog title="订阅权益追溯" className="subscription-dialog" onClose={onClose}><div className="billing-detail-toolbar"><span className="muted">查看当前状态与历史额度</span><button className="secondary" disabled={detail.loading || invoices.loading || terms.loading} onClick={() => {void detail.reload(); void invoices.reload(); void terms.reload();}}>刷新详情</button></div>
    {detail.error && <p className="error" role="alert">{detail.error}</p>}
    {!data || !sub ? <p>{detail.loading ? '正在读取订阅…' : '订阅暂时不可用。'}</p> : <>
      <div className="detail-summary"><div><h3>{data.price.name} · {intervalName(data.price.interval)}</h3><p>{sub.owner_name} · {providerName(sub.provider)} · {environmentName(sub.environment)}</p></div><BillingBadge status={sub.status} subscription/></div>
      <p className="billing-detail-benefits">权益版本 {data.price.version}：每月 {data.price.monthly_redraw_pages} 页重绘，首次试用 {data.price.trial_days} 天 / {data.price.trial_redraw_pages} 页。授权期决定有效权益，渠道订阅状态用于追溯。</p>
      <section className="event-section"><h3 className="detail-heading">订阅周期</h3><dl className="detail-meta"><dt>付款周期</dt><dd>{time(sub.paid_starts_at)} — {time(sub.paid_ends_at)}</dd><dt>下次付款</dt><dd>{time(sub.next_billed_at)}</dd><dt>试用期</dt><dd>{sub.trial_starts_at || sub.trial_ends_at ? `${time(sub.trial_starts_at)} — ${time(sub.trial_ends_at)}` : '无试用期'}</dd><dt>试用占用</dt><dd>{time(data.trial_used_at)}</dd><dt>取消时间</dt><dd>{time(sub.cancel_at)}</dd><dt>最后同步</dt><dd>{time(sub.synced_at)}</dd></dl></section>
      <details className="image-config-advanced"><summary>关联编号与原结账</summary><dl className="detail-meta"><dt>订阅编号</dt><dd><code>{sub.id}</code></dd><dt>客户编号</dt><dd><code>{sub.customer_id}</code></dd><dt>价格 / 绑定</dt><dd><code>{sub.price_id}</code><small><code>{sub.binding_id}</code></small></dd><dt>原结账</dt><dd><a className="text-link" href={href('orders', {q: sub.checkout_id})}>{sub.checkout_id}</a><small>{billingStatus(data.checkout.status)} · {time(data.checkout.created_at)}</small></dd></dl></details>
    </>}
    <section className="event-section"><h3 className="detail-heading">账单与交易凭据</h3>{invoices.error && <p className="error" role="alert">{invoices.error}</p>}
    {!invoices.data ? <p>{invoices.loading ? '正在读取账单…' : '账单暂时不可用。'}</p> : !invoices.data.items.length ? <p className="muted">暂无已处理的账单。</p> : <Table heads={['账单编号', '金额', '本地处理时间']}>{invoices.data.items.map(row => <tr key={row.id}><td><a className="text-link" href={href('orders', {q: row.id.split(':').slice(2).join(':')})}>{row.id}</a></td><td>{money(row.total, row.currency)}</td><td>{time(row.processed_at)}</td></tr>)}</Table>}
    <Pager data={invoices.data} loading={invoices.loading} setPage={setInvoicePage}/></section>
    <section><h3 className="detail-heading">授权期与月度额度桶</h3>{terms.error && <p className="error" role="alert">{terms.error}</p>}
    {!terms.data ? <p>{terms.loading ? '正在读取授权期…' : '授权期暂时不可用。'}</p> : !terms.data.items.length ? <p className="muted">暂无授权期。</p> : terms.data.items.map(term => <section className="panel subscription-term" key={term.id}><h4>{term.kind === 'trial' ? '试用授权' : '付款授权'} · {term.revoked_at ? '已撤销' : '已记录'}</h4><p>{time(term.starts_at)} — {time(term.ends_at)}{term.revoked_at && ` · 撤销于 ${time(term.revoked_at)}`}</p><Table heads={['翻译模式', '周期', '发放', '已使用', '预占', '账面余额']}>{term.quota_periods.map(bucket => <tr key={bucket.id}><td>{bucket.mode === 'redraw' ? '重绘' : '常规'}<details><summary className="muted">额度桶编号</summary><code>{bucket.id}</code></details></td><td>{time(bucket.starts_at)}<small>{time(bucket.ends_at)}</small></td><td>{bucket.granted}</td><td>{bucket.used}</td><td>{bucket.reserved}</td><td>{bucket.granted - bucket.used - bucket.reserved}</td></tr>)}</Table>{!term.quota_periods.length && <p className="muted">此授权期没有额度桶。</p>}<details><summary className="muted">授权与账单编号</summary><dl className="detail-meta"><dt>授权编号</dt><dd><code>{term.id}</code></dd><dt>原账单</dt><dd><code>{term.invoice_id || '—'}</code></dd></dl></details></section>)}
    <Pager data={terms.data} loading={terms.loading} setPage={setTermPage}/><p className="muted">账面余额保留历史消费记录；已撤销或已过期授权的剩余页数不可使用，月度桶不累计。</p></section>
  </BillingDialog>;
}

export function BillingSubscriptionsPage({params, onNavigate, onUnauthorized}: Props) {
  const customersView = params.get('view') === 'customers';
  const query = new URLSearchParams();
  for (const key of ['provider', 'environment', 'owner_id', 'q', 'page', ...customersView ? [] : ['status']]) if (params.get(key)) query.set(key, params.get(key)!);
  const {data, loading, error, reload} = useBillingResource<BillingPage<BillingSubscription | BillingCustomer>>(`${billingEndpoint}/${customersView ? 'customers' : 'subscriptions'}?${query}`, onUnauthorized);
  const [detail, setDetail] = useState<string>(), [account, setAccount] = useState<string>();
  useEffect(() => {document.title = '订阅与权益 · Node Comics 管理后台';}, []);
  return <main id="main" className="admin-surface" tabIndex={-1}>
    <div className="page-heading"><div><p className="eyebrow">SUBSCRIPTIONS & ENTITLEMENTS</p><h1>订阅与权益</h1><p className="muted">关联支付客户、试用资格、历史账单、授权期与每月额度。</p></div><button className="secondary" disabled={loading} onClick={() => void reload()}>刷新记录</button></div>
    <div className="status-tabs" aria-label="订阅管理视图"><button aria-pressed={!customersView} onClick={() => onNavigate({})}>订阅</button><button aria-pressed={customersView} onClick={() => onNavigate({view: 'customers'})}>客户与试用资格</button></div>
    <section className="filters"><form className="filter-form" key={params.toString()} onSubmit={event => {event.preventDefault(); const values = Object.fromEntries([...new FormData(event.currentTarget)].map(([key, value]) => [key, String(value).trim()]).filter(([, value]) => value)); onNavigate({...values, ...(customersView ? {view: 'customers'} : {})});}}>
      <label className="search-label">搜索<input name="q" maxLength={255} defaultValue={params.get('q') || ''} placeholder="订阅 / 客户编号 / 用户"/></label><label>用户编号<input name="owner_id" maxLength={36} defaultValue={params.get('owner_id') || ''}/></label><label>渠道<select name="provider" defaultValue={params.get('provider') || ''}><option value="">全部</option><option value="creem">Creem</option><option value="stripe">Stripe</option></select></label><label>环境<select name="environment" defaultValue={params.get('environment') || ''}><option value="">全部</option><option value="test">测试环境</option><option value="live">正式环境</option></select></label>{!customersView && <label>状态<select name="status" defaultValue={params.get('status') || ''}><option value="">全部</option>{['active', 'trialing', 'scheduled_cancel', 'canceled', 'expired', 'past_due', 'unpaid', 'paused'].map(value => <option key={value} value={value}>{value === 'active' ? '订阅生效中' : billingStatus(value)}</option>)}</select></label>}<div className="filter-actions"><button className="primary">筛选</button><button className="secondary" type="button" onClick={() => onNavigate(customersView ? {view: 'customers'} : {})}>重置</button></div>
    </form></section>
    {error && <p className="error" role="alert">{error}{data && ' 列表可能已过时。'}</p>}
    <section className="panel list-panel" aria-busy={loading}>{!data ? <p>{loading ? '正在读取…' : '记录暂时不可用。'}</p> : !data.items.length ? <Empty>没有符合条件的记录</Empty> : customersView ? <Table heads={['客户 / 用户', '渠道', '试用占用', '创建时间', '操作']}>{(data.items as BillingCustomer[]).map(row => <tr key={row.id}><td><b>{row.owner_name}</b><small><code>{row.customer_id}</code></small></td><td>{providerName(row.provider)}<small>{environmentName(row.environment)}</small></td><td>{row.trial_used_at ? time(row.trial_used_at) : '未记录使用'}</td><td>{time(row.created_at)}</td><td><button className="text-link" onClick={() => setAccount(row.owner_id)}>试用资格</button><small><button className="text-link" onClick={() => onNavigate({owner_id: row.owner_id})}>查看订阅</button></small></td></tr>)}</Table> : <Table heads={['订阅 / 用户', '渠道', '状态', '付款截止 / 下次付款', '最后同步', '操作']}>{(data.items as BillingSubscription[]).map(row => <tr key={row.id}><td><b>{row.owner_name}</b><small><button className="text-link" onClick={() => setDetail(row.id)}>{row.id}</button></small></td><td>{providerName(row.provider)}<small>{environmentName(row.environment)}</small></td><td><BillingBadge status={row.status} subscription/></td><td>{time(row.paid_ends_at)}<small>{time(row.next_billed_at)}</small></td><td>{time(row.synced_at)}</td><td><button className="text-link" onClick={() => setDetail(row.id)}>权益追溯</button><small><button className="text-link" onClick={() => setAccount(row.owner_id)}>试用资格</button></small></td></tr>)}</Table>}
      <Pager data={data} loading={loading} setPage={page => onNavigate({...Object.fromEntries(params), page: String(page)})}/>
    </section>
    {detail && <SubscriptionDetail key={detail} id={detail} onClose={() => setDetail(undefined)} onUnauthorized={onUnauthorized}/>}{account && <AccountDetail key={account} ownerId={account} onClose={() => setAccount(undefined)} onUnauthorized={onUnauthorized}/>}
  </main>;
}
