import {useEffect,useState} from 'react';
import {Api} from '../api';
import type {Job} from '../types';
import {MembershipControls,type AdminUser} from './Memberships';
type Provider={id:string;enabled:boolean;validated_at?:string;credential_configured?:boolean;config?:Record<string,unknown>;[key:string]:unknown};
type AdminJob=Job&{owner_id:string;provider_id?:string;provider_cost_state?:string;provider_usage?:Record<string,unknown>;text_cost_micros?:number;text_calls?:{cost_state:string}[]};
export function AdminPanel({api}:{api:Api}) {
 const [tab,setTab]=useState<'providers'|'jobs'|'users'>('providers');const [providers,setProviders]=useState<Provider[]>([]);const [jobs,setJobs]=useState<AdminJob[]>([]);const [users,setUsers]=useState<AdminUser[]>([]);
 const [draft,setDraft]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [offset,setOffset]=useState(0);const [total,setTotal]=useState(0);
 const [resolution,setResolution]=useState<{job:AdminJob;note:string}|null>(null);
 async function reload(){setError('');try{if(tab==='providers'){const r=await api.request<{items:Provider[]}>('/v1/admin/providers');setProviders(r.items);}if(tab==='jobs'){const r=await api.request<{items:AdminJob[];total:number}>(`/v1/admin/jobs?offset=${offset}&limit=20`);setJobs(r.items);setTotal(r.total);}if(tab==='users'){const r=await api.request<{items:AdminUser[];total:number}>(`/v1/admin/users?offset=${offset}&limit=20`);setUsers(r.items);setTotal(r.total);}}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void reload();},[api,tab,offset]);
 async function action(fn:()=>Promise<unknown>,message:string){setBusy(true);setError('');try{await fn();setMessage(message);await reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function edit(p:Provider){const config=p.config??Object.fromEntries(Object.entries(p).filter(([key])=>!['validated_at','validation_job_id','credential_configured','credential_available'].includes(key)));setDraft(JSON.stringify(config,null,2));}
 return <section className="admin-panel"><div className="page-title"><span className="eyebrow">OPERATIONS</span><h1>让每一页，安心送达。</h1><p>供应商配置、任务核实和会员权益。此区域仅管理员可访问。</p></div><div className="segmented">{(['providers','jobs','users'] as const).map(v=><button key={v} className={tab===v?'active':''} onClick={()=>{setTab(v);setOffset(0);}}>{{providers:'图片供应商',jobs:'任务与消耗',users:'用户与额度'}[v]}</button>)}<button onClick={()=>void reload()}>刷新</button></div>{error&&<p className="inline-error" role="alert">{error}</p>}{message&&<p className="privacy-note" role="status">{message}</p>}
 {tab==='providers'&&<><section className="settings-card"><h3>已配置的图片服务</h3>{providers.map(p=><div className="setting-row" key={p.id}><div><b>{String(p.label??p.id)}</b><p>{String(p.model??p.config?.model??'')} · {p.enabled?'已启用':'已停用'} · {p.validated_at?'已有验证记录':'尚无图片编辑验证记录'}</p></div><button className="button secondary small" onClick={()=>edit(p)}>编辑</button><button disabled={busy} className="button secondary small" onClick={()=>void action(()=>api.request(`/v1/admin/providers/${p.id}`,{method:'PATCH',body:JSON.stringify({enabled:!p.enabled})}),'供应商状态已更新')}>{p.enabled?'停用':'启用'}</button></div>)}<button className="text-link" onClick={()=>setDraft(JSON.stringify({id:'new-provider',label:'图片编辑服务',base_url:'https://api.openai.com/v1',credential_ref:'SECOND_IMAGE_API_KEY',model:'gpt-image-2',image_field:'image',parameters:{},enabled:true},null,2))}>添加兼容供应商</button></section><section className="settings-card"><h3>供应商配置</h3><p className="small-muted">credential_ref 只填后端环境变量名，不在此填写 API Key。保存配置不会调用模型。</p><textarea aria-label="供应商 JSON 配置" spellCheck={false} style={{width:'100%',minHeight:300,margin:'18px 0',padding:16,border:'1px solid #e7eaf0',borderRadius:12,fontFamily:'monospace'}} value={draft} onChange={e=>setDraft(e.target.value)}/><button disabled={busy||!draft} className="button primary" onClick={()=>void action(async()=>{const body=JSON.parse(draft);if(!/^[a-zA-Z0-9_-]{1,80}$/.test(body.id))throw Error('供应商编号格式无效');if(Object.keys(body).some(k=>/api.?key|secret|token/i.test(k)))throw Error('请使用credential_ref引用后端密钥，不填写真实凭据');await api.request(`/v1/admin/providers/${body.id}`,{method:'PUT',body:JSON.stringify(body)});},'供应商配置已保存')}>保存配置</button></section></>}
 {tab==='users'&&<MembershipControls api={api} users={users} onChanged={reload}/>}
 {tab==='jobs'&&<section className="settings-card"><h3>最近任务 · {total}</h3>{jobs.map(j=><div className="setting-row" key={j.id}><div><b>{j.status} · {j.target_language} · {j.quota_pages} 页额度</b><p>{j.id} · {j.provider_id??'未调用'}</p><p>{j.mode==='classic'?`文本调用 ${j.text_calls?.length??0} 次 · 估算与预占 ${((j.text_cost_micros??0)/1e6).toFixed(5)} 元（其中未知 ${j.text_calls?.filter(c=>c.cost_state==='unknown').length??0} 次）`:`供应商成本：${j.provider_cost_state??'未知'}`} {j.provider_usage?JSON.stringify(j.provider_usage):''}</p>{j.error&&<p className="inline-error">{j.error.message}</p>}</div>{j.status==='outcome_unknown'&&<button className="button secondary small" onClick={()=>setResolution({job:j,note:''})}>核实未交付</button>}</div>)}</section>}
 {tab!=='providers'&&<div className="section-actions"><button disabled={offset===0} className="button secondary small" onClick={()=>setOffset(v=>Math.max(0,v-20))}>上一页</button><span>{Math.floor(offset/20)+1} / {Math.max(1,Math.ceil(total/20))}</span><button disabled={offset+20>=total} className="button secondary small" onClick={()=>setOffset(v=>v+20)}>下一页</button></div>}
 {resolution&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-label="核实未交付"><h2>确认此任务未能交付</h2><p>先核对供应商记录。此操作释放剩余预占，不再次调用模型；供应商成本仍保留原记录。</p><input aria-label="核实依据" placeholder="填写核实依据" maxLength={200} value={resolution.note} onChange={e=>setResolution({...resolution,note:e.target.value})}/><div className="modal-actions"><button className="button secondary" onClick={()=>setResolution(null)}>返回</button><button className="button primary" disabled={busy||!resolution.note.trim()} onClick={()=>void action(async()=>{await api.request(`/v1/admin/jobs/${resolution.job.id}/reconcile`,{method:'POST',body:JSON.stringify({resolution:'failed',note:resolution.note})});setResolution(null);},'已记录核实结果并释放预占')}>确认未交付</button></div></div></div>}
 </section>;
}
