// Dedicated Vite 5181 fixture; no account, supplier, or external image requests.
import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');
const out=path.resolve('artifacts/reader-directory');await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.TEST_CHROMIUM});
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[];
page.on('pageerror',error=>errors.push(error.message));
await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
const list=page.locator('.nc-chapter-list');
const current=page.locator('.nc-chapter-entry[aria-current="true"]');
const centered=()=>page.waitForFunction(()=>{
 const list=document.querySelector('.nc-chapter-list'),row=list?.querySelector('[aria-current="true"]');if(!row)return false;
 const a=list.getBoundingClientRect(),b=row.getBoundingClientRect();return b.height>0&&b.top>=a.top&&b.bottom<=a.bottom&&Math.abs((a.top+a.bottom-b.top-b.bottom)/2)<3;
});
const position=()=>page.locator('.nc-reading-viewport').evaluate(el=>el.scrollTop);
const closePanel=()=>page.getByRole('button',{name:'关闭面板',exact:true}).click();
const openPanel=()=>page.getByRole('button',{name:'打开目录',exact:true}).click();
try{
 await page.goto('http://127.0.0.1:5181/tests/reader-directory-fixture.html');
 await page.getByLabel('跳转页码').fill('80');await openPanel();await centered();
 assert.match(await current.innerText(),/第 250 章/);assert.equal(await page.locator('.nc-chapter-entry').count(),400);
 const before=await position();await page.screenshot({path:path.join(out,'long-directory.png')});
 checks.push('Opening includes and centers chapter 250 beyond the first 200 entries');
 await list.evaluate(el=>el.scrollTop=0);await page.getByRole('button',{name:'刷新目录状态',exact:true}).click();
 await page.getByText('状态已刷新',{exact:false}).first().waitFor();assert.equal(await list.evaluate(el=>el.scrollTop),0);
 checks.push('Status refresh preserves manual directory scrolling');
 await closePanel();await openPanel();await centered();assert.equal(await position(),before);
 await page.getByRole('button',{name:'正序 ↑',exact:true}).click();await centered();assert.equal(await position(),before);
 await page.getByRole('button',{name:'显示更多',exact:true}).click();assert.equal(await page.locator('.nc-chapter-entry').count(),600);
 checks.push('Reopening and reversing locate the same chapter without moving the reading viewport; load more still advances');
 await page.getByLabel('搜索目录').fill('不存在');await page.getByText('没有匹配的内容',{exact:true}).waitFor();
 await page.getByLabel('搜索目录').fill('');await centered();
 await page.getByRole('button',{name:'切换分组',exact:true}).click();await centered();
 assert.equal(await current.evaluate(el=>{let closed=0;for(let node=el.parentElement;node;node=node.parentElement)if(node.tagName==='DETAILS'&&!node.open)closed++;return closed;}),0);
 await page.screenshot({path:path.join(out,'nested-directory.png')});
 checks.push('Search reset locates the chapter and nested source groups open automatically');
 await page.getByLabel('验收章节').fill('450');await centered();assert.match(await current.innerText(),/第 450 章/);
 checks.push('Changing the active chapter while the directory stays open follows its new group');
 await closePanel();await page.getByLabel('跳转页码').fill('90');const reading=await position();
 await openPanel();await page.getByRole('tab',{name:'页面',exact:false}).click();
 const thumb=page.locator('.nc-thumb-main[aria-current="page"]');await thumb.waitFor();
 assert.match(await thumb.innerText(),/第 90 页/);
 assert(await thumb.evaluate(el=>{const a=el.closest('.nc-thumb-list').getBoundingClientRect(),b=el.getBoundingClientRect();return b.top>=a.top&&b.bottom<=a.bottom;}));
 assert.equal(await position(),reading);await page.screenshot({path:path.join(out,'current-page.png')});
 checks.push('The virtual thumbnail list reveals page 90 without changing the reading position');
 await closePanel();await page.getByLabel('跳转页码').fill('8');
 await page.locator('[data-copy-id="chapter-450"] [data-page-index="7"] .nc-image-failure').waitFor();
 await openPanel();await centered();checks.push('Image failure does not block current chapter location');
 await closePanel();await page.getByLabel('跳转页码').fill('90');
 await page.getByRole('button',{name:'关闭阅读器',exact:true}).click();await page.getByRole('button',{name:'重开阅读器',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('[aria-label="跳转页码"]')?.value==='90');
 await openPanel();await centered();checks.push('Closing and reopening restores page 90 and locates its chapter');
 await closePanel();await page.getByRole('button',{name:'切换页面就绪',exact:true}).click();await openPanel();await centered();
 checks.push('Current chapter still locates when its page list is not ready');
 assert.deepEqual(errors,[]);await writeFile(path.join(out,'results.json'),JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({out,checks,errors}));
}catch(error){await page.screenshot({path:path.join(out,'failure.png')});throw error;}finally{await browser.close();}
