// Vite :5181. Real reader/settings components with deterministic local tracker mocks; no OAuth or remote writes.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir, writeFile} from 'node:fs/promises';
import path from 'node:path';
const {chromium} = createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE || 'playwright');
const origin = 'http://127.0.0.1:5181', out = path.resolve('artifacts/tracking-ui');
await mkdir(out, {recursive: true});
const browser = await chromium.launch({headless: true, executablePath: process.env.TEST_CHROMIUM});
const page = await browser.newPage({viewport: {width: 1440, height: 1000}}), errors = [], checks = [];
page.on('pageerror', error => errors.push(error.message));
await page.route('**/*', route => new URL(route.request().url()).origin === origin ? route.continue() : route.abort());
const snapshot = () => page.evaluate(() => window.trackingUiFixture.snapshot());
const panel = page.locator('.nc-tracking-comic');
const button = name => panel.getByRole('button', {name, exact: true});
const save = () => button('保存选择');
const position = () => page.locator('.nc-reading-viewport').evaluate(element => element.scrollTop);
const readStatus = text => panel.locator('.nc-tracking-status').filter({hasText: text}).waitFor();
const openPanel = () => page.getByRole('button', {name: '阅读设置', exact: true}).click();
const closePanel = () => page.getByRole('button', {name: '关闭面板', exact: true}).click();
try {
  await page.goto(origin + '/tests/tracking-ui-fixture.html');
  const connect = page.getByRole('button', {name: '连接 AniList', exact: true});
  await connect.waitFor();
  await page.evaluate(() => window.trackingUiFixture.configure(false));
  await page.getByText('此构建尚未配置 AniList 授权。', {exact: true}).waitFor();
  assert(await connect.isDisabled());
  assert.equal(await page.locator('.nc-tracking code').textContent(), 'https://fixture.chromiumapp.org/anilist');
  await page.screenshot({path: path.join(out, 'unconfigured.png')});
  checks.push('Missing build configuration explains registration and disables connection without a token field');

  await page.evaluate(() => window.trackingUiFixture.configure(true));
  await page.locator('.nc-tracking summary').click();
  assert.equal(await page.locator('.nc-tracking code').textContent(), 'https://fixture.chromiumapp.org/anilist');
  await page.evaluate(() => { window.trackingUiFixture.holdStatus(); window.trackingUiFixture.failNext('authorization'); });
  await connect.click();
  const authorizationError = page.getByRole('alert').filter({hasText: 'AniList 授权未完成。请检查网络，以及 AniList 应用的 Client ID 和回调地址。'});
  await authorizationError.waitFor();
  assert(await connect.isEnabled());
  await page.evaluate(() => { window.trackingUiFixture.releaseStatus(); window.dispatchEvent(new Event('focus')); });
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  assert(await authorizationError.isVisible(), 'Passive status/focus refresh erased the connection failure');
  await page.screenshot({path: path.join(out, 'connection-error.png')});
  checks.push('A failed connection remains explained after delayed status and focus refreshes; the configured callback remains inspectable');
  await connect.click();
  await page.getByText('Local fixture reader 已连接', {exact: true}).waitFor();
  assert.equal(await page.getByRole('alert').count(), 0);
  const enabled = page.getByRole('switch', {name: '自动同步已读章节', exact: true});
  assert.equal(await enabled.getAttribute('aria-checked'), 'false');
  await page.getByText('开启后，已关联作品的完成章节会创建或更新 AniList 阅读中条目；记录是否公开由 AniList 设置决定。', {exact: true}).waitFor();
  await enabled.click();
  await page.waitForFunction(() => document.querySelector('[aria-label="自动同步已读章节"]')?.getAttribute('aria-checked') === 'true');
  await page.screenshot({path: path.join(out, 'connected-settings.png')});
  checks.push('Connecting does not enable automatic writes; the separate opt-in discloses CURRENT creation and visibility');

  await page.evaluate(() => window.trackingUiFixture.holdConnect());
  await page.getByRole('button', {name: '重新连接', exact: true}).click();
  await page.getByRole('button', {name: '正在连接…', exact: true}).waitFor();
  assert.equal(await enabled.getAttribute('aria-checked'), 'true');
  assert(!(await enabled.isDisabled()));
  await enabled.click();
  await page.waitForFunction(() => document.querySelector('[aria-label="自动同步已读章节"]')?.getAttribute('aria-checked') === 'false');
  const disconnect = page.getByRole('button', {name: '断开连接', exact: true});
  assert(!(await disconnect.isDisabled()));
  await disconnect.click();
  await page.waitForFunction(() => !window.trackingUiFixture.snapshot().state.account);
  await page.evaluate(() => window.trackingUiFixture.releaseConnect());
  await connect.waitFor();
  assert.equal((await snapshot()).state.account, undefined);
  assert.equal(await page.getByRole('alert').count(), 0);
  await connect.click(); await enabled.click();
  await page.waitForFunction(() => document.querySelector('[aria-label="自动同步已读章节"]')?.getAttribute('aria-checked') === 'true');
  checks.push('Explicit disable and disconnect remain available during authorization; a cancelled late result does not reconnect or overwrite the UI');

  await page.getByTestId('reader').click();
  await page.getByLabel('跳转页码').fill('6');
  await page.waitForFunction(() => document.querySelector('.nc-reading-viewport')?.scrollTop > 100);
  const before = await position();
  await openPanel();
  await button('关联 AniList 作品').click();
  assert.equal(await panel.getByLabel('AniList 漫画链接、ID 或名称').inputValue(), '123');
  assert(await save().isDisabled());
  await panel.getByLabel('AniList 漫画链接、ID 或名称').fill('Paper Stars');
  await button('搜索').click();
  await panel.getByRole('radio', {name: /Paper Stars · original manga/}).check();
  assert(await save().isDisabled());
  await panel.getByLabel('章节偏移量', {exact: true}).fill('-2');
  await panel.getByRole('checkbox').check();
  await page.evaluate(() => window.trackingUiFixture.failNext());
  await save().click();
  await panel.getByRole('alert').filter({hasText: 'AniList 暂时不可用或请求受限，请稍后重试。'}).waitFor();
  assert.equal((await snapshot()).state.binding, undefined);
  await save().click();
  await readStatus('等待读完下一章');
  assert.deepEqual((await snapshot()).state.binding, {mediaId: 123, title: 'Paper Stars · original manga', offset: -2, paused: false});
  assert.equal((await snapshot()).calls.filter(call => call.command === 'binding').length, 1);
  await panel.scrollIntoViewIfNeeded();
  await page.screenshot({path: path.join(out, 'reader-linked.png')});
  await closePanel();
  assert(Math.abs(await position() - before) < 1, 'Tracking editor moved the reading position');
  assert.equal(await page.getByLabel('跳转页码').inputValue(), '6');
  checks.push('Candidate selection plus integer-offset confirmation is required; failed save remains retryable and preserves page six');

  await openPanel();
  await button('暂停').click(); await readStatus('已暂停');
  await button('恢复追踪').click(); await readStatus('等待读完下一章');
  for (const [status, text] of [['pending', '待同步'], ['syncing', '同步中'], ['synced', '已同步']]) {
    await page.evaluate(status => window.trackingUiFixture.complete(status), status); await readStatus(text);
  }
  await page.evaluate(() => window.trackingUiFixture.complete('blocked', 'chapter-mapping'));
  await readStatus('需要处理');
  await panel.getByText('章节无法可靠换算。小数章、番外、整卷和重置编号不会自动取整同步。', {exact: true}).waitFor();
  await button('重试').click(); await readStatus('已同步');
  checks.push('Pause/resume, pending/sending/confirmed notifications, special-chapter attention and retry render without polling');

  await page.evaluate(() => window.trackingUiFixture.complete('blocked', 'remote-reset'));
  await button('接受远端进度，丢弃待同步记录').click();
  assert.equal((await snapshot()).calls.filter(call => call.command === 'reset-baseline').length, 0);
  await panel.locator('.nc-tracking-confirm').getByRole('button', {name: '取消', exact: true}).click();
  await button('接受远端进度，丢弃待同步记录').click();
  await panel.locator('.nc-tracking-confirm').getByRole('button', {name: '接受远端进度，丢弃待同步记录', exact: true}).click();
  await readStatus('等待读完下一章');
  assert.equal((await snapshot()).calls.filter(call => call.command === 'reset-baseline').length, 1);
  await button('解除关联').click();
  assert((await snapshot()).state.binding);
  await panel.locator('.nc-tracking-confirm').getByRole('button', {name: '解除关联', exact: true}).click();
  await readStatus('未关联 AniList');
  checks.push('Remote-reset acceptance and unlink require a second explicit action; cancel does not discard records');

  await button('关联 AniList 作品').click();
  await panel.getByLabel('AniList 漫画链接、ID 或名称').fill('https://anilist.co/manga/123/Paper-Stars/');
  await button('搜索').click();
  await panel.getByRole('radio').check();
  assert((await snapshot()).calls.some(call => call.command === 'search:123'));
  await panel.getByRole('checkbox').check();
  await panel.getByLabel('章节偏移量', {exact: true}).fill('1.5');
  assert(await save().isDisabled());
  await panel.getByLabel('章节偏移量', {exact: true}).fill('1');
  assert(await save().isDisabled());
  await panel.getByRole('checkbox').check(); await save().click(); await readStatus('等待读完下一章');
  checks.push('AniList URLs use exact media identity; decimal offsets are rejected and changing the offset clears confirmation');

  await button('修改关联').click();
  await page.evaluate(() => window.trackingUiFixture.holdSearch());
  await panel.getByLabel('AniList 漫画链接、ID 或名称').fill('Paper Stars');
  await button('搜索').click();
  await page.evaluate(() => window.trackingUiFixture.switchAccount());
  await readStatus('未关联 AniList');
  await page.evaluate(() => window.trackingUiFixture.releaseSearch());
  assert.equal(await panel.getByRole('radio').count(), 0);
  assert.equal(await panel.locator('.nc-tracking-editor').count(), 0);
  checks.push('Switching accounts invalidates an open editor and ignores a late search response');

  await page.getByTestId('locale').click();
  await panel.getByRole('heading', {name: 'Reading tracking', exact: true}).waitFor();
  await page.getByTestId('theme').click();
  await page.setViewportSize({width: 760, height: 900});
  await panel.scrollIntoViewIfNeeded();
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({path: path.join(out, 'reader-dark-english.png')});
  await page.getByRole('button', {name: 'Close panel', exact: true}).click();
  assert.equal(await page.getByLabel('Jump to page').inputValue(), '6');
  checks.push('Language/theme changes render in place without horizontal overflow or resetting the active page');

  await page.getByTestId('settings').click();
  await page.getByRole('button', {name: 'Disconnect', exact: true}).click();
  await page.getByRole('button', {name: 'Connect AniList', exact: true}).waitFor();
  assert.equal((await snapshot()).state.account, undefined);
  assert.equal((await snapshot()).state.enabled, false);
  checks.push('Disconnect clears the presented account and disables automatic tracking');
  assert.deepEqual(errors, []);
  await writeFile(path.join(out, 'results.json'), JSON.stringify({scope: 'mock tracker API; real browser UI', checks, errors}, null, 2));
  console.log(JSON.stringify({out, checks, errors}, null, 2));
} catch (error) {
  await page.screenshot({path: path.join(out, 'failure.png')});
  throw error;
} finally { await browser.close(); }
