import {useCallback,useEffect,useMemo,useRef,useState, type ReactNode} from 'react';
import {Icon} from './icons';
import {Api,submissionRejected} from './api';
import {defaults,modeLabels,statusLabels,type Capabilities,type Chapter,type Job,type Mode,type Page,type Quote,type Settings,type Usage,type User} from './types';
import * as store from './reader/store';
import {automaticScope,emptyPage,id,makeChapter,naturalSort} from './reader/model';
import {Reader} from './reader/Reader';
import {ServerJobs} from './reader/ServerJobs';
import type {ChapterManifest} from './sources/adapters';
import {importMobi} from './importers/mobi';
import {AdminPanel} from './admin/AdminPanel';
import {finishOidc,startOidc,isOidcCallback,type AuthConfig} from './auth/oidc';
type View='library'|'history'|'settings'|'account'|'admin';
type Intent={mode:Mode;pages:Page[];regenerate?:boolean};
type ReadyQuote={quote:Quote;intent:Intent;key:string;chapterId:string;ownerId:string;apiOrigin:string;targetLanguage:string};
const terminal=new Set(['succeeded','failed','cancelled','no_text']);
export function App(){
const [chapters,setChapters]=useState<Chapter[]>([]);const chaptersRef=useRef(chapters);chaptersRef.current=chapters;
const [currentId,setCurrentId]=useState<string>();const current=chapters.find(c=>c.id===currentId);
const [view,setView]=useState<View>((location.hash.slice(1) as View)||'library');
const [settings,setSettings]=useState<Settings>(store.settings);const [account,setAccount]=useState(store.session);const accountRef=useRef(account);accountRef.current=account;
const [apiDraft,setApiDraft]=useState(settings.apiBase);
const apiOrigin=useMemo(()=>{try{return new URL(settings.apiBase).origin;}catch{return '';}},[settings.apiBase]);
const api=useMemo(()=>new Api(settings.apiBase,account?.apiOrigin===apiOrigin?account.token:''),[settings.apiBase,account,apiOrigin]);
const [caps,setCaps]=useState<Capabilities>();const [usage,setUsage]=useState<Usage>();const [online,setOnline]=useState<'connecting'|'online'|'offline'>('connecting');
const [busy,setBusy]=useState('');const [toast,setToast]=useState('');const [error,setError]=useState('');const [drag,setDrag]=useState(false);
const [loginOpen,setLoginOpen]=useState(false);const [username,setUsername]=useState('reader');const [authAllowed,setAuthAllowed]=useState(false);const [pendingIntent,setPendingIntent]=useState<Intent>();
const [authConfig,setAuthConfig]=useState<AuthConfig>();
const [ready,setReady]=useState<ReadyQuote>();const [confirmAction,setConfirmAction]=useState<{title:string;body:string;action:()=>Promise<void>}>();
const pendingKey=account?`nc-submission:${apiOrigin}:${account.user.id}`:'';
const [cacheBytes,setCacheBytes]=useState(0);const [autoApproval,setAutoApproval]=useState(false);const autoLock=useRef(false);const autoCount=useRef(0);const autoBudget=useRef(0);const currentRef=useRef(currentId);currentRef.current=currentId;
const autoScope=automaticScope(currentId,account?.user.id,apiOrigin,settings.language,settings.translationMode,settings.autoLimit);
const approvedAutoScope=useRef('');const autoScopeRef=useRef(autoScope);autoScopeRef.current=autoScope;
useEffect(()=>{setAutoApproval(false);},[autoScope]);
const autoState=useRef({enabled:autoApproval,chapterId:currentId});autoState.current={enabled:autoApproval&&approvedAutoScope.current===autoScope,chapterId:currentId};
const autoVisited=useRef(new Set<string>());
const input=useRef<HTMLInputElement>(null);const [sourceManifest,setSourceManifest]=useState<ChapterManifest>();
const notify=useCallback((message:string)=>setToast(message),[]);
async function saveApiAddress(){
  try{
    const url=new URL(apiDraft);const local=['127.0.0.1','localhost','[::1]'].includes(url.hostname);
    if((url.protocol!=='https:'&&!(local&&url.protocol==='http:'))||url.username||url.password||url.search||url.hash)throw Error('服务地址须为 HTTPS，或本机 HTTP 地址，不可包含凭据与查询参数。');
    if(typeof chrome!=='undefined'&&chrome.permissions){const granted=await chrome.permissions.request({origins:[url.origin+'/*']});if(!granted)throw Error('尚未取得新服务域名的访问权限。');}
    const base=url.href.replace(/\/+$/,'');
    if(url.origin!==apiOrigin){store.saveSession(null);setAccount(null);setUsage(undefined);setCaps(undefined);setReady(undefined);setPendingIntent(undefined);setAutoApproval(false);}
    setSettings(s=>({...s,apiBase:base}));setApiDraft(base);notify('服务地址已保存；切换服务后需重新登录');
  }catch(e){setError((e as Error).message);}
}
async function importMobiFile(file:File){
  setBusy('正在解析 MOBI 漫画…');setError('');
  try{
    const imported=await importMobi(file,(done,total)=>setBusy(`正在发现漫画页 ${done} / ${total}…`));
    const pages:Page[]=[];
    for(const item of imported.pages){
      let blob=item.blob;let width=item.width;let height=item.height;
      if(!width||!height||blob.type==='image/gif'){
        const bitmap=await createImageBitmap(blob);width=bitmap.width;height=bitmap.height;
        if(blob.type==='image/gif'){
          const canvas=new OffscreenCanvas(width,height);canvas.getContext('2d')!.drawImage(bitmap,0,0);
          blob=await canvas.convertToBlob({type:'image/png'});
        }
        bitmap.close();
      }
      const page=emptyPage(item.name.replace(/\.gif$/i,'.png'),width,height);page.blobKey=`original:${page.id}`;
      await store.putBlob(page.blobKey,blob);pages.push(page);
      if(pages.length%10===0)setBusy(`正在保存本地漫画 ${pages.length} / ${imported.pages.length} 页…`);
    }
    const chapter=makeChapter(imported.title,pages,'MOBI 本地导入');updateChapter(chapter);setCurrentId(chapter.id);setView('library');
    notify(`已导入 ${pages.length} 页 · ${imported.warnings[0]??'原图保存在本机，滚动时按需解码'}`);
    await store.enforceCacheBudget(chaptersRef.current,settings.cacheLimitMb,chapter.id);setCacheBytes(await store.cacheSize());
  }catch(e){setError((e as Error).message);}finally{setBusy('');if(input.current)input.current.value='';}
}
useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(timer);}},[toast]);
useEffect(()=>{store.readChapters().then(setChapters).catch(e=>setError(`本地书架无法读取：${e.message}`));store.cacheSize().then(setCacheBytes);},[]);
useEffect(()=>{if(!isOidcCallback())return;void finishOidc().then(value=>{if(value){if(value.apiOrigin!==new URL(store.settings().apiBase).origin)throw Error('登录期间服务地址已切换，请回到原服务或重新登录。');store.saveSession(value);setAccount(value);const chapterId=sessionStorage.getItem('nc-login-chapter');if(chapterId)setCurrentId(chapterId);sessionStorage.removeItem('nc-login-chapter');notify('登录成功，已返回原来的阅读位置');}}).catch(e=>setError((e as Error).message));},[]);
useEffect(()=>{store.saveSettings(settings);},[settings]);
useEffect(()=>{if(!pendingKey)return;try{const raw=localStorage.getItem(pendingKey);if(raw){const pending=JSON.parse(raw) as ReadyQuote;if(pending.ownerId===account?.user.id&&pending.apiOrigin===apiOrigin){setReady(pending);notify('上次提交尚未核实，请使用同一确认按钮找回任务。');}}}catch{setError('未能读取上次提交记录，请先查看服务端任务记录再新建。');}},[pendingKey]);
useEffect(()=>{let live=true;setOnline('connecting');Promise.allSettled([api.capabilities(),api.authConfig(),...(account?[api.usage()]:[])]).then(results=>{if(!live)return;const c=results[0];if(c.status==='fulfilled'){setCaps(c.value as Capabilities);setOnline('online');}else setOnline('offline');const a=results[1];if(a.status==='fulfilled'){setAuthAllowed(Boolean((a.value as AuthConfig).dev_auth));setAuthConfig(a.value as AuthConfig);}if(results[2]?.status==='fulfilled')setUsage(results[2].value as Usage);});return()=>{live=false};},[api,account]);
const updateChapter=useCallback((chapter:Chapter)=>{setChapters(previous=>{const next=previous.some(c=>c.id===chapter.id)?previous.map(c=>c.id===chapter.id?chapter:c):[chapter,...previous];chaptersRef.current=next;return next;});void store.saveChapter(chapter).catch(e=>setError(`本地记录未保存：${e.message}`));},[]);
const updatePage=useCallback((chapterId:string,page:Page)=>{const c=chaptersRef.current.find(c=>c.id===chapterId);if(c)updateChapter({...c,pages:c.pages.map(p=>p.id===page.id?page:p)});},[updateChapter]);
const refreshUsage=useCallback(()=>{if(accountRef.current)void api.usage().then(setUsage).catch(()=>{});},[api]);
useEffect(()=>{
  if(!account)return;
  let stopped=false;let timer:ReturnType<typeof setTimeout>;
  async function poll(){
    const candidates=chaptersRef.current.flatMap(c=>c.pages.filter(p=>p.ownerId===account!.user.id&&p.apiOrigin===apiOrigin).flatMap(p=>p.jobs.filter(j=>!terminal.has(j.status)||j.status==='succeeded'&&!!j.output_asset_id&&!p.outputBlobs[j.id])));
    const ids=[...new Map(candidates.sort((a,b)=>((a.status==='queued'||a.status==='running')?0:1)-((b.status==='queued'||b.status==='running')?0:1)).map(j=>[j.id,j])).keys()].slice(0,80);
    try{
      if(ids.length){
        const {items}=await api.status(ids);if(stopped)return;
        for(const c of chaptersRef.current){
          let changed=false;const pages=[...c.pages];
          for(let i=0;i<pages.length;i++){
            let p=pages[i];if((p.ownerId!==account!.user.id||p.apiOrigin!==apiOrigin))continue;
            const jobs=p.jobs.map(j=>items.find(n=>n.id===j.id)??j);
            if(jobs.some((j,k)=>j!==p.jobs[k])){p={...p,jobs};changed=true;}
            for(const j of jobs){
              if(j.status==='succeeded'&&j.output_asset_id&&!p.outputBlobs[j.id]){
                try{const blob=await api.image(j.output_asset_id);if(stopped)return;const key=`result:${apiOrigin}:${account!.user.id}:${j.id}`;await store.putBlob(key,blob);p={...p,outputBlobs:{...p.outputBlobs,[j.id]:key}};changed=true;}
                catch(e){const message=(e as Error).message;if(p.fetchError!==message){p={...p,fetchError:message};changed=true;}}
              }
            }
            pages[i]=p;
          }
          if(changed){const latest=chaptersRef.current.find(ch=>ch.id===c.id);if(latest)updateChapter({...latest,pages:latest.pages.map(p=>{const synced=pages.find(n=>n.id===p.id);return synced?{...p,jobs:synced.jobs,outputBlobs:synced.outputBlobs,fetchError:synced.fetchError}:p;})});}
        }
        refreshUsage();
      }
    }catch{/* Persistent job IDs survive temporary network errors. */}
    if(!stopped)timer=setTimeout(poll,document.hidden?12000:4000);
  }
  void poll();return()=>{stopped=true;clearTimeout(timer);};
},[api,account,updateChapter,refreshUsage]);
useEffect(()=>{const manifestId=new URLSearchParams(location.search).get('manifest');if(!manifestId||typeof chrome==='undefined'||!chrome.storage?.local)return;chrome.storage.local.get([`manifest:${manifestId}`,'pendingLanguage']).then(data=>{if(data.pendingLanguage)setSettings(s=>({...s,language:String(data.pendingLanguage)}));const m=data[`manifest:${manifestId}`] as ChapterManifest;if(m)setSourceManifest(m);});},[]);
async function importFiles(files:File[]){const mobi=files.find(f=>/\.mobi$/i.test(f.name));if(mobi){if(files.length>1){setError('MOBI 请一次导入一本，以保留独立章节与阅读位置。');return;}await importMobiFile(mobi);return;}const accepted=naturalSort(files.filter(f=>['image/png','image/jpeg','image/webp'].includes(f.type)));if(!accepted.length){setError('请选择 PNG、JPEG、WebP 图片或无 DRM 的 MOBI 漫画。');return;}if(accepted.length>300){setError('一次最多导入 300 张图片，请拆分阅读清单。');return;}setBusy(`正在整理 ${accepted.length} 张图片…`);setError('');try{const pages:Page[]=[];for(const file of accepted){if(file.size>40*1024*1024)throw Error(`${file.name} 超过本地单图 40 MB 限制。`);const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>100_000_000){bitmap.close();throw Error(`${file.name} 像素过大，无法安全解码。`);}const p=emptyPage(file.name,bitmap.width,bitmap.height);bitmap.close();p.blobKey=`original:${p.id}`;await store.putBlob(p.blobKey,file);pages.push(p);}const chapter=makeChapter(accepted[0].name.replace(/\.[^.]+$/,'')+(pages.length>1?` · ${pages.length} 页`:''),pages);updateChapter(chapter);setCurrentId(chapter.id);setView('library');notify(`已导入 ${pages.length} 页 · 原图保存在本地`);await store.enforceCacheBudget([...chaptersRef.current,chapter],settings.cacheLimitMb,chapter.id);setCacheBytes(await store.cacheSize());}catch(e){setError((e as Error).message);}finally{setBusy('');if(input.current)input.current.value='';}}
async function openDemo(){const existing=chaptersRef.current.find(c=>c.demo);if(existing){setCurrentId(existing.id);return;}setBusy('正在打开原创阅读示例…');try{const blob=await(await fetch('/samples/starlight-bookshop.png')).blob();const bitmap=await createImageBitmap(blob);const p=emptyPage('星光书店 · 原创示例.png',bitmap.width,bitmap.height);bitmap.close();p.blobKey=`original:${p.id}`;await store.putBlob(p.blobKey,blob);const c={...makeChapter('星光书店', [p],'原创阅读示例'),demo:true};updateChapter(c);setCurrentId(c.id);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
async function acquireManifest(){if(!sourceManifest)return;setBusy('正在获取已发现的原图…');try{const origins=[...new Set(sourceManifest.items.map(i=>new URL(i.url).origin+'/*'))];const granted=origins.length?await chrome.permissions.request({origins}):true;if(!granted)throw Error('未取得图片域名权限。你仍可导入本地图片。');const pages:Page[]=[];for(const item of sourceManifest.items){const p=emptyPage(`第 ${item.order+1} 页`,item.width,item.height);p.sourceUrl=item.url;try{const valid=await chrome.runtime.sendMessage({type:'NC_SOURCE_IMAGE',manifestId:sourceManifest.id,pageId:item.id});if(!valid.ok)throw Error(valid.error);const response=await fetch(valid.data.url,{credentials:'omit'});if(!response.ok)throw Error(`图片获取失败（HTTP ${response.status}），请在源网页保存后导入。`);const blob=await response.blob();if(blob.size>40*1024*1024)throw Error('图片超过 40 MB 本地限制。');const bitmap=await createImageBitmap(blob);p.width=bitmap.width;p.height=bitmap.height;bitmap.close();p.blobKey=`original:${p.id}`;await store.putBlob(p.blobKey,blob);}catch(e){p.fetchError=(e as Error).message;}pages.push(p);}const c={...makeChapter(sourceManifest.title,pages,sourceManifest.adapter),sourceUrl:sourceManifest.url,discoveryComplete:sourceManifest.discoveryComplete};updateChapter(c);setSettings(s=>({...s,direction:sourceManifest.direction}));setCurrentId(c.id);setSourceManifest(undefined);notify(`已获取 ${pages.filter(p=>p.blobKey).length} / ${pages.length} 张原图`);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
async function authenticate(){setBusy('正在登录…');setError('');try{let value:store.Session;if(authAllowed){const auth=await api.login(username.trim());value={token:auth.access_token,user:auth.user,apiOrigin};}else{if(!authConfig)throw Error('无法读取身份服务配置。');if(currentId)sessionStorage.setItem('nc-login-chapter',currentId);const result=await startOidc(authConfig,settings.apiBase);if(!result)return;value=result;}if(value.apiOrigin!==new URL(store.settings().apiBase).origin)throw Error('登录期间服务地址已切换，请重新登录。');store.saveSession(value);setAccount(value);setLoginOpen(false);notify('已连接账户，可以开始翻译了');}catch(e){setError((e as Error).message);}finally{setBusy('');}}
useEffect(()=>{if(account&&pendingIntent){const intent=pendingIntent;setPendingIntent(undefined);void prepareTranslation(intent);} },[account]);
async function prepareTranslation(intent:Intent,automatic=false){if(!currentRef.current)return;if(!automatic){autoState.current.enabled=false;setAutoApproval(false);}if(pendingKey){const raw=localStorage.getItem(pendingKey);if(raw){if(!automatic)setReady(JSON.parse(raw));return;}}if(!accountRef.current){setPendingIntent(intent);setLoginOpen(true);return;}if(caps&&!caps.modes.find(m=>m.id===intent.mode)?.enabled){setError(`${modeLabels[intent.mode]}暂未配置就绪，请选择其他方式或稍后再试。`);return;}if(intent.pages.length>(caps?.limits.max_batch??100)){setError('单次翻译最多选择 '+(caps?.limits.max_batch??100)+' 页，请在页面列表调整范围。');return;}const chapterId=currentRef.current;const acc=accountRef.current;const liveApi=new Api(settings.apiBase,acc.token);if(!automatic){setBusy('正在上传选中原图并估算额度…');setError('');}try{const storedChapter=(await store.readChapters()).find(c=>c.id===chapterId);const pages:Page[]=[];for(const requested of intent.pages){let p=storedChapter?.pages.find(p=>p.id===requested.id)??chaptersRef.current.find(c=>c.id===chapterId)?.pages.find(p=>p.id===requested.id);if(!p||automatic&&autoVisited.current.has(p.id))continue;const sameOwner=p.ownerId===acc.user.id&&p.apiOrigin===apiOrigin;if(!intent.regenerate&&sameOwner&&p.jobs.some(j=>j.mode===intent.mode&&j.target_language===settings.language&&(['queued','running','outcome_unknown'].includes(j.status)||j.status==='succeeded'&&!!p!.outputBlobs[j.id])))continue;if(!p.blobKey)throw Error(`${p.name} 原图未获取，请返回来源或重新导入。`);if(!sameOwner||!p.assetId||!p.assetExpiresAt||new Date(p.assetExpiresAt).getTime()<=Date.now()){const blob=await store.getBlob(p.blobKey);if(!blob)throw Error(`${p.name} 本地图片已清理，请重新导入。`);const asset=await liveApi.upload(blob,p.name);p={...p,assetId:asset.id,assetExpiresAt:asset.expires_at,ownerId:acc.user.id,apiOrigin,jobs:sameOwner?p.jobs:[],outputBlobs:sameOwner?p.outputBlobs:{},operationIds:sameOwner?p.operationIds:{}};updatePage(chapterId,p);}pages.push(p);}if(!pages.length){if(!automatic)notify('所选页面已有结果或正在处理，无需重复创建任务');return;}const quote=await liveApi.quote(pages.map(p=>p.assetId!),intent.mode,settings.language);const prepared:ReadyQuote={quote,intent:{...intent,pages},key:id(),chapterId,ownerId:acc.user.id,apiOrigin,targetLanguage:settings.language};if(automatic){if(currentRef.current!==chapterId||!autoState.current.enabled||autoScopeRef.current!==autoScope||accountRef.current?.user.id!==acc.user.id||accountRef.current?.apiOrigin!==apiOrigin)return;if(autoCount.current+pages.length>settings.autoLimit||autoBudget.current<quote.total_cost){setAutoApproval(false);notify('本次自动翻译已达到页数或额度上限');return;}autoCount.current+=pages.length;autoBudget.current-=quote.total_cost;for(const p of pages)autoVisited.current.add(p.id);await submitQuote(prepared,true);}else setReady(prepared);}catch(e){if(automatic){setAutoApproval(false);notify(`自动翻译已暂停：${(e as Error).message}`);}else setError((e as Error).message);}finally{if(!automatic)setBusy('');}}
async function submitQuote(prepared:ReadyQuote=ready!,automatic=false){
  if(!prepared||!accountRef.current)return;
  if(prepared.ownerId!==accountRef.current.user.id||prepared.apiOrigin!==accountRef.current.apiOrigin){setError('账户或服务已切换，请回到原账户核实这次提交。');return;}
  if(automatic&&(!autoState.current.enabled||autoState.current.chapterId!==prepared.chapterId||autoScopeRef.current!==autoScope))return;
  if(!automatic)setBusy('正在确认额度并提交任务…');
  const storageKey=`nc-submission:${prepared.apiOrigin}:${prepared.ownerId}`;
  try{
    // Persist before crossing the network boundary; an uncertain response reuses this exact key.
    localStorage.setItem(storageKey,JSON.stringify(prepared));
    let returned:Job[];
    if(prepared.intent.regenerate){
      returned=[];
      for(const page of prepared.intent.pages){
        const previous=page.jobs.filter(j=>j.mode===prepared.intent.mode&&j.target_language===prepared.targetLanguage).at(-1);
        const job=previous&&previous.input_asset_id===page.assetId?await api.rerun(previous.id,`${prepared.key}:${page.id}`,prepared.quote.id,prepared.quote.total_cost):(await api.batch(prepared.quote.id,prepared.quote.total_cost,prepared.key)).jobs[0];
        returned.push(job);
      }
    }else returned=(await api.batch(prepared.quote.id,prepared.quote.total_cost,prepared.key)).jobs;
    const c=chaptersRef.current.find(c=>c.id===prepared.chapterId);
    if(c){const pages=c.pages.map(p=>{if(p.ownerId!==prepared.ownerId||p.apiOrigin!==prepared.apiOrigin)return p;const jobs=returned.filter(j=>j.input_asset_id===p.assetId);return jobs.length?{...p,jobs:[...p.jobs.filter(j=>!jobs.some(n=>n.id===j.id)),...jobs]}:p;});const updated={...c,pages};await store.saveChapter(updated);updateChapter(updated);}
    else localStorage.setItem(`nc-detached:${prepared.apiOrigin}:${prepared.ownerId}:${prepared.key}`,JSON.stringify({jobs:returned.map(j=>j.id),createdAt:Date.now()}));
    localStorage.removeItem(storageKey);
    if(!automatic){setReady(undefined);notify(`已提交 ${returned.length} 页${modeLabels[prepared.intent.mode]} · 可以继续读原图`);}
    refreshUsage();
  }catch(e){if(submissionRejected(e)){localStorage.removeItem(storageKey);setReady(undefined);setError((e as Error).message+' 此请求未创建任务，请重新估算。');}else{setError((e as Error).message+' 提交记录已保存，请使用同一确认按钮核实，避免重复新建。');if(automatic)setReady(prepared);}if(automatic)setAutoApproval(false);}
  finally{if(!automatic)setBusy('');}
}
const autoTranslate=useCallback(async(pages:Page[])=>{if(!autoApproval||autoLock.current||!account)return;autoLock.current=true;try{await prepareTranslation({mode:settings.translationMode,pages},true);}finally{autoLock.current=false;}},[autoApproval,account,settings.language,settings.translationMode,settings.autoLimit,api]);
function askAuto(){if(autoApproval){autoState.current.enabled=false;setAutoApproval(false);return;}if(!account){setLoginOpen(true);return;}if(!caps?.modes.find(m=>m.id===settings.translationMode)?.enabled){setError('所选翻译方式尚未配置，暂时不能开启自动翻译。');return;}const cost=(caps?.modes.find(m=>m.id===settings.translationMode)?.unit_cost??1)*settings.autoLimit;setConfirmAction({title:'开启本次阅读自动翻译',body:`${modeLabels[settings.translationMode]}，按当前页 + 后 2 页按需提交。本次最多 ${settings.autoLimit} 页、${cost} 点；已有结果不会重复提交。切换书架或关闭阅读器后停止添加任务。`,action:async()=>{if(autoScopeRef.current!==autoScope)return;approvedAutoScope.current=autoScope;autoCount.current=0;autoVisited.current.clear();autoBudget.current=cost;setAutoApproval(true);}});}
function exitReader(){setAutoApproval(false);setCurrentId(undefined);}
const allJobs=chapters.flatMap(c=>c.pages.filter(p=>p.ownerId===account?.user.id&&p.apiOrigin===apiOrigin).flatMap(p=>p.jobs.map(j=>({...j,page:p,chapter:c})))).sort((a,b)=>b.created_at.localeCompare(a.created_at));
const balance=usage?.available??caps?.quota?.available;
const nav=(value:View)=>{exitReader();setView(value);location.hash=value;setError('');};
return <div className="app-shell" onDragOver={e=>{if(e.dataTransfer.types.includes('Files')){e.preventDefault();setDrag(true);}}} onDrop={e=>{e.preventDefault();setDrag(false);void importFiles(Array.from(e.dataTransfer.files));}}>
<input aria-label="选择漫画图片" type="file" multiple accept="image/png,image/jpeg,image/webp,.mobi" ref={input} className="hidden-input" onChange={e=>void importFiles(Array.from(e.target.files??[]))}/>
<aside className="sidebar"><button aria-label="返回我的书架" className="brand brand-button" onClick={()=>nav('library')}><span className="brand-mark"><Icon name="book" size={25}/></span><b>Node Comics<span>漫游 · 让故事跨越语言</span></b></button><span className="nav-label">我的空间</span><nav><Nav icon="book" text="我的书架" active={view==='library'&&!current} onClick={()=>nav('library')} badge={chapters.length||undefined}/><Nav icon="clock" text="翻译记录" active={view==='history'&&!current} onClick={()=>nav('history')} badge={allJobs.filter(j=>!terminal.has(j.status)).length||undefined}/></nav><div className="sidebar-rule"/><span className="nav-label">阅读偏好</span><nav><Nav icon="settings" text="偏好设置" active={view==='settings'&&!current} onClick={()=>nav('settings')}/><Nav icon="user" text="我的账户" active={view==='account'&&!current} onClick={()=>nav('account')}/>{account?.user.role==='admin'&&<Nav icon="shield" text="运营管理" active={view==='admin'&&!current} onClick={()=>nav('admin')}/>}</nav><div className="sidebar-bottom"><div className="tiny-comic"><span>✦</span><b>好故事，值得读懂。</b><p>每一页，都有新的相遇。</p><div className="comic-dots"/></div><div className="local-note"><Icon name="shield" size={15}/><span>原图本地保存 · 按需上传</span></div><button aria-label="我的账户与登录" className="account-chip" onClick={()=>account?nav('account'):setLoginOpen(true)}><span className="avatar">{account?account.user.name[0].toUpperCase():<Icon name="user" size={20}/>}</span><span><b>{account?.user.name??'漫游旅人'}</b><small>{account?'测试账户 · 已连接':'登录后解锁翻译'}</small></span><Icon name="chevron" size={15}/></button></div></aside>
<div className="workspace"><header className="topbar"><div className="breadcrumb"><span>我的空间</span><Icon name="chevron" size={13}/><b>{current?'沉浸阅读':{library:'我的书架',history:'翻译记录',settings:'偏好设置',account:'我的账户',admin:'运营管理'}[view]??'我的书架'}</b></div><div className="top-actions"><span className={`service-status ${online}`}><i/>{online==='online'?'翻译服务已连接':online==='connecting'?'正在连接服务':'离线阅读模式'}</span><button className="quota-pill" onClick={()=>account?nav('account'):setLoginOpen(true)}><Icon name="spark" size={15}/>{account?`${balance??'—'} 点可用`:'连接翻译账户'}</button><span className="beta-tag">LOCAL PREVIEW</span></div></header>
{error&&<div className="global-error" role="alert"><Icon name="info" size={18}/><span>{error}</span><button aria-label="关闭错误提示" onClick={()=>setError('')}><Icon name="close" size={16}/></button></div>}
{current?<Reader chapter={current} settings={settings} setSettings={setSettings} update={updateChapter} onBack={exitReader} onTranslate={(mode,pages,regenerate)=>void prepareTranslation({mode,pages,regenerate})} onImport={()=>input.current?.click()} notify={notify} autoEnabled={autoState.current.enabled} onAutoToggle={askAuto} onAutoWindow={autoTranslate} caps={caps} userId={account?.user.id} apiOrigin={apiOrigin} onCancel={async(job)=>{try{const result=await api.cancel(job.id);const p=current.pages.find(p=>p.jobs.some(j=>j.id===job.id));if(p)updatePage(current.id,{...p,jobs:p.jobs.map(j=>j.id===job.id?result:j)});refreshUsage();}catch(e){setError((e as Error).message);}}}/>:
<main className="main-content">{view==='admin'&&account?.user.role==='admin'&&<AdminPanel api={api}/>}
{view==='library'&&<><section className="welcome-banner"><div className="hero-copy"><span className="eyebrow"><i/> EVERY PANEL, A NEW WORLD</span><h1>故事，<br/>不该止于<span>语言。</span><span className="title-star">✦</span></h1><p>把喜欢的漫画带进来。<br/>从原文到心动，读懂每一格的精彩。</p><button className="button primary" onClick={()=>input.current?.click()}><Icon name="plus" size={18}/>导入漫画<Icon name="arrow" size={17}/></button><span className="hero-footnote">PNG / JPG / WEBP / MOBI · 故事一起带进来</span></div><div className="hero-art" aria-hidden="true"><span className="art-orbit orbit-one"/><span className="art-orbit orbit-two"/><span className="art-star star-one">✦</span><span className="art-star star-two">✧</span><div className="floating-caption caption-ja">物語のつづきを。<small>故事，还在继续。</small></div><div className="manga-ticket ticket-back"/><div className="manga-ticket"><div className="ticket-top">NODE COMICS <span>VOL. 01</span></div><img src="/samples/starlight-bookshop.png" alt=""/><div className="ticket-bottom"><b>星光书店</b><span>THE STARLIGHT BOOKSHOP</span><i>✦</i></div></div><div className="floating-caption caption-cn"><Icon name="check" size={14}/><span>让每一句心声，<br/><b>都被好好听见。</b></span></div><span className="art-number">01 / ∞</span></div></section>
<div className="mode-cards"><div className="feature-card"><span className="feature-icon blue"><Icon name="globe" size={24}/></span><div><h3>AI 图片翻译 <span>读懂每一格</span></h3><p>把原图交给图片模型，让故事跨越语言。</p></div><Icon name="arrow" size={18}/></div><div className="feature-card"><span className="feature-icon pink"><Icon name="spark" size={24}/></span><div><h3>原图随时对照 <span>故事本来的样子</span></h3><p>原图与译图独立保留，切换语言也不丢版本。</p></div><Icon name="arrow" size={18}/></div></div>
<section className="bookshelf"><div className="section-heading"><div><span className="eyebrow muted">MY LITTLE LIBRARY</span><h2>我的书架 <span>{chapters.length.toString().padStart(2,'0')}</span></h2></div><div className="section-actions"><span className="small-muted">只在这台设备，留住阅读进度</span><button className="button secondary small" onClick={()=>input.current?.click()}><Icon name="plus" size={16}/>添加漫画</button></div></div>{chapters.length?<div className="book-grid">{chapters.map(chapter=><BookCard key={chapter.id} chapter={chapter} onOpen={()=>setCurrentId(chapter.id)} onDelete={()=>setConfirmAction({title:'移除这本漫画？',body:'将删除该书本地原图与译图缓存。已提交的服务器任务不受影响；服务器图片可在翻译记录中单独删除。',action:async()=>{await store.deleteChapter(chapter);setChapters(c=>c.filter(v=>v.id!==chapter.id));}})}/>)}</div>:<div className="empty-library"><span className="empty-illustration"><Icon name="folder" size={38}/><i>＋</i><span>✦</span></span><h3>你的下一段故事，从这里开始</h3><p>拖入漫画图片，或从浏览器插件带入网页图片。<br/>无需登录，也能安静地读完一整章。</p><button className="text-link" onClick={()=>input.current?.click()}>选择本地图片 <Icon name="arrow" size={16}/></button></div>}</section>
<button className="sample-strip" onClick={()=>void openDemo()}><span className="sample-cover"><img src="/samples/starlight-bookshop.png" alt="星光书店原创示例封面"/></span><span><small>不妨先读一段小故事</small><b>星光书店 <i>原创阅读示例</i></b><p>一位少女、一只白猫，和一家藏着星星的书店。</p></span><span className="sample-cta">打开示例 <Icon name="arrow" size={18}/></span></button><footer className="page-footer"><span>MADE FOR THE LOVE OF STORIES</span><span>原图永远在 · 翻译由你决定 <Icon name="spark" size={12}/></span></footer></>}
{view==='history'&&<><PageTitle eyebrow="YOUR TRANSLATION JOURNEY" title="每一页的翻译，都有迹可循。" description="已提交任务独立执行。关闭阅读器后，回来仍能找回结果。"/><div className="stat-grid"><Stat label="翻译任务" value={allJobs.length}/><Stat label="已完成" value={allJobs.filter(j=>j.status==='succeeded').length}/><Stat label="进行中 / 待核实" value={allJobs.filter(j=>!terminal.has(j.status)).length}/></div>{allJobs.length?<div className="job-list">{allJobs.map(job=><div className="job-row" key={job.id}><span className={`feature-icon ${job.mode==='redraw'?'pink':'blue'}`}><Icon name={job.mode==='redraw'?'spark':'globe'}/></span><div className="job-main"><b>{job.chapter.title} · {job.page.name}</b><small>{modeLabels[job.mode]} · {job.target_language} · 版本 {job.version} · {new Date(job.created_at).toLocaleString()}</small>{job.error&&<p className="inline-error">{job.error.message}</p>}</div><Status job={job}/><span className="cost-label">{job.cost} 点</span><button className="button secondary small" onClick={()=>setCurrentId(job.chapter.id)}>查看</button>{job.status==='queued'&&<button className="text-link" onClick={async()=>{try{await api.cancel(job.id);notify('已请求取消，稍后同步任务状态');}catch(e){setError((e as Error).message);}}}>取消</button>}{job.output_asset_id&&<button className="icon-button" aria-label="删除服务器译图" onClick={()=>setConfirmAction({title:'删除服务器译图？',body:'删除后立即撤销服务器访问。本地已经保存的副本仍可阅读，重新生成会创建新任务。',action:async()=>{await api.deleteImage(job.output_asset_id!);notify('服务器译图已删除');}})}><Icon name="trash" size={16}/></button>}</div>)}</div>:<Empty icon="clock" title="还没有翻译记录" text="打开一本漫画，选择需要翻译的页面。原图会一直陪着你。"/>}</>}
{view==='history'&&<ServerJobs api={api} knownIds={allJobs.map(j=>j.id)}/>}{view==='settings'&&<><PageTitle eyebrow="MAKE IT YOURS" title="调成你喜欢的阅读节奏。" description="偏好保存在本机。自动翻译每次进入阅读器都保持关闭。"/><section className="settings-card"><h3><Icon name="book"/>阅读偏好</h3><SettingRow title="默认目标语言" description="切换语言会保留其他语言的译图版本。"><select value={settings.language} onChange={e=>setSettings(s=>({...s,language:e.target.value}))}>{(caps?.languages??[{id:'zh-Hans',label:'简体中文'},{id:'en',label:'English'},{id:'ja',label:'日本語'}]).map(l=><option key={l.id} value={l.id}>{l.label}</option>)}</select></SettingRow><SettingRow title="翻页方向" description="单页模式中的方向键遵循此设置。"><select value={settings.direction} onChange={e=>setSettings(s=>({...s,direction:e.target.value as Settings['direction']}))}><option value="rtl">从右向左 · 日漫习惯</option><option value="ltr">从左向右</option></select></SettingRow><SettingRow title="阅读方式" description="连续阅读仅解码当前页附近的有限图片窗口。"><select value={settings.layout} onChange={e=>setSettings(s=>({...s,layout:e.target.value as Settings['layout']}))}><option value="continuous">连续纵向滚动</option><option value="single">单页翻页</option></select></SettingRow><SettingRow title="自动翻译上限" description="仅在阅读器明确开启后生效；AI 翻译始终按需启动。"><label className="unit-input"><input aria-label="自动翻译页数上限" type="number" min="1" max="50" value={settings.autoLimit} onChange={e=>setSettings(s=>({...s,autoLimit:Math.max(1,Math.min(50,Number(e.target.value)||1))}))}/> 页 / 本次阅读</label></SettingRow></section><section className="settings-card"><h3><Icon name="folder"/>图片与隐私</h3><SettingRow title="本地图片缓存" description={`当前约 ${(cacheBytes/1024/1024).toFixed(1)} MB；仅在开始翻译时上传选定原图。`}><select value={settings.cacheLimitMb} onChange={e=>setSettings(s=>({...s,cacheLimitMb:Number(e.target.value)}))}><option value="128">128 MB</option><option value="512">512 MB</option><option value="1024">1 GB</option></select></SettingRow><SettingRow title="清理本地图片" description="保留书架与阅读位置；清理后离线无法显示原图。"><button className="button danger small" onClick={()=>setConfirmAction({title:'清理本地图片缓存？',body:'所有本地原图和译图将被删除，书架和进度保留。之后需重新导入原图，译图可在服务器保留期内重新获取。',action:async()=>{await store.clearImages(chaptersRef.current);setChapters(await store.readChapters());setCacheBytes(0);notify('本地图片已清理，书架与进度已保留');}})}>清理缓存</button></SettingRow><div className="privacy-note"><Icon name="shield"/><p>服务器原图与译图暂存 {caps?.retention_days??7} 天。图片归你的账户私有，不接收源网站 Cookie，也不会公开分享。</p></div></section><section className="settings-card"><h3><Icon name="globe"/>翻译服务</h3><SettingRow title="后端服务地址" description="只填写你的可信产品服务地址。模型与密钥由后端统一管理。"><input aria-label="后端服务地址" className="api-input" type="url" value={apiDraft} onChange={e=>setApiDraft(e.target.value)}/><button className="button secondary small" onClick={()=>void saveApiAddress()}>保存并连接</button></SettingRow><div className="privacy-note"><Icon name="info"/><p>当前为本地测试版本。插件如需连接新服务域名，会在使用时申请对应访问权限。</p></div></section></>}
{view==='account'&&<><PageTitle eyebrow="A LITTLE MAGIC FOR EVERY PAGE" title="把额度，留给喜欢的故事。" description="成功交付后结算；失败或未执行时释放预占。费用与任务逐笔记录。"/>{account?<><div className="account-summary"><span className="avatar large">{account.user.name[0].toUpperCase()}</span><div><h2>{account.user.name}</h2><p>本地开发测试账户 · {account.user.role==='admin'?'管理员':'读者'}</p></div><button className="button secondary small" onClick={()=>{store.saveSession(null);setAccount(null);setUsage(undefined);setAutoApproval(false);notify('已退出账户，原图仍可继续阅读');}}>退出登录</button></div><div className="stat-grid"><Stat label="可用额度" value={usage?.available??'—'} suffix="点"/><Stat label="处理中预占" value={usage?.reserved??'—'} suffix="点"/><Stat label="账户余额" value={usage?.balance??'—'} suffix="点"/></div><div className="settings-card"><h3><Icon name="coin"/>额度流水</h3>{usage?.items.length?<div className="ledger">{usage.items.map(row=><div key={row.id}><span>{{reserve:'任务预占',settle:'成功结算',release:'释放预占',grant:'发放测试额度'}[row.kind]??row.kind}</span><small>{new Date(row.created_at).toLocaleString()}</small><b>{row.amount} 点</b></div>)}</div>:<p className="empty-copy">还没有额度流水。选择一页，开始第一次翻译吧。</p>}</div></>:<div className="login-prompt"><span className="feature-icon pink"><Icon name="user" size={28}/></span><h2>准备好，一起漫游了吗？</h2><p>无需登录即可阅读原图。连接测试账户，开始翻译并查看额度。</p><button className="button primary" onClick={()=>setLoginOpen(true)}>连接测试账户 <Icon name="arrow" size={18}/></button></div>}<div className="privacy-note standalone"><Icon name="info"/><p>本版本使用运营方发放的测试额度，尚未接入支付。公开部署需配置正式身份认证。</p></div></>}
</main>}
</div>
{drag&&<div className="drop-overlay" onDragLeave={()=>setDrag(false)}><Icon name="upload" size={60}/><h2>把故事放在这里</h2><p>松开即可导入漫画图片或无 DRM 的 MOBI 文件</p></div>}
{busy&&<div className="busy-pill" role="status"><span className="spinner"/>{busy}</div>}{toast&&<div className="toast" role="status"><Icon name="check" size={18}/>{toast}</div>}
{loginOpen&&<Modal title="连接你的漫游账户" subtitle="原图无需登录。翻译任务和额度将归属于这个账户。" onClose={()=>{setLoginOpen(false);setPendingIntent(undefined);}}>
  {authAllowed?<><div className="notice"><Icon name="info"/><span>本地测试登录已由后端开启，仅用于开发验证。</span></div><label className="field">测试用户名<input value={username} maxLength={60} onChange={e=>setUsername(e.target.value)} placeholder="例如 reader" autoFocus/></label></>:<div className="notice"><Icon name="shield"/><span>{authConfig?.mode==='oidc'?'将前往身份服务安全登录，完成后回到当前阅读位置。':'身份服务尚未配置，请联系运营方。'}</span></div>}
  <button className="button primary full" style={{marginTop:20}} disabled={!!busy||(authAllowed?!username.trim():authConfig?.mode!=='oidc'||!authConfig?.authorization_endpoint||!authConfig?.token_endpoint||!authConfig?.client_id)} onClick={()=>void authenticate()}>{authAllowed?'连接测试账户':'继续登录'} <Icon name="arrow" size={18}/></button>
</Modal>}
{ready&&<Modal title={`开始${modeLabels[ready.intent.mode]}`} subtitle="图片已上传。确认后才会创建任务并预占额度。" onClose={()=>{if(!busy)setReady(undefined);}}><div className="quote-summary"><span>本次选中<b>{ready.quote.page_count} <small>页</small></b></span><span>预计预占<b>{ready.quote.total_cost} <small>点</small></b></span><span>目标语言<b className="language-value">{caps?.languages.find(l=>l.id===ready.targetLanguage)?.label??ready.targetLanguage}</b></span></div><p className="modal-copy">逐页交付、逐页结算；原图与已有译图一直保留。{ready.intent.mode==='classic'?'常规翻译只处理文字区域，请检查识别和排版效果。':'图片重绘可能改变画面细节，请在完成后对照检查。'}</p>{ready.intent.regenerate&&<p className="notice warning">这是一次主动新建。结果待核实的旧请求可能已产生成本。</p>}<div className="quote-expiry">报价有效至 {new Date(ready.quote.expires_at).toLocaleTimeString()} · 确认后可继续阅读</div><button className="button primary full" disabled={!!busy} onClick={()=>void submitQuote()}><Icon name="spark" size={18}/>确认并开始 · {ready.quote.total_cost} 点</button></Modal>}
{sourceManifest&&<Modal title={`发现 ${sourceManifest.items.length} 张图片`} subtitle={sourceManifest.title} onClose={()=>setSourceManifest(undefined)}><div className="notice"><Icon name="info"/><span>{sourceManifest.note}</span></div><p className="modal-copy">下一步按需申请图片域名权限，并把原图缓存到当前设备。此时不会上传到翻译后端。</p><button className="button primary full" onClick={()=>void acquireManifest()} disabled={!!busy||!sourceManifest.items.length}>获取原图并阅读 <Icon name="arrow"/></button></Modal>}
{confirmAction&&<Modal title={confirmAction.title} subtitle={confirmAction.body} onClose={()=>setConfirmAction(undefined)}><button className="button primary full" onClick={async()=>{const action=confirmAction;setConfirmAction(undefined);try{await action.action();}catch(e){setError((e as Error).message);}}}>确认</button></Modal>}
</div>;
}
function Nav({icon,text,active,onClick,badge}:{icon:string;text:string;active:boolean;onClick:()=>void;badge?:number}){return <button className={`nav-item ${active?'active':''}`} aria-label={text} onClick={onClick}><Icon name={icon} size={20}/><span>{text}</span>{badge!=null&&<small>{badge}</small>}{active&&<i/>}</button>;}
function PageTitle({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <div className="page-title"><span className="eyebrow muted">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>;}
function Stat({label,value,suffix}:{label:string;value:number|string;suffix?:string}){return <div className="stat-card"><span>{label}</span><b>{value}<small>{suffix}</small></b><Icon name="spark" size={32}/></div>;}
function Empty({icon,title,text}:{icon:string;title:string;text:string}){return <div className="empty-library compact"><span className="feature-icon pink"><Icon name={icon} size={30}/></span><h3>{title}</h3><p>{text}</p></div>;}
function SettingRow({title,description,children}:{title:string;description:string;children:ReactNode}){return <div className="setting-row"><div><b>{title}</b><p>{description}</p></div>{children}</div>;}
export function Status({job}:{job?:Job}){return <span className={`status-badge ${job?.status??'original'}`}><i/>{job?(job.status==='succeeded'&&job.quality_flags?.includes('unrecognized_regions')?'部分完成 · 保留原文':statusLabels[job.status]):'原图 · 未翻译'}</span>;}
export function Modal({title,subtitle,children,onClose}:{title:string;subtitle?:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog ref={ref} className="modal" onCancel={e=>{e.preventDefault();onClose();}}><button className="modal-close icon-button" aria-label="关闭弹窗" onClick={onClose}><Icon name="close"/></button><span className="modal-spark">✦</span><h2>{title}</h2>{subtitle&&<p className="modal-subtitle">{subtitle}</p>}{children}</dialog>;}
function BookCard({chapter,onOpen,onDelete}:{chapter:Chapter;onOpen:()=>void;onDelete:()=>void}){const [url,setUrl]=useState('');useEffect(()=>{let object='';let alive=true;const p=chapter.pages.find(p=>p.blobKey);if(p?.blobKey)store.getBlob(p.blobKey).then(blob=>{if(blob&&alive){object=URL.createObjectURL(blob);setUrl(object);}});return()=>{alive=false;if(object)URL.revokeObjectURL(object);};},[chapter.id,chapter.pages[0]?.blobKey]);const page=Math.max(1,chapter.pages.findIndex(p=>p.id===(store.readPosition(chapter.id)?.pageId??chapter.pageId))+1);return <article className="book-card"><button className="book-open" onClick={onOpen}><span className="book-cover">{url?<img src={url} alt={chapter.title}/>:<Icon name="book" size={42}/>}<span className="book-pages">{chapter.pages.length} 页</span><span className="book-play"><Icon name="book"/>继续阅读</span></span><h3>{chapter.title}</h3><span className="book-meta">{chapter.source} · 读到第 {page} 页</span><span className="book-progress"><i style={{width:`${page/Math.max(1,chapter.pages.length)*100}%`}}/></span></button><button className="book-remove icon-button" aria-label={`移除 ${chapter.title}`} onClick={onDelete}><Icon name="trash" size={15}/></button></article>;}
