import {initializeUiLanguage} from './i18n/load';
import {createRoot} from 'react-dom/client';
import {App} from './App';
import './styles.css';
import './redesign.css';
import './library.css';
import './ui/theme/surfaces.css';
import {connectReaderSettings} from './inline/settings';
import {settings} from './library/store';
void connectReaderSettings(settings()).catch(()=>{}).then(initializeUiLanguage).then(()=>createRoot(document.getElementById('root')!).render(<App/>));
