export type Mode = 'redraw' | 'classic';
export type JobStatus = 'awaiting_upload' | 'validating_upload' | 'queued' | 'running' | 'succeeded' | 'no_text' | 'failed' | 'cancelled' | 'outcome_unknown' | 'unknown_released';
export interface Job { id: string; input_asset_id: string | null; requested_asset_id?: string | null; output_asset_id: string | null; mode: Mode; target_language: string; status: JobStatus; phase: string; error?: { code: string; message: string }; quota_pages: number; quota_kind?:QuotaKind; quota_period_id?:string|null; created_at: string; completed_at?: string; version: number; cache_hit: boolean; reused?:boolean; quality_flags?: string[]; result_available?: boolean; result_expired?: boolean; settlement?: 'reserved'|'settled'|'released'|'free'|'included'; submission_id?:string|null; ordinal?:number; cancel_requested?:boolean; file_hash?:string|null; page_index?:number|null; image_sha256?:string; priority?:'realtime'|'preload'; user_order?:number; updated_at?:string;change_sequence?:number; }
export interface FilePageSource { file_hash: string; page_index: number; image_sha256?: string; }
export interface ImageAsset { id: string; width: number; height: number; expires_at: string|null; sha256?:string;byte_size?:number;mime?:string; }
export interface FilePageMatch extends FilePageSource { asset: ImageAsset | null; jobs: Job[]; display_jobs?: Job[]; }
export interface ModeQueue { mode:Mode; capacity:number; in_flight:number; available_slots:number; realtime_limit:number; realtime_count:number; queued:number; running:number; awaiting_upload:number; paused:boolean; version:number; weight?:number;upload_reserved?:boolean;upload_reservation_session_id?:string|null;session_id?:string|null; }
export interface UploadPlan {id:string;url:string;method:'PUT';headers:Record<string,string>;expires_at:string;authorization_required?:boolean;}
export interface SubmissionInput {mode:Mode;target_language:string;max_quota_pages:number;expected_kind?:QuotaKind;regenerate:boolean;rerun_job_id?:string;acknowledge_unknown_cost?:boolean;reading_session_id?:string;items:SubmissionImage[];}
export interface SubmissionImage {client_item_id:string;file_hash?:string;page_index?:number;image_sha256:string;byte_size:number;content_type:string;name:string;asset_id?:string;}
export interface SubmissionItem {client_item_id:string;job:Job;reused?:boolean;upload?:UploadPlan|null;}
export interface SubmissionReceipt {id:string;mode:Mode;target_language:string;items:SubmissionItem[];}
export interface TranslationChanges {items:Job[];deleted_job_ids:string[];cursor:string;has_more:boolean;}
export interface QueuePriority {session_id:string;sequence:number;expected_version:number;realtime_job_ids:string[];ordered_job_ids:string[];ttl_seconds:number;takeover?:boolean;reserve_next_upload?:boolean;}
export interface PriorityReceipt {version:number;realtime_job_ids:string[];expires_at:string;session_id?:string;}
export interface Page { id: string; name: string; width: number; height: number; fileHash?: string; pageIndex?: number; imageSha256?: string; imageByteSize?:number;imageMime?:string; blobKey?: string; sourceUrl?: string; fetchError?: string; translationError?: string; assetId?: string; assetExpiresAt?: string|null; ownerId?: string; apiOrigin?:string; jobs: Job[]; outputBlobs: Record<string, string>; }
export interface ReadingCopy { id: string; title: string; source: string; sourceKey: string; sourceUrl?: string; sourceEntryId?: string; sourcePagesEdited?:boolean; webImports?:{key:string;pageIds:string[]}[]; manifestRevision: number; retention: 'cache'|'offline'; language?: string; versionId?: string; createdAt: number; updatedAt: number; lastReadAt?:number; coverPageId?:string; pages: Page[]; pageId: string; relativeOffset: number; demo?: boolean; discoveryComplete: boolean; knownTotal?: number; }
export interface User { id: string; name: string; role: string; }
export type QuotaKind='classic_daily'|'classic_unlimited'|'redraw_monthly'|'classic_grant'|'redraw_grant'|'unavailable';
export interface QuotaBucket {id:string;kind:QuotaKind;mode:Mode;source:'daily'|'membership'|'grant';granted:number;used:number;reserved:number;available:number;starts_at:string;expires_at:string;grants_access:boolean;note:string;}
export interface QuotaSummary {id:string;kind:QuotaKind;granted:number;used:number;reserved:number;available:number;starts_at:string;resets_at:string|null;next_expiry_at:string;buckets:QuotaBucket[];}
export interface ModeEntitlement {allowed:boolean;unlimited:boolean;quota_kind:QuotaKind;consent_version:string;quota:QuotaSummary|null;}
export interface Entitlements {plan:'free'|'plus';plus_started_at:string|null;plus_expires_at:string|null;timezone:string;queue_capacity:number;realtime_slots:number;scheduler_weight:number;modes:Record<Mode,ModeEntitlement>;generated_at:string;pending_previous_period_pages:number;}
export interface BillingStatus {enabled:boolean;environment:'sandbox'|'production';trial_eligible:boolean;checkout_pending:boolean;checkout_error:string|null;entitlement_expires_at:string|null;subscription:{status:string;next_billed_at:string|null;cancel_at:string|null;trial_ends_at:string|null;paid_ends_at:string|null}|null;}
export interface Capabilities { modes: { id: Mode; label: string; enabled: boolean; languages?:string[] }[]; languages: { id: string; label: string }[]; limits: { max_bytes: number; max_pixels: number; max_dimension: number; max_batch: number;max_active_jobs:number }; entitlements:Entitlements|null; retention_days: number; }
export interface Usage { entitlements:Entitlements; items: { id: string; job_id: string|null;period_id:string|null;quota_kind:QuotaKind|null;kind: string; pages: number; created_at: string; note?:string }[]; total: number; next_offset?:number|null; }
export interface Settings { apiBase: string; language: string; translationMode: Mode; direction: 'ltr' | 'rtl'; layout: 'continuous' | 'single'; fit: 'width' | 'window'; cacheLimitMb: number; requestConcurrency: number; appearance:'system'|'light'|'dark'; accentTheme:'sky'|'rose'|'mint'|'iris'; libraryLayout:'grid'|'list'; readerBackground:'gray'|'paper'|'night'; textScale:number; }
export const defaults: Settings = { apiBase: 'http://127.0.0.1:18088', language: 'zh-Hans', translationMode: 'classic', direction: 'rtl', layout: 'continuous', fit: 'width', cacheLimitMb: 512, requestConcurrency: 2, appearance:'system',accentTheme:'sky',libraryLayout:'grid',readerBackground:'gray',textScale:1 };

export interface UsageSummary {entitlements:Entitlements;timezone:string;start_date:string;end_date:string;generated_at:string;delivered:number;free_delivered:number;included_delivered:number;by_mode:Record<string,number>;quota_used:Record<string,number>;days:{date:string;delivered:number;classic:number;redraw:number}[];}
export interface SubmissionSummary {id:string;status:string;created_at:string;mode:Mode;target_language:string;quota_pages:number;page_count:number;counts?:Record<string,number>;job_ids?:string[];asset_ids?:string[];}
export interface Paginated<T>{items:T[];total:number;next_offset:number|null;}
export type FeedbackIssue='missing_text'|'meaning'|'typesetting'|'art_changed'|'other';
export interface FeedbackRecord {id:string;job_id:string;output_asset_id:string;issues:FeedbackIssue[];comment:string;status:'received'|'reviewing'|'resolved';created_at:string;updated_at:string;}
export const statusLabels: Record<JobStatus, string> = { awaiting_upload:'等待原图上传', validating_upload:'校验原图', queued: '服务器排队', running: '处理中', succeeded: '已完成', no_text: '未检测到文字', failed: '处理失败', cancelled: '已取消', outcome_unknown: '结果待核实',unknown_released:'核实期限已结束' };
export const modeLabels: Record<Mode, string> = { classic: '常规翻译', redraw: 'AI 重绘翻译' };
export const languageLabels:Record<string,string>={ 'zh-Hans':'简体中文','zh-Hant':'繁體中文',en:'English',ja:'日本語',ko:'한국어',fr:'Français',es:'Español','pt-BR':'Português (Brasil)',de:'Deutsch',it:'Italiano',ru:'Русский',pl:'Polski',uk:'Українська',tr:'Türkçe',vi:'Tiếng Việt',id:'Bahasa Indonesia' };
export const languageLabel=(id:string)=>languageLabels[id]??id;
export const phaseLabels: Record<string, string> = { queued: '等待处理', preprocessing: '准备原图', detecting_ocr: '识别漫画文字', translating_text: '翻译对白', inpainting_rendering: '清理原文并排版', validating_upload: '检查译图', calling_image_model: '图片模型翻译中', recovering_local: '恢复处理进度' };

export const fallbackLanguages = Object.entries(languageLabels).map(([id,label])=>({id,label}));
export const supportsLanguage=(caps:Capabilities|undefined,mode:Mode,language:string)=>caps?.modes.find(m=>m.id===mode)?.languages?.includes(language)??(mode==='classic'?language in languageLabels:['zh-Hans','zh-Hant','en','ja','ko'].includes(language));
