import type { Locale } from './types';

interface GuidePresentation {
  workflows: string; reference: string; intro: string; screenshots: string; enlarge: string;
}

export const guidePresentation: Record<Locale, GuidePresentation> = {
  'zh-CN': { workflows: '从你想做的事开始', reference: '深入了解与问题排查', intro: '跟着真实界面，一次完成一个阅读任务。', screenshots: '截图来自真实桌面插件，提供中、日、韩、英四版；漫画样张为项目原创。连接表单仅展示设置入口，不代表已连接服务。', enlarge: '查看大图' },
  'zh-TW': { workflows: '從你想做的事開始', reference: '深入了解與問題排查', intro: '跟著真實介面，一次完成一個閱讀任務。', screenshots: '截圖來自真實桌面擴充功能，提供中、日、韓、英四版；漫畫樣張為專案原創。連線表單僅展示設定入口，不代表已連線服務。', enlarge: '檢視大圖' },
  en: { workflows: 'Start with what you want to do', reference: 'Details & troubleshooting', intro: 'Real screens. One complete reading workflow at a time.', screenshots: 'Real desktop extension captures in Chinese, Japanese, Korean and English, with an original sample comic. Connection forms show setup, not a verified service connection.', enlarge: 'View full size' },
  ja: { workflows: 'やりたいことから始める', reference: '詳しい説明とトラブル対処', intro: '実際の画面を見ながら、ひとつずつ操作を進めましょう。', screenshots: '実際のデスクトップ拡張機能を中国語・日本語・韓国語・英語で撮影しています。見本の漫画は本プロジェクトのオリジナルです。接続フォームは設定画面の紹介であり、接続成功の実証ではありません。', enlarge: '画像を拡大' },
  ko: { workflows: '원하는 작업부터 시작하세요', reference: '상세 안내 및 문제 해결', intro: '실제 화면을 보며 한 번에 하나의 읽기 작업을 완성하세요.', screenshots: '실제 데스크톱 확장 프로그램의 중국어, 일본어, 한국어, 영어 화면입니다. 예제 만화는 프로젝트의 창작물입니다. 연결 양식은 설정 화면이며 서비스 연결 성공을 의미하지 않습니다.', enlarge: '크게 보기' },
  fr: { workflows: 'Commencez par votre objectif', reference: 'Pour aller plus loin et dépanner', intro: 'Des écrans réels pour suivre chaque parcours de lecture.', screenshots: 'Captures réelles en chinois, japonais, coréen et anglais, avec une BD originale du projet. Les formulaires illustrent la configuration, pas une connexion validée. Cette page utilise les captures anglaises.', enlarge: 'Agrandir' },
  es: { workflows: 'Empieza por lo que quieres hacer', reference: 'Más información y soluciones', intro: 'Pantallas reales para completar cada tarea de lectura.', screenshots: 'Capturas reales en chino, japonés, coreano e inglés con un cómic original del proyecto. Los formularios muestran la configuración, no una conexión verificada. Esta página usa capturas en inglés.', enlarge: 'Ver imagen completa' },
  'pt-BR': { workflows: 'Comece pelo que deseja fazer', reference: 'Detalhes e solução de problemas', intro: 'Telas reais para concluir uma tarefa de leitura por vez.', screenshots: 'Capturas reais em chinês, japonês, coreano e inglês com quadrinhos originais do projeto. Os formulários mostram a configuração, não uma conexão validada. Esta página usa capturas em inglês.', enlarge: 'Ampliar imagem' },
  de: { workflows: 'Beginne mit deinem Vorhaben', reference: 'Hintergründe und Problemlösung', intro: 'Echte Ansichten, ein vollständiger Leseablauf nach dem anderen.', screenshots: 'Echte Aufnahmen auf Chinesisch, Japanisch, Koreanisch und Englisch mit einem eigenen Beispielcomic. Verbindungsformulare zeigen die Einrichtung, keine bestätigte Verbindung. Hier werden englische Aufnahmen verwendet.', enlarge: 'In voller Größe ansehen' },
  it: { workflows: 'Inizia da ciò che vuoi fare', reference: 'Approfondimenti e risoluzione dei problemi', intro: 'Schermate reali per completare un percorso di lettura alla volta.', screenshots: 'Schermate reali in cinese, giapponese, coreano e inglese, con un fumetto originale del progetto. I moduli mostrano la configurazione, non una connessione verificata. Qui le schermate sono in inglese.', enlarge: 'Ingrandisci' },
  ru: { workflows: 'Начните со своей задачи', reference: 'Подробности и решение проблем', intro: 'Настоящие экраны для каждого этапа чтения.', screenshots: 'Снимки реального расширения на китайском, японском, корейском и английском с оригинальным комиксом проекта. Формы показывают настройку, а не успешное подключение. Здесь используются английские снимки.', enlarge: 'Открыть в полном размере' },
  pl: { workflows: 'Zacznij od swojego celu', reference: 'Szczegóły i rozwiązywanie problemów', intro: 'Prawdziwe ekrany, jeden kompletny proces czytania naraz.', screenshots: 'Zrzuty prawdziwego rozszerzenia po chińsku, japońsku, koreańsku i angielsku z autorskim komiksem projektu. Formularze pokazują konfigurację, nie potwierdzone połączenie. Tutaj używamy zrzutów angielskich.', enlarge: 'Pokaż pełny rozmiar' },
  uk: { workflows: 'Почніть зі свого завдання', reference: 'Подробиці та усунення проблем', intro: 'Справжні екрани для кожного етапу читання.', screenshots: 'Знімки справжнього розширення китайською, японською, корейською й англійською з оригінальним коміксом проєкту. Форми показують налаштування, не успішне підключення. Тут використано англійські знімки.', enlarge: 'Відкрити повний розмір' },
  tr: { workflows: 'Yapmak istediğiniz işle başlayın', reference: 'Ayrıntılar ve sorun giderme', intro: 'Gerçek ekranlarla her okuma işlemini adım adım tamamlayın.', screenshots: 'Projenin özgün çizgi romanıyla Çince, Japonca, Korece ve İngilizce gerçek uzantı ekranları. Bağlantı formları kurulumu gösterir, başarılı bağlantıyı doğrulamaz. Bu sayfa İngilizce ekranları kullanır.', enlarge: 'Tam boyutta görüntüle' },
  vi: { workflows: 'Bắt đầu từ việc bạn muốn làm', reference: 'Tìm hiểu thêm và xử lý sự cố', intro: 'Làm theo giao diện thật để hoàn thành từng thao tác đọc.', screenshots: 'Ảnh chụp tiện ích thật bằng tiếng Trung, Nhật, Hàn và Anh, dùng truyện mẫu do dự án sáng tạo. Biểu mẫu chỉ minh họa cài đặt, không chứng minh đã kết nối dịch vụ. Trang này dùng ảnh tiếng Anh.', enlarge: 'Xem ảnh lớn' },
  id: { workflows: 'Mulai dari yang ingin Anda lakukan', reference: 'Detail dan pemecahan masalah', intro: 'Ikuti layar nyata untuk menyelesaikan satu alur membaca setiap kali.', screenshots: 'Tangkapan ekstensi asli dalam bahasa Mandarin, Jepang, Korea, dan Inggris dengan komik orisinal proyek. Formulir menunjukkan pengaturan, bukan koneksi yang terverifikasi. Halaman ini memakai tangkapan bahasa Inggris.', enlarge: 'Lihat ukuran penuh' },
  ar: { workflows: 'ابدأ بما تريد القيام به', reference: 'تفاصيل وحلول للمشكلات', intro: 'اتبع الشاشات الحقيقية لإتمام كل مهمة قراءة خطوة بخطوة.', screenshots: 'لقطات حقيقية للإضافة بالصينية واليابانية والكورية والإنجليزية مع قصة أصلية للمشروع. تعرض النماذج الإعدادات ولا تثبت نجاح الاتصال. تستخدم هذه الصفحة اللقطات الإنجليزية.', enlarge: 'عرض بالحجم الكامل' },
};
