import type {Locale} from './types';

// One vocabulary for pricing, account balances and the actual charging order.
const labels:Record<Locale,[string,string,string,string,string,string,string]>={
  'zh-CN':["免费额度","订阅额度","{0} 页 / 月","免费模型先扣免费额度，用完后扣订阅额度，再扣购买额度。高级模型仅扣订阅或购买额度；可用额度耗尽后停止受理。","季付和年付均按月发放，未用订阅额度不结转；请求频率与服务容量限制仍生效。","100 页 / 滚动分钟","订阅额度用完后可扣购买额度；购买额度有效期仍继续计算。"],
  'zh-TW':["免費額度","訂閱額度","{0} 頁 / 月","免費模型先扣免費額度，用完後扣訂閱額度，再扣購買額度。進階模型僅扣訂閱或購買額度；可用額度耗盡後停止受理。","季付和年付均按月發放，未用訂閱額度不累積；請求頻率與服務容量限制仍生效。","100 頁 / 滾動分鐘","訂閱額度用完後可扣購買額度；購買額度有效期仍繼續計算。"],
  en:["Free allowance","Subscription allowance","{0} pages / month","Free models use free pages first, then subscription pages, then purchased pages. Advanced models use only subscription or purchased pages. New work stops when eligible pages run out.","Quarterly and annual subscriptions grant pages monthly, without rollover. Request and service capacity limits still apply.","100 pages / rolling minute","Purchased pages can be used after subscription pages run out; their expiry dates still apply."],
  ja:["無料枠","購読枠","{0} ページ / 月","無料モデルは無料枠、購読枠、購入ページの順に消費します。上位モデルは購読枠または購入ページのみ使用します。利用可能な枠を使い切ると新規受付を停止します。","3か月払いも年払いも毎月付与、繰り越しなし。受付頻度とサービス容量の制限は引き続き適用されます。","直近1分で100ページ","購読枠を使い切ると購入ページを使用できます。有効期限は延長されません。"],
  ko:["무료 한도","구독 한도","{0}페이지 / 월","무료 모델은 무료, 구독, 구매 페이지 순으로 차감합니다. 고급 모델은 구독 또는 구매 페이지만 사용합니다. 사용 가능한 페이지가 없으면 새 작업을 접수하지 않습니다.","분기 및 연간 구독 모두 매월 지급되며 이월되지 않습니다. 요청 빈도와 서비스 용량 제한은 계속 적용됩니다.","최근 1분 동안 100페이지","구독 페이지 소진 후 구매 페이지를 사용할 수 있으며 유효기간은 계속 적용됩니다."],
  fr:["Quota gratuit","Quota d’abonnement","{0} pages / mois","Les modèles gratuits utilisent d’abord le quota gratuit, puis celui de l’abonnement, puis les pages achetées. Les modèles avancés utilisent uniquement l’abonnement ou les pages achetées. Sans quota admissible, les nouvelles tâches sont bloquées.","Les abonnements trimestriels et annuels attribuent les pages chaque mois, sans report. Les limites de fréquence et de capacité restent applicables.","100 pages / minute glissante","Les pages achetées peuvent être utilisées après épuisement du quota d’abonnement ; leur expiration reste applicable."],
  es:["Cuota gratuita","Cuota de suscripción","{0} páginas / mes","Los modelos gratuitos consumen primero la cuota gratuita, luego la de suscripción y después las páginas compradas. Los avanzados solo consumen suscripción o páginas compradas. Sin cuota válida, no se aceptan tareas nuevas.","Las suscripciones trimestrales y anuales asignan páginas cada mes, sin acumulación. Se mantienen los límites de frecuencia y capacidad.","100 páginas / minuto móvil","Las páginas compradas se pueden usar al agotar la cuota de suscripción; su caducidad sigue vigente."],
  'pt-BR':["Cota gratuita","Cota da assinatura","{0} páginas / mês","Modelos gratuitos usam primeiro a cota gratuita, depois a assinatura e por fim páginas compradas. Modelos avançados usam apenas assinatura ou páginas compradas. Sem saldo elegível, novas tarefas são bloqueadas.","Assinaturas trimestrais e anuais liberam páginas mensalmente, sem acúmulo. Limites de frequência e capacidade continuam valendo.","100 páginas / minuto móvel","Páginas compradas podem ser usadas após esgotar a cota da assinatura; a validade continua valendo."],
  de:["Kostenloses Kontingent","Abo-Kontingent","{0} Seiten / Monat","Kostenlose Modelle nutzen zuerst das kostenlose Kontingent, dann Abo-Seiten und danach gekaufte Seiten. Erweiterte Modelle nutzen nur Abo- oder gekaufte Seiten. Ohne verfügbares Kontingent werden keine neuen Aufgaben angenommen.","Quartals- und Jahresabos vergeben Seiten monatlich, ohne Übertrag. Anfrage- und Kapazitätsgrenzen gelten weiterhin.","100 Seiten / rollierender Minute","Nach Verbrauch des Abo-Kontingents können gekaufte Seiten genutzt werden; ihre Ablaufdaten gelten weiterhin."],
  it:["Quota gratuita","Quota abbonamento","{0} pagine / mese","I modelli gratuiti consumano prima la quota gratuita, poi quella dell’abbonamento e infine le pagine acquistate. I modelli avanzati usano solo abbonamento o pagine acquistate. Senza quota utilizzabile, le nuove attività vengono bloccate.","Gli abbonamenti trimestrali e annuali assegnano pagine mensilmente, senza riporto. Restano i limiti di frequenza e capacità.","100 pagine / minuto mobile","Le pagine acquistate si possono usare dopo aver esaurito la quota dell’abbonamento; la scadenza resta invariata."],
  ru:["Бесплатный лимит","Лимит подписки","{0} страниц / месяц","Бесплатные модели сначала расходуют бесплатный лимит, затем подписку, затем купленные страницы. Продвинутые модели расходуют только подписку или купленные страницы. Без доступного лимита новые задачи не принимаются.","Квартальные и годовые подписки начисляют страницы ежемесячно, без переноса остатка. Ограничения частоты и мощности сервиса сохраняются.","100 страниц за скользящую минуту","Купленные страницы доступны после исчерпания лимита подписки; срок их действия не продлевается."],
  pl:["Darmowy limit","Limit subskrypcji","{0} stron / miesiąc","Darmowe modele zużywają kolejno darmowy limit, limit subskrypcji i kupione strony. Zaawansowane modele korzystają tylko z subskrypcji lub kupionych stron. Po wyczerpaniu dostępnych stron nowe zadania są blokowane.","Subskrypcje kwartalne i roczne przyznają strony co miesiąc, bez przenoszenia. Nadal obowiązują limity częstotliwości i wydajności.","100 stron / ruchoma minuta","Kupione strony można wykorzystać po wyczerpaniu limitu subskrypcji; ich termin ważności pozostaje bez zmian."],
  uk:["Безкоштовний ліміт","Ліміт підписки","{0} сторінок / місяць","Безкоштовні моделі спершу витрачають безкоштовний ліміт, потім підписку, потім куплені сторінки. Розширені моделі використовують лише підписку або куплені сторінки. Без доступного ліміту нові завдання не приймаються.","Квартальні й річні підписки нараховують сторінки щомісяця без перенесення залишку. Обмеження частоти й потужності залишаються.","100 сторінок за ковзну хвилину","Куплені сторінки доступні після вичерпання ліміту підписки; їхній строк дії не подовжується."],
  tr:["Ücretsiz kota","Abonelik kotası","{0} sayfa / ay","Ücretsiz modeller önce ücretsiz kotayı, ardından abonelik ve satın alınan sayfaları kullanır. Gelişmiş modeller yalnızca abonelik veya satın alınan sayfaları kullanır. Kullanılabilir kota bitince yeni görev alınmaz.","Üç aylık ve yıllık aboneliklerde sayfalar aylık verilir, devretmez. İstek sıklığı ve hizmet kapasitesi sınırları geçerlidir.","Kayan dakikada 100 sayfa","Abonelik kotası bitince satın alınan sayfalar kullanılabilir; son kullanma tarihleri geçerli kalır."],
  vi:["Hạn mức miễn phí","Hạn mức thuê bao","{0} trang / tháng","Mô hình miễn phí dùng hạn mức miễn phí trước, rồi thuê bao, rồi trang đã mua. Mô hình nâng cao chỉ dùng thuê bao hoặc trang đã mua. Hết hạn mức phù hợp thì ngừng nhận tác vụ mới.","Thuê bao quý và năm cấp trang hàng tháng, không cộng dồn. Giới hạn tần suất và năng lực dịch vụ vẫn áp dụng.","100 trang / phút trượt","Có thể dùng trang đã mua sau khi hết hạn mức thuê bao; ngày hết hạn vẫn áp dụng."],
  id:["Kuota gratis","Kuota langganan","{0} halaman / bulan","Model gratis memakai kuota gratis terlebih dahulu, lalu langganan, lalu halaman yang dibeli. Model lanjutan hanya memakai langganan atau halaman yang dibeli. Tugas baru dihentikan jika kuota yang sesuai habis.","Langganan triwulanan dan tahunan memberi halaman setiap bulan tanpa akumulasi. Batas frekuensi dan kapasitas tetap berlaku.","100 halaman / menit bergulir","Halaman yang dibeli dapat digunakan setelah kuota langganan habis; masa berlakunya tetap berjalan."],
  ar:["الحصة المجانية","حصة الاشتراك","{0} صفحة / شهر","تستهلك النماذج المجانية الحصة المجانية أولاً، ثم حصة الاشتراك، ثم الصفحات المشتراة. تستهلك النماذج المتقدمة الاشتراك أو الصفحات المشتراة فقط. يتوقف قبول المهام الجديدة عند نفاد الحصة المتاحة.","تمنح الاشتراكات ربع السنوية والسنوية صفحات كل شهر دون ترحيل. تبقى حدود الطلبات وسعة الخدمة سارية.","100 صفحة خلال دقيقة متحركة","يمكن استخدام الصفحات المشتراة بعد نفاد حصة الاشتراك؛ وتبقى تواريخ انتهائها سارية."],
};
export function subscriptionQuotaCopy(locale:string){
  const [free,subscription,monthly,rule,renewal,paidRate,packRule]=labels[locale as Locale]??labels.en;
  return {free,subscription,monthly,rule,renewal,paidRate,packRule};
}
