import type {Locale} from './locales';
export interface ModelCopy {label:string;automatic:string;free:string;paid:string;available:string;unavailable:string;not_allowed:string;quota_exhausted:string;temporary:string;hint:string;actual:string;upgrade:string;retranslate:string;}
export const modelCopy:Record<Locale,ModelCopy> = {
  "zh-CN": {"free":"免费","paid":"付费权益","label":"翻译模型","automatic":"自动选择（默认）","available":"可用","unavailable":"不可用","not_allowed":"当前权益不支持","quota_exhausted":"可用额度不足","temporary":"模型暂不可用","hint":"更换模型仅影响新任务；已有译图需手动重新翻译。","actual":"实际模型：{0}","upgrade":"升级","retranslate":"重新翻译"},
  "zh-TW": {"free":"免費","paid":"付費權益","label":"翻譯模型","automatic":"自動選擇（預設）","available":"可用","unavailable":"不可用","not_allowed":"目前權益不支援","quota_exhausted":"可用額度不足","temporary":"模型暫不可用","hint":"更換模型僅影響新任務；已有譯圖需手動重新翻譯。","actual":"實際模型：{0}","upgrade":"升級","retranslate":"重新翻譯"},
  "en": {"free":"Free","paid":"Paid access","label":"Translation model","automatic":"Automatic (default)","available":"Available","unavailable":"Unavailable","not_allowed":"Not included in your access","quota_exhausted":"Insufficient quota","temporary":"Model temporarily unavailable","hint":"Changing models affects new tasks only. Retranslate existing results manually.","actual":"Actual model: {0}","upgrade":"Upgrade","retranslate":"Retranslate"},
  "ja": {"free":"無料","paid":"有料プラン","label":"翻訳モデル","automatic":"自動選択（デフォルト）","available":"利用可能","unavailable":"利用不可","not_allowed":"現在の利用権限では使えません","quota_exhausted":"利用枠が不足しています","temporary":"モデルは一時的に利用できません","hint":"モデルの変更は新規タスクにのみ適用されます。既存の結果は手動で再翻訳してください。","actual":"使用モデル：{0}","upgrade":"アップグレード","retranslate":"再翻訳"},
  "ko": {"free":"무료","paid":"유료 이용","label":"번역 모델","automatic":"자동 선택(기본값)","available":"사용 가능","unavailable":"사용 불가","not_allowed":"현재 이용 권한에 포함되지 않음","quota_exhausted":"사용 가능한 할당량 부족","temporary":"모델을 일시적으로 사용할 수 없음","hint":"모델 변경은 새 작업에만 적용됩니다. 기존 결과는 직접 다시 번역하세요.","actual":"사용 모델: {0}","upgrade":"업그레이드","retranslate":"다시 번역"},
  "fr": {"free":"Gratuit","paid":"Accès payant","label":"Modèle de traduction","automatic":"Automatique (par défaut)","available":"Disponible","unavailable":"Indisponible","not_allowed":"Non inclus dans vos droits","quota_exhausted":"Quota insuffisant","temporary":"Modèle temporairement indisponible","hint":"Le changement de modèle ne concerne que les nouvelles tâches. Retraduisez manuellement les résultats existants.","actual":"Modèle utilisé : {0}","upgrade":"Mettre à niveau","retranslate":"Retraduire"},
  "es": {"free":"Gratis","paid":"Acceso de pago","label":"Modelo de traducción","automatic":"Automático (predeterminado)","available":"Disponible","unavailable":"No disponible","not_allowed":"No incluido en tu acceso","quota_exhausted":"Cuota insuficiente","temporary":"Modelo temporalmente no disponible","hint":"El cambio de modelo solo afecta a tareas nuevas. Vuelve a traducir manualmente los resultados existentes.","actual":"Modelo utilizado: {0}","upgrade":"Mejorar plan","retranslate":"Volver a traducir"},
  "pt-BR": {"free":"Grátis","paid":"Acesso pago","label":"Modelo de tradução","automatic":"Automático (padrão)","available":"Disponível","unavailable":"Indisponível","not_allowed":"Não incluído no seu acesso","quota_exhausted":"Cota insuficiente","temporary":"Modelo temporariamente indisponível","hint":"A mudança de modelo afeta apenas novas tarefas. Traduza novamente os resultados existentes manualmente.","actual":"Modelo utilizado: {0}","upgrade":"Fazer upgrade","retranslate":"Traduzir novamente"},
  "de": {"free":"Kostenlos","paid":"Kostenpflichtig","label":"Übersetzungsmodell","automatic":"Automatisch (Standard)","available":"Verfügbar","unavailable":"Nicht verfügbar","not_allowed":"Nicht in Ihrem Zugang enthalten","quota_exhausted":"Kontingent reicht nicht aus","temporary":"Modell vorübergehend nicht verfügbar","hint":"Ein Modellwechsel gilt nur für neue Aufgaben. Vorhandene Ergebnisse müssen manuell neu übersetzt werden.","actual":"Verwendetes Modell: {0}","upgrade":"Upgrade","retranslate":"Neu übersetzen"},
  "it": {"free":"Gratis","paid":"Accesso a pagamento","label":"Modello di traduzione","automatic":"Automatico (predefinito)","available":"Disponibile","unavailable":"Non disponibile","not_allowed":"Non incluso nel tuo accesso","quota_exhausted":"Quota insufficiente","temporary":"Modello temporaneamente non disponibile","hint":"Il cambio di modello riguarda solo le nuove attività. Ritraduci manualmente i risultati esistenti.","actual":"Modello utilizzato: {0}","upgrade":"Upgrade","retranslate":"Ritraduci"},
  "ru": {"free":"Бесплатно","paid":"Платный доступ","label":"Модель перевода","automatic":"Автоматически (по умолчанию)","available":"Доступна","unavailable":"Недоступна","not_allowed":"Не входит в ваши права доступа","quota_exhausted":"Недостаточно квоты","temporary":"Модель временно недоступна","hint":"Смена модели влияет только на новые задания. Существующие результаты нужно перевести заново вручную.","actual":"Использованная модель: {0}","upgrade":"Улучшить план","retranslate":"Перевести заново"},
  "pl": {"free":"Bezpłatny","paid":"Płatny dostęp","label":"Model tłumaczenia","automatic":"Automatycznie (domyślnie)","available":"Dostępny","unavailable":"Niedostępny","not_allowed":"Poza Twoimi uprawnieniami","quota_exhausted":"Niewystarczający limit","temporary":"Model tymczasowo niedostępny","hint":"Zmiana modelu dotyczy tylko nowych zadań. Istniejące wyniki przetłumacz ponownie ręcznie.","actual":"Użyty model: {0}","upgrade":"Ulepsz plan","retranslate":"Przetłumacz ponownie"},
  "uk": {"free":"Безкоштовно","paid":"Платний доступ","label":"Модель перекладу","automatic":"Автоматично (типово)","available":"Доступна","unavailable":"Недоступна","not_allowed":"Не входить до ваших прав доступу","quota_exhausted":"Недостатньо квоти","temporary":"Модель тимчасово недоступна","hint":"Зміна моделі впливає лише на нові завдання. Наявні результати потрібно перекласти заново вручну.","actual":"Використана модель: {0}","upgrade":"Покращити план","retranslate":"Перекласти заново"},
  "tr": {"free":"Ücretsiz","paid":"Ücretli erişim","label":"Çeviri modeli","automatic":"Otomatik (varsayılan)","available":"Kullanılabilir","unavailable":"Kullanılamaz","not_allowed":"Mevcut haklarınıza dahil değil","quota_exhausted":"Yetersiz kota","temporary":"Model geçici olarak kullanılamıyor","hint":"Model değişikliği yalnızca yeni görevleri etkiler. Mevcut sonuçları elle yeniden çevirin.","actual":"Kullanılan model: {0}","upgrade":"Yükselt","retranslate":"Yeniden çevir"},
  "vi": {"free":"Miễn phí","paid":"Quyền trả phí","label":"Mô hình dịch","automatic":"Tự động (mặc định)","available":"Khả dụng","unavailable":"Không khả dụng","not_allowed":"Không thuộc quyền sử dụng hiện tại","quota_exhausted":"Không đủ hạn mức","temporary":"Mô hình tạm thời không khả dụng","hint":"Đổi mô hình chỉ áp dụng cho tác vụ mới. Hãy dịch lại thủ công các kết quả hiện có.","actual":"Mô hình đã dùng: {0}","upgrade":"Nâng cấp","retranslate":"Dịch lại"},
  "id": {"free":"Gratis","paid":"Akses berbayar","label":"Model terjemahan","automatic":"Otomatis (default)","available":"Tersedia","unavailable":"Tidak tersedia","not_allowed":"Tidak termasuk dalam hak akses Anda","quota_exhausted":"Kuota tidak cukup","temporary":"Model sementara tidak tersedia","hint":"Perubahan model hanya berlaku untuk tugas baru. Terjemahkan ulang hasil yang ada secara manual.","actual":"Model yang digunakan: {0}","upgrade":"Tingkatkan","retranslate":"Terjemahkan ulang"},
  "ar": {"free":"مجاني","paid":"مدفوع","label":"نموذج الترجمة","automatic":"تلقائي (افتراضي)","available":"متاح","unavailable":"غير متاح","not_allowed":"غير مشمول بصلاحياتك الحالية","quota_exhausted":"الحصة المتاحة غير كافية","temporary":"النموذج غير متاح مؤقتًا","hint":"يؤثر تغيير النموذج على المهام الجديدة فقط. أعد ترجمة النتائج الحالية يدويًا.","actual":"النموذج المستخدم: {0}","upgrade":"ترقية","retranslate":"إعادة الترجمة"},
};
