import type {Locale} from './types';
const en={title:'Translate manga images',intro:'Choose an image. Read it in your language.',select:'Choose images',drop:'Drop images here, or paste from your clipboard',formats:'JPG, PNG, WebP · Up to 32 MiB each · 10 images at a time',start:'Start translation',history:'Local history',empty:'Your images will appear here.',language:'Translate into',mode:'Translation mode',classic:'Standard',redraw:'AI redraw',original:'Original',translated:'Translated',compare:'Side by side',download:'Download translation',remove:'Delete local record',confirmDelete:'Delete this local image and translation? This cannot be undone.',retry:'Retry failed image',regenerate:'Translate again',confirmAgain:'Create a new translation? This uses your translation allowance again.',resume:'Resume',login:'Sign in',guest:'Guest experience',remaining:'Remaining today',account:'Account allowance',unlimited:'Unlimited',local:'History stays in this browser, not across devices. Clearing site data removes it. Download images you want to keep.',retention:'Guest results are available on the server for 24 hours. Daily trials count accepted tasks, including failures; shared networks share a limit.',disabled:'Guest trials are not available right now. Sign in to use your account allowance.',verify:'Complete verification to continue',draft:'Ready',preparing:'Preparing image',needs_input:'Uploading',queued:'Queued',running:'Translating',succeeded:'Complete',failed:'Failed',needs_attention:'Outcome needs checking — do not resubmit',paused:'Paused — resume to check the same task',busy:'Working…',storage:'Local storage',cancel:'Stop adding images',network:'Connection interrupted. Resume to check the existing task.',invalid:'Choose up to 10 JPG, PNG or WebP images, each no larger than 32 MiB.',dimensions:'This image exceeds the supported dimensions. Long images are not split automatically.',full:'Local storage is full or unavailable. Delete old local records or allow site storage, then resume. No new task was submitted automatically.',quota:'Guest trials are exhausted or busy on this network. Sign in, or try again later.',expired:'This session or result has expired. Saved local translations remain available.',auth:'Your login has expired or changed. Sign in again before resuming.',processing:'Image processing failed. The file may be damaged or too large for this browser.',generic:'Unable to complete this action. Please try again.',noText:'No text found',partial:'Some text could not be translated',newImages:'Add images',open:'Open translator',guestHistory:'Guest history',myHistory:'My history',fit:'Fit width',verifyFailed:'Verification failed or expired. Try again.',saveDownload:'The translation could not be saved locally. Download it now; resume later to retry saving.'};
type Copy=typeof en;
const baseCopy:Record<Locale,Copy>={en,
'zh-CN':{title:'漫画图片，上传即翻译',intro:'选择图片，用熟悉的语言继续阅读。',select:'选择图片',drop:'或将图片拖到这里，也支持粘贴',formats:'JPG、PNG、WebP · 每张最大 32 MiB · 一次最多 10 张',start:'开始翻译',history:'本地历史',empty:'选择图片后，在这里开始翻译。',language:'翻译为',mode:'翻译模式',classic:'常规翻译',redraw:'AI 重绘',original:'原图',translated:'译图',compare:'并排对照',download:'下载完整译图',remove:'删除本地记录',confirmDelete:'删除这张图片及其本地译图？此操作无法撤销。',retry:'重试失败图片',regenerate:'重新翻译',confirmAgain:'生成新的翻译结果？将再次使用翻译额度。',resume:'恢复任务',login:'登录',guest:'匿名体验',remaining:'今日剩余次数',account:'账户可用额度',unlimited:'不限量',local:'历史仅保存在当前浏览器，不跨设备同步。清理网站数据后将丢失，请及时下载需要保留的图片。',retention:'匿名服务器结果保留 24 小时。每日体验按已受理任务计次，失败也计次；同一网络共享限制。',disabled:'匿名体验暂未开放，登录后可使用账户额度。',verify:'请完成验证以继续',draft:'待翻译',preparing:'处理图片中',needs_input:'上传中',queued:'排队中',running:'翻译中',succeeded:'已完成',failed:'失败',needs_attention:'结果待核实，请勿重复提交',paused:'已暂停，恢复时会核实原任务',busy:'处理中…',storage:'本地占用',cancel:'停止新增',network:'连接中断，恢复后将核实原任务。',invalid:'请选择 JPG、PNG 或 WebP，每张不超过 32 MiB，一次最多 10 张。',dimensions:'图片尺寸超出限制；过长图片不会自动切片。',full:'本地空间不足或存储不可用。请删除旧记录或允许网站存储，再恢复任务；不会自动新建翻译。',quota:'当前网络匿名次数已用完或体验繁忙，请登录或稍后重试。',expired:'会话或服务器结果已过期，已保存的本地译图仍可查看。',auth:'登录已失效或账户已改变，请重新登录后恢复。',processing:'图片处理失败，文件可能损坏或超出浏览器处理能力。',generic:'操作未完成，请重试。',noText:'未发现文字',partial:'部分文字未能翻译',newImages:'添加图片',open:'进入翻译页面',guestHistory:'游客历史',myHistory:'我的历史',fit:'适合宽度',verifyFailed:'验证失败或已过期，请重新验证。',saveDownload:'译图未能保存到本地，请立即下载；稍后恢复任务可重试保存。'},
'zh-TW':{title:'漫畫圖片，上傳即翻譯',intro:'選擇圖片，用熟悉的語言繼續閱讀。',select:'選擇圖片',drop:'或將圖片拖到這裡，也支援貼上',formats:'JPG、PNG、WebP · 每張最大 32 MiB · 一次最多 10 張',start:'開始翻譯',history:'本機歷史',empty:'選擇圖片後，在這裡開始翻譯。',language:'翻譯為',mode:'翻譯模式',classic:'一般翻譯',redraw:'AI 重繪',original:'原圖',translated:'譯圖',compare:'並排對照',download:'下載完整譯圖',remove:'刪除本機紀錄',confirmDelete:'刪除此圖片與本機譯圖？此操作無法復原。',retry:'重試失敗圖片',regenerate:'重新翻譯',confirmAgain:'產生新的翻譯結果？將再次使用翻譯額度。',resume:'恢復任務',login:'登入',guest:'匿名體驗',remaining:'今日剩餘次數',account:'帳戶可用額度',unlimited:'不限量',local:'歷史僅儲存在目前瀏覽器，不跨裝置同步。清除網站資料後將遺失，請下載需要保留的圖片。',retention:'匿名伺服器結果保留 24 小時。每日體驗按已受理任務計次，失敗也計次；同一網路共用限制。',disabled:'匿名體驗暫未開放，登入後可使用帳戶額度。',verify:'請完成驗證以繼續',draft:'待翻譯',preparing:'處理圖片中',needs_input:'上傳中',queued:'排隊中',running:'翻譯中',succeeded:'已完成',failed:'失敗',needs_attention:'結果待確認，請勿重複提交',paused:'已暫停，恢復時會確認原任務',busy:'處理中…',storage:'本機用量',cancel:'停止新增',network:'連線中斷，恢復後將確認原任務。',invalid:'請選擇 JPG、PNG 或 WebP，每張不超過 32 MiB，一次最多 10 張。',dimensions:'圖片尺寸超出限制；過長圖片不會自動切片。',full:'本機空間不足或儲存不可用。請刪除舊紀錄或允許網站儲存，再恢復任務。',quota:'目前網路匿名次數已用完或體驗繁忙，請登入或稍後重試。',expired:'工作階段或伺服器結果已過期，已儲存的本機譯圖仍可查看。',auth:'登入已失效或帳戶已變更，請重新登入後恢復。',processing:'圖片處理失敗，檔案可能損壞或超出瀏覽器處理能力。',generic:'操作未完成，請重試。',noText:'未發現文字',partial:'部分文字未能翻譯',newImages:'新增圖片',open:'進入翻譯頁面',guestHistory:'訪客歷史',myHistory:'我的歷史',fit:'符合寬度',verifyFailed:'驗證失敗或已過期，請重新驗證。',saveDownload:'譯圖未能儲存，請立即下載；稍後恢復任務可重試儲存。'},
ja:{title:'漫画画像を、そのまま翻訳',intro:'画像を選んで、読みたい言語で楽しもう。',select:'画像を選ぶ',drop:'ここにドロップ、または画像を貼り付け',formats:'JPG・PNG・WebP · 1枚32 MiBまで · 一度に10枚まで',start:'翻訳を開始',history:'ローカル履歴',empty:'画像を選んで翻訳を始めましょう。',language:'翻訳先',mode:'翻訳モード',classic:'通常翻訳',redraw:'AI再描画',original:'原画像',translated:'翻訳画像',compare:'並べて比較',download:'翻訳画像を保存',remove:'ローカル履歴を削除',confirmDelete:'この画像と翻訳を削除しますか？元に戻せません。',retry:'失敗した画像を再試行',regenerate:'もう一度翻訳',confirmAgain:'新しい翻訳を作成しますか？利用枠を再度使用します。',resume:'再開',login:'ログイン',guest:'ゲスト体験',remaining:'本日の残り回数',account:'アカウントの利用枠',unlimited:'無制限',local:'履歴はこのブラウザーのみに保存されます。サイトデータを削除すると失われます。必要な画像はダウンロードしてください。',retention:'ゲストのサーバー結果は24時間保存。失敗も受付回数に含まれ、同一ネットワークで上限を共有します。',disabled:'ゲスト体験は現在利用できません。ログインしてご利用ください。',verify:'認証を完了してください',draft:'準備完了',preparing:'画像を処理中',needs_input:'アップロード中',queued:'待機中',running:'翻訳中',succeeded:'完了',failed:'失敗',needs_attention:'結果を確認中 — 再送信しないでください',paused:'一時停止 — 再開時に元のタスクを確認します',busy:'処理中…',storage:'保存容量',cancel:'新規処理を停止',network:'接続が切れました。再開して元のタスクを確認してください。',invalid:'JPG・PNG・WebPを10枚まで、1枚32 MiB以下で選択してください。',dimensions:'画像サイズが上限を超えています。長い画像は自動分割しません。',full:'保存領域が不足しているか利用できません。古い履歴を削除するか保存を許可して再開してください。',quota:'このネットワークのゲスト枠が上限に達したか混雑しています。ログインするか後でお試しください。',expired:'セッションまたはサーバー結果の期限が切れました。保存済み画像は閲覧できます。',auth:'ログインが無効になったか変更されました。再度ログインしてください。',processing:'画像処理に失敗しました。破損または大きすぎる可能性があります。',generic:'操作を完了できませんでした。再試行してください。',noText:'文字が見つかりません',partial:'一部の文字を翻訳できませんでした',newImages:'画像を追加',open:'翻訳ページへ',guestHistory:'ゲスト履歴',myHistory:'自分の履歴',fit:'幅に合わせる',verifyFailed:'認証に失敗したか期限が切れました。再試行してください。',saveDownload:'翻訳を保存できませんでした。今すぐダウンロードし、後で保存を再試行してください。'},
ko:{title:'만화 이미지, 올리면 바로 번역',intro:'이미지를 선택하고 익숙한 언어로 읽어 보세요.',select:'이미지 선택',drop:'여기로 끌어 놓거나 이미지를 붙여 넣으세요',formats:'JPG, PNG, WebP · 장당 최대 32 MiB · 한 번에 10장',start:'번역 시작',history:'로컬 기록',empty:'이미지를 선택해 번역을 시작하세요.',language:'번역 언어',mode:'번역 모드',classic:'일반 번역',redraw:'AI 다시 그리기',original:'원본',translated:'번역본',compare:'나란히 비교',download:'번역 이미지 다운로드',remove:'로컬 기록 삭제',confirmDelete:'이 이미지와 로컬 번역본을 삭제할까요? 되돌릴 수 없습니다.',retry:'실패한 이미지 재시도',regenerate:'다시 번역',confirmAgain:'새 번역을 생성할까요? 번역 한도를 다시 사용합니다.',resume:'계속하기',login:'로그인',guest:'비회원 체험',remaining:'오늘 남은 횟수',account:'계정 사용 가능 한도',unlimited:'무제한',local:'기록은 현재 브라우저에만 저장됩니다. 사이트 데이터를 지우면 사라지므로 필요한 이미지는 다운로드하세요.',retention:'비회원 서버 결과는 24시간 보관합니다. 실패도 접수 횟수에 포함되며 같은 네트워크는 한도를 공유합니다.',disabled:'현재 비회원 체험을 사용할 수 없습니다. 로그인 후 계정 한도를 이용하세요.',verify:'인증을 완료해 주세요',draft:'준비됨',preparing:'이미지 처리 중',needs_input:'업로드 중',queued:'대기 중',running:'번역 중',succeeded:'완료',failed:'실패',needs_attention:'결과 확인 필요 — 다시 제출하지 마세요',paused:'일시 정지 — 계속하면 기존 작업을 확인합니다',busy:'처리 중…',storage:'로컬 저장 용량',cancel:'새 작업 중지',network:'연결이 끊겼습니다. 계속하기로 기존 작업을 확인하세요.',invalid:'JPG, PNG, WebP를 한 번에 10장까지, 장당 32 MiB 이하로 선택하세요.',dimensions:'지원하는 이미지 크기를 초과했습니다. 긴 이미지는 자동 분할하지 않습니다.',full:'로컬 공간이 부족하거나 저장할 수 없습니다. 이전 기록을 삭제하거나 저장을 허용한 뒤 계속하세요.',quota:'이 네트워크의 비회원 한도가 소진되었거나 혼잡합니다. 로그인하거나 나중에 시도하세요.',expired:'세션 또는 서버 결과가 만료되었습니다. 저장한 로컬 번역본은 볼 수 있습니다.',auth:'로그인이 만료되었거나 계정이 변경되었습니다. 다시 로그인하세요.',processing:'이미지 처리에 실패했습니다. 파일이 손상되었거나 너무 클 수 있습니다.',generic:'작업을 완료하지 못했습니다. 다시 시도하세요.',noText:'텍스트 없음',partial:'일부 텍스트를 번역하지 못했습니다',newImages:'이미지 추가',open:'번역 페이지 열기',guestHistory:'비회원 기록',myHistory:'내 기록',fit:'너비에 맞추기',verifyFailed:'인증에 실패했거나 만료되었습니다. 다시 시도하세요.',saveDownload:'번역본을 저장하지 못했습니다. 지금 다운로드하고 나중에 저장을 다시 시도하세요.'}};
interface WorkspaceCopy {
  uploadTitle: string;
  settingsTitle: string;
  previewTitle: string;
  historyEmpty: string;
  localTitle: string;
  serverTitle: string;
  errorTitle: string;
  verificationHint: string;
  reload: string;
}
export const translationCopy: Record<Locale, Copy & WorkspaceCopy> = {
  en: {
    ...baseCopy.en,
    uploadTitle: 'Add your pages', settingsTitle: 'Make it your language', previewTitle: 'Read & compare',
    historyEmpty: 'Your pages and translations stay here.', localTitle: 'Saved on this browser', serverTitle: 'About the guest trial',
    errorTitle: 'This action needs attention', verificationHint: 'A quick check, then your translation continues.', reload: 'Reconnect',
  },
  'zh-CN': {
    ...baseCopy['zh-CN'],
    uploadTitle: '放入漫画图片', settingsTitle: '换成你的语言', previewTitle: '阅读与对照',
    historyEmpty: '你的图片与译图，会保存在这里。', localTitle: '保存在当前浏览器', serverTitle: '匿名体验须知',
    errorTitle: '操作需要处理', verificationHint: '完成这一步验证，翻译会继续进行。', reload: '重新连接',
  },
  'zh-TW': {
    ...baseCopy['zh-TW'],
    uploadTitle: '放入漫畫圖片', settingsTitle: '換成你的語言', previewTitle: '閱讀與對照',
    historyEmpty: '你的圖片與譯圖，會儲存在這裡。', localTitle: '儲存在目前瀏覽器', serverTitle: '匿名體驗須知',
    errorTitle: '操作需要處理', verificationHint: '完成這一步驗證，翻譯會繼續進行。', reload: '重新連線',
  },
  ja: {
    ...baseCopy.ja,
    uploadTitle: '漫画画像を追加', settingsTitle: '読みたい言語へ', previewTitle: '読んで、比べる',
    historyEmpty: '画像と翻訳はここに保存されます。', localTitle: 'このブラウザーに保存', serverTitle: 'ゲスト体験について',
    errorTitle: '操作を確認してください', verificationHint: '認証が完了すると翻訳を続けます。', reload: '再接続',
  },
  ko: {
    ...baseCopy.ko,
    uploadTitle: '만화 이미지 추가', settingsTitle: '원하는 언어로', previewTitle: '읽고 비교하기',
    historyEmpty: '이미지와 번역본이 여기에 저장됩니다.', localTitle: '현재 브라우저에 저장', serverTitle: '비회원 체험 안내',
    errorTitle: '작업을 확인해 주세요', verificationHint: '인증을 완료하면 번역이 계속됩니다.', reload: '다시 연결',
  },
};
export function translationError(code:string,t:Copy){if(code.startsWith('GUEST_')&&code.endsWith('LIMIT')||code==='GUEST_BUSY')return t.quota;if(code.includes('VERIFICATION'))return t.verifyFailed;if(code.includes('STORAGE')||code==='QuotaExceededError')return t.full;if(code==='IMAGE_DIMENSIONS_LIMIT')return t.dimensions;if(code==='IMAGE_SELECTION_LIMIT'||code==='IMAGE_FORMAT_LIMIT')return t.invalid;if(code==='AUTH_REQUIRED'||code==='TOKEN_INVALID')return t.auth;if(code==='GUEST_SESSION_EXPIRED'||code==='TRANSLATION_UNAVAILABLE')return t.expired;if(code==='GUEST_UNAVAILABLE')return t.disabled;if(code.includes('IMAGE_')||code.includes('ARTIFACT'))return t.processing;if(code==='NETWORK_ERROR'||code==='TypeError'||code==='TimeoutError')return t.network;return t.generic;}
