import type { Locale } from './locales';

export const translationCacheCopy: Record<Locale, { clear: string; confirm: string; cleared: string }> = {
  'zh-CN': { clear: '清空本地缓存', confirm: '清空当前列表中的全部原图、译图和本地记录？此操作无法撤销，请先下载需要保留的图片。不会退出登录、重置额度或取消服务器任务；其他账户的历史不受影响。', cleared: '当前列表的本地缓存已清空。' },
  'zh-TW': { clear: '清空本機快取', confirm: '清空目前清單中的全部原圖、譯圖和本機紀錄？此操作無法復原，請先下載需要保留的圖片。不會登出、重設額度或取消伺服器任務；其他帳戶的歷史不受影響。', cleared: '目前清單的本機快取已清空。' },
  en: { clear: 'Clear local cache', confirm: 'Remove all original images, translations and local records in this list? This cannot be undone. Download anything you need first. This does not sign you out, reset your quota or cancel server tasks. Other accounts’ history is unchanged.', cleared: 'Local cache for this list cleared.' },
  ar: { clear: 'مسح التخزين المحلي', confirm: 'هل تريد حذف جميع الصور الأصلية والترجمات والسجلات المحلية في هذه القائمة؟ لا يمكن التراجع. نزّل الصور التي تحتاجها أولًا. لن يتم تسجيل خروجك أو إعادة تعيين حصتك أو إلغاء مهام الخادم. لن يتأثر سجل الحسابات الأخرى.', cleared: 'تم مسح التخزين المحلي لهذه القائمة.' },
  ja: { clear: 'ローカルキャッシュを消去', confirm: 'この一覧の原画像、翻訳画像、ローカル履歴をすべて削除しますか？元に戻せません。必要な画像を先にダウンロードしてください。ログアウト、利用枠のリセット、サーバータスクのキャンセルは行いません。他のアカウントの履歴は変更しません。', cleared: 'この一覧のローカルキャッシュを消去しました。' },
  ko: { clear: '로컬 캐시 비우기', confirm: '현재 목록의 원본 이미지, 번역본, 로컬 기록을 모두 삭제할까요? 되돌릴 수 없습니다. 필요한 이미지는 먼저 다운로드하세요. 로그아웃, 사용 한도 초기화, 서버 작업 취소는 하지 않으며 다른 계정의 기록은 유지됩니다.', cleared: '현재 목록의 로컬 캐시를 비웠습니다.' },
  fr: { clear: 'Vider le cache local', confirm: 'Supprimer toutes les images originales, traductions et données locales de cette liste ? Cette action est irréversible. Téléchargez d’abord les images à conserver. Votre connexion, votre quota, les tâches serveur et l’historique des autres comptes restent inchangés.', cleared: 'Le cache local de cette liste a été vidé.' },
  es: { clear: 'Vaciar caché local', confirm: '¿Eliminar los originales, las traducciones y los registros locales de esta lista? No se puede deshacer. Descarga primero las imágenes que quieras conservar. No se cerrará la sesión, no se restablecerá la cuota ni se cancelarán tareas del servidor. El historial de otras cuentas no cambia.', cleared: 'Se ha vaciado la caché local de esta lista.' },
  'pt-BR': { clear: 'Limpar cache local', confirm: 'Excluir todas as imagens originais, traduções e registros locais desta lista? Não é possível desfazer. Baixe primeiro as imagens que deseja guardar. Isso não encerra sua sessão, redefine sua cota nem cancela tarefas do servidor. O histórico de outras contas não será alterado.', cleared: 'O cache local desta lista foi limpo.' },
  de: { clear: 'Lokalen Cache leeren', confirm: 'Alle Originalbilder, Übersetzungen und lokalen Einträge dieser Liste löschen? Dies kann nicht rückgängig gemacht werden. Lade benötigte Bilder vorher herunter. Anmeldung, Kontingent, Serveraufträge und der Verlauf anderer Konten bleiben unverändert.', cleared: 'Der lokale Cache dieser Liste wurde geleert.' },
  it: { clear: 'Svuota cache locale', confirm: 'Eliminare tutte le immagini originali, le traduzioni e i record locali di questo elenco? L’azione è irreversibile. Scarica prima le immagini da conservare. Non verrai disconnesso, la quota non verrà azzerata e le attività del server non verranno annullate. La cronologia degli altri account resta invariata.', cleared: 'La cache locale di questo elenco è stata svuotata.' },
  ru: { clear: 'Очистить локальный кэш', confirm: 'Удалить все оригиналы, переводы и локальные записи этого списка? Отменить действие нельзя. Сначала скачайте нужные изображения. Вход в аккаунт, квота, задачи на сервере и история других аккаунтов не изменятся.', cleared: 'Локальный кэш этого списка очищен.' },
  pl: { clear: 'Wyczyść lokalną pamięć', confirm: 'Usunąć wszystkie oryginały, tłumaczenia i lokalne wpisy z tej listy? Tej czynności nie można cofnąć. Najpierw pobierz potrzebne obrazy. Nie nastąpi wylogowanie, reset limitu ani anulowanie zadań serwera. Historia innych kont pozostanie bez zmian.', cleared: 'Lokalna pamięć tej listy została wyczyszczona.' },
  uk: { clear: 'Очистити локальний кеш', confirm: 'Видалити всі оригінали, переклади та локальні записи цього списку? Скасувати дію неможливо. Спочатку завантажте потрібні зображення. Вхід в обліковий запис, ліміт, серверні завдання та історія інших облікових записів не зміняться.', cleared: 'Локальний кеш цього списку очищено.' },
  tr: { clear: 'Yerel önbelleği temizle', confirm: 'Bu listedeki tüm orijinal görseller, çeviriler ve yerel kayıtlar silinsin mi? Bu işlem geri alınamaz. Gerekli görselleri önce indirin. Oturumunuz kapatılmaz, kotanız sıfırlanmaz ve sunucu görevleri iptal edilmez. Diğer hesapların geçmişi değişmez.', cleared: 'Bu listenin yerel önbelleği temizlendi.' },
  vi: { clear: 'Xóa bộ nhớ đệm cục bộ', confirm: 'Xóa toàn bộ ảnh gốc, bản dịch và bản ghi cục bộ trong danh sách này? Không thể hoàn tác. Hãy tải xuống ảnh cần giữ trước. Thao tác không đăng xuất, đặt lại hạn mức hay hủy tác vụ máy chủ. Lịch sử tài khoản khác không bị ảnh hưởng.', cleared: 'Đã xóa bộ nhớ đệm cục bộ của danh sách này.' },
  id: { clear: 'Kosongkan cache lokal', confirm: 'Hapus semua gambar asli, terjemahan, dan catatan lokal dalam daftar ini? Tindakan ini tidak dapat dibatalkan. Unduh gambar yang diperlukan terlebih dahulu. Anda tidak akan keluar, kuota tidak direset, dan tugas server tidak dibatalkan. Riwayat akun lain tidak berubah.', cleared: 'Cache lokal untuk daftar ini telah dikosongkan.' },
};
