"""Final application baseline. Empty databases only; no upgrade path."""
from alembic import op
import sqlalchemy as sa
revision = 'payments_0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    if set(sa.inspect(op.get_bind()).get_table_names()) - {'alembic_version'}:
        raise RuntimeError('payments_0001 requires an empty database')
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_requests',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('kind', sa.String(16), nullable=False),
        sa.Column('site_name', sa.String(100), nullable=False),
        sa.Column('url', sa.String(2048), nullable=False),
        sa.Column('comment', sa.String(1000), nullable=False),
        sa.Column('contact', sa.String(200), nullable=False),
        sa.Column('idempotency_key', sa.String(36), nullable=False, unique=True),
        sa.Column('request_hash', sa.String(64), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index('ix_support_requests_kind_created', 'support_requests', ['kind', 'created_at', 'id'])
    op.create_table('support_request_admissions',
        sa.Column('client_hash', sa.String(64), primary_key=True),
        sa.Column('minute_started_at', sa.DateTime(), nullable=False),
        sa.Column('minute_count', sa.Integer(), nullable=False),
        sa.Column('day_started_at', sa.DateTime(), nullable=False),
        sa.Column('day_count', sa.Integer(), nullable=False))
    op.create_index('ix_support_request_admissions_day_started_at', 'support_request_admissions', ['day_started_at'])
    op.create_table('billing_events',
    sa.Column('id', sa.String(length=320), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=320), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('last_retry_key', sa.String(length=64), nullable=True),
    sa.Column('last_retry_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_events_next_attempt_at'), 'billing_events', ['next_attempt_at'], unique=False)
    op.create_table('billing_plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_provider', sa.String(length=16), nullable=True),
    sa.CheckConstraint("default_provider IN ('stripe', 'creem')"),
    sa.CheckConstraint('id = 1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compute_nodes',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=False),
    sa.Column('engine_version', sa.String(length=120), nullable=False),
    sa.Column('device', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('credential_hash', sa.String(length=64), nullable=True),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('applied_config_version', sa.Integer(), nullable=False),
    sa.Column('desired_config', sa.JSON(), nullable=False),
    sa.Column('supported_languages', sa.JSON(), nullable=False),
    sa.Column('config_error', sa.String(length=80), nullable=True),
    sa.Column('runtime_report', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id')
    )
    op.create_table('fairness_states',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('service', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('providers',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('validation_job_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduler_mutex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_heartbeats',
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('instance_id', sa.String(length=200), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('role', 'instance_id')
    )
    op.create_index(op.f('ix_service_heartbeats_heartbeat_at'), 'service_heartbeats', ['heartbeat_at'], unique=False)
    op.create_table('translation_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('revision_id', sa.String(length=36), nullable=True),
    sa.Column('requests_per_minute', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('requests_per_minute BETWEEN 1 AND 10000'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_translation_default', 'translation_providers', ['is_default'], unique=True, sqlite_where=sa.text('is_default = 1'), postgresql_where=sa.text('is_default'))
    op.create_table('upload_ingress_mutex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('membership_id', sa.String(length=36), nullable=True),
    sa.Column('plus_started_at', sa.DateTime(), nullable=True),
    sa.Column('plus_expires_at', sa.DateTime(), nullable=True),
    sa.Column('plus_timezone', sa.String(length=80), nullable=True),
    sa.Column('plus_monthly_pages', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('plus_monthly_pages >= 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject')
    )
    op.create_table('admin_audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=60), nullable=False),
    sa.Column('target_id', sa.String(length=320), nullable=False),
    sa.Column('operation_key', sa.String(length=64), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_key')
    )
    op.create_index('ix_admin_audit_actor', 'admin_audit_events', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_admin_audit_created', 'admin_audit_events', ['created_at', 'id'], unique=False)
    op.create_index('ix_admin_audit_target', 'admin_audit_events', ['target_type', 'target_id', 'created_at'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), server_default='local', nullable=False),
    sa.Column('mime', sa.String(length=30), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('active_references', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('purged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_content_lookup', 'assets', ['kind', 'sha256'], unique=False)
    op.create_index(op.f('ix_assets_expires_at'), 'assets', ['expires_at'], unique=False)
    op.create_index(op.f('ix_assets_last_accessed_at'), 'assets', ['last_accessed_at'], unique=False)
    op.create_index('ix_assets_owner_content', 'assets', ['owner_id', 'kind', 'sha256'], unique=False)
    op.create_index(op.f('ix_assets_owner_id'), 'assets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_assets_parent_id'), 'assets', ['parent_id'], unique=False)
    op.create_index(op.f('ix_assets_sha256'), 'assets', ['sha256'], unique=False)
    op.create_index('ix_assets_storage_key', 'assets', ['storage_backend', 'storage_key'], unique=False)
    op.create_table('billing_accounts',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('trial_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('billing_customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('customer_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("environment IN ('test', 'live')"),
    sa.CheckConstraint("provider IN ('stripe', 'creem')"),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'provider', 'environment'),
    sa.UniqueConstraint('provider', 'environment', 'customer_id')
    )
    op.create_index(op.f('ix_billing_customers_owner_id'), 'billing_customers', ['owner_id'], unique=False)
    op.create_table('billing_plan_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('monthly_redraw_pages', sa.Integer(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('trial_redraw_pages', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('monthly_redraw_pages >= 0'),
    sa.CheckConstraint('trial_days > 0 OR trial_redraw_pages = 0'),
    sa.CheckConstraint('trial_days >= 0 AND trial_days <= 30'),
    sa.CheckConstraint('trial_redraw_pages >= 0'),
    sa.CheckConstraint('version > 0'),
    sa.ForeignKeyConstraint(['plan_id'], ['billing_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'plan_id'),
    sa.UniqueConstraint('plan_id', 'version')
    )
    op.create_index(op.f('ix_billing_plan_revisions_plan_id'), 'billing_plan_revisions', ['plan_id'], unique=False)
    op.create_table('compute_claims',
    sa.Column('node_id', sa.String(length=80), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('lease_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['compute_nodes.id'], ),
    sa.PrimaryKeyConstraint('node_id', 'request_id')
    )
    op.create_table('control_admissions',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('tokens', sa.Float(), nullable=False),
    sa.Column('refilled_at', sa.DateTime(), nullable=False),
    sa.Column('leases', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'scope')
    )
    op.create_table('feedback_admissions',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('request_tokens', sa.Float(), nullable=False),
    sa.Column('refilled_at', sa.DateTime(), nullable=False),
    sa.Column('day_started_at', sa.DateTime(), nullable=False),
    sa.Column('daily_receipts', sa.Integer(), nullable=False),
    sa.CheckConstraint('daily_receipts >= 0', name='ck_feedback_admissions_daily_receipts'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('membership_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_key', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_key')
    )
    op.create_index(op.f('ix_membership_operations_owner_id'), 'membership_operations', ['owner_id'], unique=False)
    op.create_table('reading_sessions',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('window_hash', sa.String(length=64), nullable=False),
    sa.Column('window', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('fenced', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'session_id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_system_settings_singleton'),
    sa.CheckConstraint('version >= 1', name='ck_system_settings_version'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation_policies',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('translation_provider_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['translation_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_provider_revisions_provider_id'), 'translation_provider_revisions', ['provider_id'], unique=False)
    op.create_table('user_mode_queues',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=True),
    sa.Column('session_epoch', sa.Integer(), nullable=False),
    sa.Column('session_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'mode')
    )
    op.create_table('billing_prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('plan_revision_id', sa.String(length=36), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit_amount', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("environment IN ('test', 'live')"),
    sa.CheckConstraint("interval IN ('month', 'year')"),
    sa.CheckConstraint("status IN ('draft', 'active', 'archived')"),
    sa.CheckConstraint('unit_amount > 0'),
    sa.ForeignKeyConstraint(['plan_id'], ['billing_plans.id'], ),
    sa.ForeignKeyConstraint(['plan_revision_id', 'plan_id'], ['billing_plan_revisions.id', 'billing_plan_revisions.plan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_billing_active_offer', 'billing_prices', ['plan_id', 'environment', 'currency', 'interval'], unique=True, sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
    op.create_table('file_pages',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('page_index >= 0'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'file_hash', 'page_index')
    )
    op.create_index(op.f('ix_file_pages_asset_id'), 'file_pages', ['asset_id'], unique=False)
    op.create_table('billing_price_bindings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('price_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('trial_product_id', sa.String(length=255), nullable=True),
    sa.Column('provider_price_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("environment IN ('test', 'live')"),
    sa.CheckConstraint("provider != 'creem' OR provider_price_id IS NULL"),
    sa.CheckConstraint("provider != 'stripe' OR provider_price_id IS NOT NULL"),
    sa.CheckConstraint("provider != 'stripe' OR trial_product_id IS NULL"),
    sa.CheckConstraint("provider IN ('stripe', 'creem')"),
    sa.CheckConstraint("status IN ('draft', 'active', 'archived')"),
    sa.CheckConstraint('trial_product_id IS NULL OR trial_product_id != product_id'),
    sa.ForeignKeyConstraint(['price_id'], ['billing_prices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'environment', 'provider_price_id')
    )
    op.create_index(op.f('ix_billing_price_bindings_price_id'), 'billing_price_bindings', ['price_id'], unique=False)
    op.create_index('uq_billing_active_binding', 'billing_price_bindings', ['price_id', 'provider', 'environment'], unique=True, sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
    op.create_index('uq_billing_creem_product', 'billing_price_bindings', ['provider', 'environment', 'product_id'], unique=True, sqlite_where=sa.text("provider = 'creem'"), postgresql_where=sa.text("provider = 'creem'"))
    op.create_table('billing_checkouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('price_id', sa.String(length=36), nullable=False),
    sa.Column('binding_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('return_url', sa.String(length=1024), nullable=False),
    sa.Column('checkout_url', sa.String(length=2048), nullable=True),
    sa.Column('trial', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.CheckConstraint("environment IN ('test', 'live')"),
    sa.CheckConstraint("provider IN ('stripe', 'creem')"),
    sa.ForeignKeyConstraint(['binding_id'], ['billing_price_bindings.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['billing_prices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'environment', 'session_id')
    )
    op.create_index(op.f('ix_billing_checkouts_owner_id'), 'billing_checkouts', ['owner_id'], unique=False)
    op.create_table('billing_subscriptions',
    sa.Column('id', sa.String(length=320), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('checkout_id', sa.String(length=36), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('customer_id', sa.String(length=255), nullable=False),
    sa.Column('price_id', sa.String(length=36), nullable=False),
    sa.Column('binding_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('trial_starts_at', sa.DateTime(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('paid_starts_at', sa.DateTime(), nullable=True),
    sa.Column('paid_ends_at', sa.DateTime(), nullable=True),
    sa.Column('next_billed_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['binding_id'], ['billing_price_bindings.id'], ),
    sa.ForeignKeyConstraint(['checkout_id'], ['billing_checkouts.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['billing_prices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_id')
    )
    op.create_index(op.f('ix_billing_subscriptions_owner_id'), 'billing_subscriptions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_synced_at'), 'billing_subscriptions', ['synced_at'], unique=False)
    op.create_table('billing_invoices',
    sa.Column('id', sa.String(length=320), nullable=False),
    sa.Column('subscription_id', sa.String(length=320), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['billing_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_invoices_subscription_id'), 'billing_invoices', ['subscription_id'], unique=False)
    op.create_table('billing_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('checkout_id', sa.String(length=36), nullable=True),
    sa.Column('subscription_id', sa.String(length=320), nullable=True),
    sa.Column('price_id', sa.String(length=36), nullable=False),
    sa.Column('binding_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('refunded_total', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.CheckConstraint("environment IN ('test', 'live')"),
    sa.CheckConstraint("kind IN ('initial', 'renewal')"),
    sa.CheckConstraint("provider IN ('stripe', 'creem')"),
    sa.CheckConstraint('refunded_total >= 0'),
    sa.CheckConstraint('subtotal >= 0'),
    sa.CheckConstraint('total >= 0'),
    sa.ForeignKeyConstraint(['binding_id'], ['billing_price_bindings.id'], ),
    sa.ForeignKeyConstraint(['checkout_id'], ['billing_checkouts.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['billing_prices.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['billing_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'environment', 'external_id')
    )
    op.create_index(op.f('ix_billing_orders_checkout_id'), 'billing_orders', ['checkout_id'], unique=False)
    op.create_index('ix_billing_orders_created', 'billing_orders', ['created_at', 'id'], unique=False)
    op.create_index('ix_billing_orders_filter', 'billing_orders', ['provider', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_billing_orders_owner_id'), 'billing_orders', ['owner_id'], unique=False)
    op.create_index(op.f('ix_billing_orders_subscription_id'), 'billing_orders', ['subscription_id'], unique=False)
    op.create_index('uq_billing_initial_order', 'billing_orders', ['checkout_id'], unique=True, sqlite_where=sa.text("kind = 'initial'"), postgresql_where=sa.text("kind = 'initial'"))
    op.create_table('billing_disputes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=320), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("environment IN ('test', 'live')"),
    sa.CheckConstraint("provider IN ('stripe', 'creem')"),
    sa.CheckConstraint('amount >= 0'),
    sa.ForeignKeyConstraint(['order_id'], ['billing_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'environment', 'external_id')
    )
    op.create_index(op.f('ix_billing_disputes_order_id'), 'billing_disputes', ['order_id'], unique=False)
    op.create_table('billing_order_transitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=320), nullable=True),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['billing_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_billing_order_timeline', 'billing_order_transitions', ['order_id', 'created_at', 'id'], unique=False)
    op.create_table('billing_refunds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=320), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("environment IN ('test', 'live')"),
    sa.CheckConstraint("provider IN ('stripe', 'creem')"),
    sa.CheckConstraint('amount >= 0'),
    sa.ForeignKeyConstraint(['order_id'], ['billing_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'environment', 'external_id')
    )
    op.create_index(op.f('ix_billing_refunds_order_id'), 'billing_refunds', ['order_id'], unique=False)
    op.create_table('billing_terms',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=320), nullable=False),
    sa.Column('price_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=320), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("kind IN ('trial', 'paid')"),
    sa.CheckConstraint('ends_at > starts_at'),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing_invoices.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['billing_prices.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['billing_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'kind', 'starts_at')
    )
    op.create_index('ix_billing_terms_owner_dates', 'billing_terms', ['owner_id', 'ends_at', 'starts_at'], unique=False)
    op.create_index(op.f('ix_billing_terms_subscription_id'), 'billing_terms', ['subscription_id'], unique=False)
    op.create_table('quota_periods',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('billing_term_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_key', sa.String(length=200), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('grants_access', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('granted', sa.Integer(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.CheckConstraint("(source = 'subscription' AND billing_term_id IS NOT NULL) OR (source != 'subscription' AND billing_term_id IS NULL)"),
    sa.CheckConstraint("mode IN ('classic', 'redraw')"),
    sa.CheckConstraint("source IN ('daily', 'membership', 'grant', 'subscription')"),
    sa.CheckConstraint('ends_at > starts_at'),
    sa.CheckConstraint('granted >= used + reserved'),
    sa.CheckConstraint('reserved >= 0'),
    sa.CheckConstraint('used >= 0'),
    sa.ForeignKeyConstraint(['billing_term_id'], ['billing_terms.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'source_key')
    )
    op.create_index(op.f('ix_quota_periods_billing_term_id'), 'quota_periods', ['billing_term_id'], unique=False)
    op.create_index(op.f('ix_quota_periods_owner_id'), 'quota_periods', ['owner_id'], unique=False)
    op.create_index('ix_quota_periods_owner_mode_end', 'quota_periods', ['owner_id', 'mode', 'ends_at'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('input_asset_id', sa.String(length=36), nullable=True),
    sa.Column('input_pinned', sa.Boolean(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('page_index', sa.Integer(), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('realtime_until', sa.DateTime(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('change_sequence', sa.BigInteger(), nullable=False),
    sa.Column('output_asset_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('target_language', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('phase', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('quota_pages', sa.Integer(), nullable=False),
    sa.Column('quota_kind', sa.String(length=30), nullable=False),
    sa.Column('quota_period_id', sa.String(length=64), nullable=True),
    sa.Column('entitlement', sa.JSON(), nullable=False),
    sa.Column('settlement', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('discard_output', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.String(length=300), nullable=True),
    sa.Column('quality_flags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('unknown_since', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['input_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['output_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quota_period_id'], ['quota_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'operation', 'idempotency_key')
    )
    op.create_index(op.f('ix_jobs_cache_key'), 'jobs', ['cache_key'], unique=False)
    op.create_index(op.f('ix_jobs_change_sequence'), 'jobs', ['change_sequence'], unique=False)
    op.create_index(op.f('ix_jobs_changed_at'), 'jobs', ['changed_at'], unique=False)
    op.create_index('ix_jobs_completed_at', 'jobs', ['completed_at'], unique=False)
    op.create_index('ix_jobs_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_input_asset_id'), 'jobs', ['input_asset_id'], unique=False)
    op.create_index('ix_jobs_owner_content', 'jobs', ['owner_id', 'cache_key', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_owner_id'), 'jobs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_jobs_quota_period_id'), 'jobs', ['quota_period_id'], unique=False)
    op.create_index(op.f('ix_jobs_realtime_until'), 'jobs', ['realtime_until'], unique=False)
    op.create_index(op.f('ix_jobs_source_sha256'), 'jobs', ['source_sha256'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=80), nullable=False),
    sa.Column('output_storage_backend', sa.String(length=20), server_default='local', nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=False),
    sa.Column('call_started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('request_id', sa.String(length=200), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=True),
    sa.Column('cost_state', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('recovered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_job_id'), 'attempts', ['job_id'], unique=False)
    op.create_table('classic_states',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.Column('timings', sa.JSON(), nullable=False),
    sa.Column('artifacts', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('image_admissions',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('admitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('ix_image_admissions_owner_time', 'image_admissions', ['owner_id', 'admitted_at'], unique=False)
    op.create_table('job_stages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'name')
    )
    op.create_index(op.f('ix_job_stages_job_id'), 'job_stages', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_stages_status'), 'job_stages', ['status'], unique=False)
    op.create_index('ix_stage_ready', 'job_stages', ['status', 'name', 'available_at'], unique=False)
    op.create_table('translation_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_results_content_generated', 'translation_results', ['cache_key', 'generated_at', 'id'], unique=False)
    op.create_table('upload_reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('expected_sha256', sa.String(length=64), nullable=False),
    sa.Column('expected_size', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=30), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('max_expires_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.String(length=300), nullable=True),
    sa.Column('verified_info', sa.JSON(), nullable=True),
    sa.CheckConstraint('expected_size > 0'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_reservations_expires_at'), 'upload_reservations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_upload_reservations_job_id'), 'upload_reservations', ['job_id'], unique=True)
    op.create_index(op.f('ix_upload_reservations_owner_id'), 'upload_reservations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_upload_reservations_status'), 'upload_reservations', ['status'], unique=False)
    op.create_table('usage_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('period_id', sa.String(length=64), nullable=True),
    sa.Column('quota_kind', sa.String(length=30), nullable=True),
    sa.Column('transaction_key', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['quota_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_key')
    )
    op.create_index('ix_ledger_owner_created', 'usage_ledger', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_ledger_owner_id'), 'usage_ledger', ['owner_id'], unique=False)
    op.create_index(op.f('ix_usage_ledger_period_id'), 'usage_ledger', ['period_id'], unique=False)
    op.create_table('execution_leases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('stage_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=80), nullable=False),
    sa.Column('executor_id', sa.String(length=160), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('resource_pool', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('priority_class', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('estimated_seconds', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(length=24), nullable=True),
    sa.Column('result_hash', sa.String(length=64), nullable=True),
    sa.Column('output_key', sa.String(length=200), nullable=True),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['compute_nodes.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['job_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_leases_completed_at'), 'execution_leases', ['completed_at'], unique=False)
    op.create_index(op.f('ix_execution_leases_expires_at'), 'execution_leases', ['expires_at'], unique=False)
    op.create_index(op.f('ix_execution_leases_job_id'), 'execution_leases', ['job_id'], unique=False)
    op.create_index(op.f('ix_execution_leases_node_id'), 'execution_leases', ['node_id'], unique=False)
    op.create_index(op.f('ix_execution_leases_stage_id'), 'execution_leases', ['stage_id'], unique=False)
    op.create_table('result_accesses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('input_asset_id', sa.String(length=36), nullable=False),
    sa.Column('output_asset_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('change_sequence', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['input_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['output_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['translation_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'result_id')
    )
    op.create_index(op.f('ix_result_accesses_input_asset_id'), 'result_accesses', ['input_asset_id'], unique=False)
    op.create_index(op.f('ix_result_accesses_output_asset_id'), 'result_accesses', ['output_asset_id'], unique=False)
    op.create_index('ix_result_accesses_owner_changes', 'result_accesses', ['owner_id', 'change_sequence'], unique=False)
    op.create_index('ix_result_accesses_result', 'result_accesses', ['result_id'], unique=False)
    op.create_table('text_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('execution_lease_id', sa.String(length=36), nullable=True),
    sa.Column('group_index', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('request_id', sa.String(length=200), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=True),
    sa.Column('reserved_micros', sa.Integer(), nullable=False),
    sa.Column('accounted_micros', sa.Integer(), nullable=False),
    sa.Column('cost_state', sa.String(length=24), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('accounted_micros >= 0'),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'group_index', 'sequence')
    )
    op.create_index(op.f('ix_text_calls_execution_lease_id'), 'text_calls', ['execution_lease_id'], unique=False)
    op.create_index(op.f('ix_text_calls_job_id'), 'text_calls', ['job_id'], unique=False)
    op.create_index('ix_text_calls_provider_started', 'text_calls', ['provider_id', 'started_at'], unique=False)
    op.create_index('ix_text_calls_started_at', 'text_calls', ['started_at'], unique=False)
    op.create_table('upload_ingress_leases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_reservations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id')
    )
    op.create_index(op.f('ix_upload_ingress_leases_expires_at'), 'upload_ingress_leases', ['expires_at'], unique=False)
    op.create_index(op.f('ix_upload_ingress_leases_owner_id'), 'upload_ingress_leases', ['owner_id'], unique=False)
    op.create_table('translation_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('access_id', sa.String(length=36), nullable=True),
    sa.Column('output_asset_id', sa.String(length=36), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(job_id IS NOT NULL AND access_id IS NULL) OR (job_id IS NULL AND access_id IS NOT NULL)'),
    sa.ForeignKeyConstraint(['access_id'], ['result_accesses.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['output_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'idempotency_key')
    )
    op.create_index('ix_feedback_job', 'translation_feedback', ['job_id'], unique=False)
    op.create_index('ix_feedback_owner_created', 'translation_feedback', ['owner_id', 'created_at'], unique=False)
    op.create_table('translation_operations',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('operation_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('access_id', sa.String(length=36), nullable=True),
    sa.Column('descriptor', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(job_id IS NOT NULL AND access_id IS NULL) OR (job_id IS NULL AND access_id IS NOT NULL)'),
    sa.ForeignKeyConstraint(['access_id'], ['result_accesses.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'operation_key')
    )
    op.create_index(op.f('ix_translation_operations_access_id'), 'translation_operations', ['access_id'], unique=False)
    op.create_index(op.f('ix_translation_operations_job_id'), 'translation_operations', ['job_id'], unique=False)
    op.create_index('ix_translation_operations_owner_created', 'translation_operations', ['owner_id', 'created_at'], unique=False)
    op.create_table('translation_feedback_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('operation_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=False),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['feedback_id'], ['translation_feedback.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'operation_key')
    )
    op.create_index('ix_feedback_reviews_feedback_created', 'translation_feedback_reviews', ['feedback_id', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###
    op.execute(sa.text("INSERT INTO scheduler_mutex (id, revision) VALUES (1, 0)"))


def downgrade():
    op.drop_table('support_requests')
    op.drop_table('support_request_admissions')
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_reviews_feedback_created', table_name='translation_feedback_reviews')
    op.drop_table('translation_feedback_reviews')
    op.drop_index('ix_translation_operations_owner_created', table_name='translation_operations')
    op.drop_index(op.f('ix_translation_operations_job_id'), table_name='translation_operations')
    op.drop_index(op.f('ix_translation_operations_access_id'), table_name='translation_operations')
    op.drop_table('translation_operations')
    op.drop_index('ix_feedback_owner_created', table_name='translation_feedback')
    op.drop_index('ix_feedback_job', table_name='translation_feedback')
    op.drop_table('translation_feedback')
    op.drop_index(op.f('ix_upload_ingress_leases_owner_id'), table_name='upload_ingress_leases')
    op.drop_index(op.f('ix_upload_ingress_leases_expires_at'), table_name='upload_ingress_leases')
    op.drop_table('upload_ingress_leases')
    op.drop_index('ix_text_calls_started_at', table_name='text_calls')
    op.drop_index('ix_text_calls_provider_started', table_name='text_calls')
    op.drop_index(op.f('ix_text_calls_job_id'), table_name='text_calls')
    op.drop_index(op.f('ix_text_calls_execution_lease_id'), table_name='text_calls')
    op.drop_table('text_calls')
    op.drop_index('ix_result_accesses_result', table_name='result_accesses')
    op.drop_index('ix_result_accesses_owner_changes', table_name='result_accesses')
    op.drop_index(op.f('ix_result_accesses_output_asset_id'), table_name='result_accesses')
    op.drop_index(op.f('ix_result_accesses_input_asset_id'), table_name='result_accesses')
    op.drop_table('result_accesses')
    op.drop_index(op.f('ix_execution_leases_stage_id'), table_name='execution_leases')
    op.drop_index(op.f('ix_execution_leases_node_id'), table_name='execution_leases')
    op.drop_index(op.f('ix_execution_leases_job_id'), table_name='execution_leases')
    op.drop_index(op.f('ix_execution_leases_expires_at'), table_name='execution_leases')
    op.drop_index(op.f('ix_execution_leases_completed_at'), table_name='execution_leases')
    op.drop_table('execution_leases')
    op.drop_index(op.f('ix_usage_ledger_period_id'), table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_owner_id'), table_name='usage_ledger')
    op.drop_index('ix_ledger_owner_created', table_name='usage_ledger')
    op.drop_table('usage_ledger')
    op.drop_index(op.f('ix_upload_reservations_status'), table_name='upload_reservations')
    op.drop_index(op.f('ix_upload_reservations_owner_id'), table_name='upload_reservations')
    op.drop_index(op.f('ix_upload_reservations_job_id'), table_name='upload_reservations')
    op.drop_index(op.f('ix_upload_reservations_expires_at'), table_name='upload_reservations')
    op.drop_table('upload_reservations')
    op.drop_index('ix_results_content_generated', table_name='translation_results')
    op.drop_table('translation_results')
    op.drop_index('ix_stage_ready', table_name='job_stages')
    op.drop_index(op.f('ix_job_stages_status'), table_name='job_stages')
    op.drop_index(op.f('ix_job_stages_job_id'), table_name='job_stages')
    op.drop_table('job_stages')
    op.drop_index('ix_image_admissions_owner_time', table_name='image_admissions')
    op.drop_table('image_admissions')
    op.drop_table('classic_states')
    op.drop_index(op.f('ix_attempts_job_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source_sha256'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_realtime_until'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_quota_period_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_owner_id'), table_name='jobs')
    op.drop_index('ix_jobs_owner_content', table_name='jobs')
    op.drop_index(op.f('ix_jobs_input_asset_id'), table_name='jobs')
    op.drop_index('ix_jobs_created_at', table_name='jobs')
    op.drop_index('ix_jobs_completed_at', table_name='jobs')
    op.drop_index(op.f('ix_jobs_changed_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_change_sequence'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_cache_key'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_quota_periods_owner_mode_end', table_name='quota_periods')
    op.drop_index(op.f('ix_quota_periods_owner_id'), table_name='quota_periods')
    op.drop_index(op.f('ix_quota_periods_billing_term_id'), table_name='quota_periods')
    op.drop_table('quota_periods')
    op.drop_index(op.f('ix_billing_terms_subscription_id'), table_name='billing_terms')
    op.drop_index('ix_billing_terms_owner_dates', table_name='billing_terms')
    op.drop_table('billing_terms')
    op.drop_index(op.f('ix_billing_refunds_order_id'), table_name='billing_refunds')
    op.drop_table('billing_refunds')
    op.drop_index('ix_billing_order_timeline', table_name='billing_order_transitions')
    op.drop_table('billing_order_transitions')
    op.drop_index(op.f('ix_billing_disputes_order_id'), table_name='billing_disputes')
    op.drop_table('billing_disputes')
    op.drop_index('uq_billing_initial_order', table_name='billing_orders', sqlite_where=sa.text("kind = 'initial'"), postgresql_where=sa.text("kind = 'initial'"))
    op.drop_index(op.f('ix_billing_orders_subscription_id'), table_name='billing_orders')
    op.drop_index(op.f('ix_billing_orders_owner_id'), table_name='billing_orders')
    op.drop_index('ix_billing_orders_filter', table_name='billing_orders')
    op.drop_index('ix_billing_orders_created', table_name='billing_orders')
    op.drop_index(op.f('ix_billing_orders_checkout_id'), table_name='billing_orders')
    op.drop_table('billing_orders')
    op.drop_index(op.f('ix_billing_invoices_subscription_id'), table_name='billing_invoices')
    op.drop_table('billing_invoices')
    op.drop_index(op.f('ix_billing_subscriptions_synced_at'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_owner_id'), table_name='billing_subscriptions')
    op.drop_table('billing_subscriptions')
    op.drop_index(op.f('ix_billing_checkouts_owner_id'), table_name='billing_checkouts')
    op.drop_table('billing_checkouts')
    op.drop_index('uq_billing_creem_product', table_name='billing_price_bindings', sqlite_where=sa.text("provider = 'creem'"), postgresql_where=sa.text("provider = 'creem'"))
    op.drop_index('uq_billing_active_binding', table_name='billing_price_bindings', sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_billing_price_bindings_price_id'), table_name='billing_price_bindings')
    op.drop_table('billing_price_bindings')
    op.drop_index(op.f('ix_file_pages_asset_id'), table_name='file_pages')
    op.drop_table('file_pages')
    op.drop_index('uq_billing_active_offer', table_name='billing_prices', sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
    op.drop_table('billing_prices')
    op.drop_table('user_mode_queues')
    op.drop_index(op.f('ix_translation_provider_revisions_provider_id'), table_name='translation_provider_revisions')
    op.drop_table('translation_provider_revisions')
    op.drop_table('translation_policies')
    op.drop_table('system_settings')
    op.drop_table('reading_sessions')
    op.drop_index(op.f('ix_membership_operations_owner_id'), table_name='membership_operations')
    op.drop_table('membership_operations')
    op.drop_table('feedback_admissions')
    op.drop_table('control_admissions')
    op.drop_table('compute_claims')
    op.drop_index(op.f('ix_billing_plan_revisions_plan_id'), table_name='billing_plan_revisions')
    op.drop_table('billing_plan_revisions')
    op.drop_index(op.f('ix_billing_customers_owner_id'), table_name='billing_customers')
    op.drop_table('billing_customers')
    op.drop_table('billing_accounts')
    op.drop_index('ix_assets_storage_key', table_name='assets')
    op.drop_index(op.f('ix_assets_sha256'), table_name='assets')
    op.drop_index(op.f('ix_assets_parent_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_owner_id'), table_name='assets')
    op.drop_index('ix_assets_owner_content', table_name='assets')
    op.drop_index(op.f('ix_assets_last_accessed_at'), table_name='assets')
    op.drop_index(op.f('ix_assets_expires_at'), table_name='assets')
    op.drop_index('ix_assets_content_lookup', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_admin_audit_target', table_name='admin_audit_events')
    op.drop_index('ix_admin_audit_created', table_name='admin_audit_events')
    op.drop_index('ix_admin_audit_actor', table_name='admin_audit_events')
    op.drop_table('admin_audit_events')
    op.drop_table('users')
    op.drop_table('upload_ingress_mutex')
    op.drop_index('uq_translation_default', table_name='translation_providers', sqlite_where=sa.text('is_default = 1'), postgresql_where=sa.text('is_default'))
    op.drop_table('translation_providers')
    op.drop_index(op.f('ix_service_heartbeats_heartbeat_at'), table_name='service_heartbeats')
    op.drop_table('service_heartbeats')
    op.drop_table('scheduler_mutex')
    op.drop_table('providers')
    op.drop_table('fairness_states')
    op.drop_table('compute_nodes')
    op.drop_table('billing_settings')
    op.drop_table('billing_plans')
    op.drop_index(op.f('ix_billing_events_next_attempt_at'), table_name='billing_events')
    op.drop_table('billing_events')
    # ### end Alembic commands ###
