"""Fresh cluster schema; existing installations use a separate database."""
from alembic import op
import sqlalchemy as sa
revision = "nodes_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    if "users" in sa.inspect(op.get_bind()).get_table_names():
        raise RuntimeError("Cluster baseline requires a new empty database")
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compute_nodes',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=False),
    sa.Column('engine_version', sa.String(length=120), nullable=False),
    sa.Column('device', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('credential_hash', sa.String(length=64), nullable=True),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('applied_config_version', sa.Integer(), nullable=False),
    sa.Column('desired_config', sa.JSON(), nullable=False),
    sa.Column('supported_languages', sa.JSON(), nullable=False),
    sa.Column('config_error', sa.String(length=80), nullable=True),
    sa.Column('runtime_report', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id')
    )
    op.create_table('fairness_states',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('service', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('providers',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('validation_job_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduler_mutex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_scans',
    sa.Column('backend', sa.String(length=20), nullable=False),
    sa.Column('cursor', sa.String(length=4096), nullable=True),
    sa.Column('next_scan_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('backend')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('membership_id', sa.String(length=36), nullable=True),
    sa.Column('plus_started_at', sa.DateTime(), nullable=True),
    sa.Column('plus_expires_at', sa.DateTime(), nullable=True),
    sa.Column('plus_timezone', sa.String(length=80), nullable=True),
    sa.Column('plus_monthly_pages', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('plus_monthly_pages >= 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), server_default='local', nullable=False),
    sa.Column('mime', sa.String(length=30), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('active_references', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('purged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_expires_at'), 'assets', ['expires_at'], unique=False)
    op.create_index(op.f('ix_assets_last_accessed_at'), 'assets', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_assets_owner_id'), 'assets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_assets_parent_id'), 'assets', ['parent_id'], unique=False)
    op.create_index(op.f('ix_assets_sha256'), 'assets', ['sha256'], unique=False)
    op.create_table('membership_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_key', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_key')
    )
    op.create_index(op.f('ix_membership_operations_owner_id'), 'membership_operations', ['owner_id'], unique=False)
    op.create_table('quota_periods',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_key', sa.String(length=200), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('grants_access', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('granted', sa.Integer(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.CheckConstraint("mode IN ('classic', 'redraw')"),
    sa.CheckConstraint("source IN ('daily', 'membership', 'grant')"),
    sa.CheckConstraint('ends_at > starts_at'),
    sa.CheckConstraint('granted >= used + reserved'),
    sa.CheckConstraint('reserved >= 0'),
    sa.CheckConstraint('used >= 0'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'source_key')
    )
    op.create_index(op.f('ix_quota_periods_owner_id'), 'quota_periods', ['owner_id'], unique=False)
    op.create_index('ix_quota_periods_owner_mode_end', 'quota_periods', ['owner_id', 'mode', 'ends_at'], unique=False)
    op.create_table('translation_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('target_language', sa.String(length=20), nullable=False),
    sa.Column('quota_pages', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_translation_submissions_owner_id'), 'translation_submissions', ['owner_id'], unique=False)
    op.create_table('user_mode_queues',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=True),
    sa.Column('session_sequence', sa.Integer(), nullable=False),
    sa.Column('session_expires_at', sa.DateTime(), nullable=True),
    sa.Column('priority_request_hash', sa.String(length=64), nullable=True),
    sa.Column('next_upload_session', sa.String(length=80), nullable=True),
    sa.Column('next_upload_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'mode')
    )
    op.create_table('file_pages',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('page_index >= 0'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'file_hash', 'page_index')
    )
    op.create_index(op.f('ix_file_pages_asset_id'), 'file_pages', ['asset_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('input_asset_id', sa.String(length=36), nullable=True),
    sa.Column('input_pinned', sa.Boolean(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('page_index', sa.Integer(), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('realtime_until', sa.DateTime(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('change_sequence', sa.BigInteger(), nullable=False),
    sa.Column('output_asset_id', sa.String(length=36), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('target_language', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('phase', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('quota_pages', sa.Integer(), nullable=False),
    sa.Column('quota_kind', sa.String(length=30), nullable=False),
    sa.Column('quota_period_id', sa.String(length=64), nullable=True),
    sa.Column('entitlement', sa.JSON(), nullable=False),
    sa.Column('settlement', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('discard_output', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.String(length=300), nullable=True),
    sa.Column('quality_flags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('unknown_since', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['input_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['output_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quota_period_id'], ['quota_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'operation', 'idempotency_key')
    )
    op.create_index(op.f('ix_jobs_cache_key'), 'jobs', ['cache_key'], unique=False)
    op.create_index(op.f('ix_jobs_change_sequence'), 'jobs', ['change_sequence'], unique=False)
    op.create_index(op.f('ix_jobs_changed_at'), 'jobs', ['changed_at'], unique=False)
    op.create_index(op.f('ix_jobs_input_asset_id'), 'jobs', ['input_asset_id'], unique=False)
    op.create_index(op.f('ix_jobs_owner_id'), 'jobs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_jobs_quota_period_id'), 'jobs', ['quota_period_id'], unique=False)
    op.create_index(op.f('ix_jobs_realtime_until'), 'jobs', ['realtime_until'], unique=False)
    op.create_index(op.f('ix_jobs_source_sha256'), 'jobs', ['source_sha256'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=80), nullable=False),
    sa.Column('output_storage_backend', sa.String(length=20), server_default='local', nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=False),
    sa.Column('call_started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('request_id', sa.String(length=200), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=True),
    sa.Column('cost_state', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('recovered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_job_id'), 'attempts', ['job_id'], unique=False)
    op.create_table('classic_states',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.Column('timings', sa.JSON(), nullable=False),
    sa.Column('artifacts', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('job_requests',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'operation', 'idempotency_key')
    )
    op.create_index(op.f('ix_job_requests_job_id'), 'job_requests', ['job_id'], unique=False)
    op.create_table('job_stages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'name')
    )
    op.create_index(op.f('ix_job_stages_job_id'), 'job_stages', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_stages_status'), 'job_stages', ['status'], unique=False)
    op.create_index('ix_stage_ready', 'job_stages', ['status', 'name', 'available_at'], unique=False)
    op.create_table('submission_items',
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('client_item_id', sa.String(length=100), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('descriptor', sa.JSON(), nullable=False),
    sa.Column('reused', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['translation_submissions.id'], ),
    sa.PrimaryKeyConstraint('submission_id', 'ordinal')
    )
    op.create_index(op.f('ix_submission_items_job_id'), 'submission_items', ['job_id'], unique=False)
    op.create_table('translation_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('output_asset_id', sa.String(length=36), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['output_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'idempotency_key')
    )
    op.create_index('ix_feedback_job', 'translation_feedback', ['job_id'], unique=False)
    op.create_index('ix_feedback_owner_created', 'translation_feedback', ['owner_id', 'created_at'], unique=False)
    op.create_table('upload_reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('expected_sha256', sa.String(length=64), nullable=False),
    sa.Column('expected_size', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=30), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('max_expires_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.String(length=300), nullable=True),
    sa.CheckConstraint('expected_size > 0'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_upload_reservations_expires_at'), 'upload_reservations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_upload_reservations_job_id'), 'upload_reservations', ['job_id'], unique=True)
    op.create_index(op.f('ix_upload_reservations_owner_id'), 'upload_reservations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_upload_reservations_status'), 'upload_reservations', ['status'], unique=False)
    op.create_table('usage_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('period_id', sa.String(length=64), nullable=True),
    sa.Column('quota_kind', sa.String(length=30), nullable=True),
    sa.Column('transaction_key', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['quota_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_key')
    )
    op.create_index('ix_ledger_owner_created', 'usage_ledger', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_ledger_owner_id'), 'usage_ledger', ['owner_id'], unique=False)
    op.create_index(op.f('ix_usage_ledger_period_id'), 'usage_ledger', ['period_id'], unique=False)
    op.create_table('execution_leases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('stage_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=80), nullable=False),
    sa.Column('executor_id', sa.String(length=160), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('resource_pool', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('priority_class', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('estimated_seconds', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(length=24), nullable=True),
    sa.Column('result_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['compute_nodes.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['job_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_leases_completed_at'), 'execution_leases', ['completed_at'], unique=False)
    op.create_index(op.f('ix_execution_leases_expires_at'), 'execution_leases', ['expires_at'], unique=False)
    op.create_index(op.f('ix_execution_leases_job_id'), 'execution_leases', ['job_id'], unique=False)
    op.create_index(op.f('ix_execution_leases_node_id'), 'execution_leases', ['node_id'], unique=False)
    op.create_index(op.f('ix_execution_leases_stage_id'), 'execution_leases', ['stage_id'], unique=False)
    op.create_index('ix_jobs_created_at', 'jobs', ['created_at'])
    op.create_index('ix_jobs_completed_at', 'jobs', ['completed_at'])
    op.create_table('text_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('execution_lease_id', sa.String(length=36), nullable=True),
    sa.Column('group_index', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('request_id', sa.String(length=200), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=True),
    sa.Column('reserved_micros', sa.Integer(), nullable=False),
    sa.Column('accounted_micros', sa.Integer(), nullable=False),
    sa.Column('cost_state', sa.String(length=24), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('accounted_micros >= 0'),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'group_index', 'sequence')
    )
    op.create_index(op.f('ix_text_calls_execution_lease_id'), 'text_calls', ['execution_lease_id'], unique=False)
    op.create_index(op.f('ix_text_calls_job_id'), 'text_calls', ['job_id'], unique=False)
    # ### end Alembic commands ###
    op.execute(sa.text("INSERT INTO scheduler_mutex (id, revision) VALUES (1, 0)"))


def downgrade():
    raise RuntimeError("Cluster baseline has no destructive downgrade")
