import {useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {Icon} from '../icons';
import {Modal} from '../ui/components';
import type {Api} from '../api';
import {fallbackLanguages,supportsLanguage,languageLabel,modeLabels,phaseLabels,type Capabilities,type ReadingCopy,type Job,type Mode,type Page,type Settings} from '../types';
import {getBlob,collectUnusedBlobs,saveCopy,savePosition} from '../library/store';
import {BlobPicture,type ShownImage} from './Images';
import {pageTranslation,taskText,readingImage,resolvePageView,type PageView} from './presentation';
import {pageFrame} from './geometry';
import {TaskActivity} from './TaskActivity';
import {FeedbackForm} from '../ui/Feedback';
import {useChapterStream,pageKey,completeManifest} from './useChapterStream';
import {ThumbnailDirectory} from './ThumbnailDirectory';
import {ComicDirectory} from './ComicDirectory';
import type {ReadingDirectory} from '../library/directory';
import {PageTranslationBar} from './PageTranslationBar';
type Props={directory?:ReadingDirectory;onCatalog?:()=>void;initialView?:PageView;onMarkRead:(id:string)=>Promise<void>;sequence:ReadingCopy[];onActiveCopy:(id:string)=>void;onLoadCopy:(id:string)=>void;sourceStatus?:string;onAcquire:()=>void;onPauseAcquire:()=>void;onNavigate:(id:string,pageId?:string)=>void;copy:ReadingCopy;settings:Settings;setSettings:(s:Settings|((s:Settings)=>Settings))=>void;update:(copy:ReadingCopy)=>void;onBack:()=>void;onTranslate:(mode:Mode,pages:Page[],regenerate?:boolean)=>void;onImport:()=>void;notify:(message:string)=>void;priorityStatus:string;realtimeLimit:number;onClaimReading:()=>void;onOpenQueue:()=>void;onReadingWindow:(pages:Page[],visiblePages:Page[])=>void;caps?:Capabilities;userId?:string;apiOrigin:string;api:Api;busy:boolean;recoveryStatus:string;recovering:boolean;recoveryEnabled:boolean;onRecover:(mode?:Mode,pages?:Page[])=>void;onCancel:(job:Job)=>Promise<void>;preparingPages:string[]};
type Panel='directory'|'translation'|'settings';
export function Reader({directory,onCatalog,initialView,onMarkRead,sourceStatus,onAcquire,onPauseAcquire,sequence,onActiveCopy,onLoadCopy,onNavigate,copy,settings,setSettings,update,onBack,onTranslate,onImport,notify,priorityStatus,realtimeLimit,onClaimReading,onOpenQueue,onReadingWindow,caps,userId,apiOrigin,api,busy,recoveryStatus,recovering,recoveryEnabled,onRecover,onCancel,preparingPages}:Props){
const {index,setIndex,indexRef,anchor,viewport,cells,ends,stream,next,nextOf,preserve,persist,restore,scroll,jump}=useChapterStream({copy,sequence,layout:settings.layout,update,onActiveCopy,onLoadCopy,onMarkRead,notify});
const [panel,setPanel]=useState<Panel>();const [zoom,setZoom]=useState(100);const [pageViews,setPageViews]=useState<Record<string,PageView>>({});const [compare,setCompare]=useState(false);
const [selected,setSelected]=useState(new Set<string>());const [rangeStart,setRangeStart]=useState(1);const [rangeEnd,setRangeEnd]=useState(Math.min(copy.pages.length,24));const [manage,setManage]=useState(false);const [removePage,setRemovePage]=useState<Page>();const [shortcuts,setShortcuts]=useState(false);
const [seekPreview,setSeekPreview]=useState<number>();
const [feedback,setFeedback]=useState<{job:Job;page:Page;number:number}>();const [actual,setActual]=useState<Record<string,ShownImage|undefined>>({});const seenTranslated=useRef(new Set<string>());
const [immersive,setImmersive]=useState(false);const [hidden,setHidden]=useState(false);const hideTimer=useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
const root=useRef<HTMLDivElement>(null);const [viewportSize,setViewportSize]=useState({width:900,height:700});
const page=copy.pages[Math.min(index,copy.pages.length-1)];const viewFor=(p:Page,c=copy)=>resolvePageView(pageViews[pageKey(c,p.id)]??initialView,settings.translationMode);const mode=page?viewFor(page).mode:settings.translationMode;const preference=page?viewFor(page).preference:'auto';const language=caps?.languages.find(l=>l.id===settings.language)?.label??languageLabel(settings.language);
const scopeBase=`${userId??''}:${apiOrigin}:${settings.language}`;const scope=(p:Page,c=copy)=>`${scopeBase}:${pageKey(c,p.id)}`;
const translation=page?pageTranslation(page,mode,settings.language,userId,apiOrigin):undefined;const shown=page&&actual[pageKey(copy,page.id)]?.scope===scope(page)?actual[pageKey(copy,page.id)]:undefined;const shownJob=shown?.job;const pending=translation?.pending;const modeEnabled=!!caps?.modes.find(m=>m.id===mode)?.enabled&&supportsLanguage(caps,mode,settings.language);
const streamPages=useMemo(()=>stream.flatMap(c=>c.pages.map(p=>({page:p,key:pageKey(c,p.id)}))),[stream]);
const decodedSet=useMemo(()=>{const set=new Set<string>();let pixels=0;const current=streamPages.findIndex(p=>p.key===pageKey(copy,page?.id??''));for(const delta of [0,1,-1,2,-2]){const item=streamPages[current+delta];if(!item||settings.layout==='single'&&delta!==0)continue;const pagePixels=item.page.width*item.page.height*(compare?2:1);if(pixels+pagePixels>32_000_000&&set.size)continue;set.add(item.key);pixels+=pagePixels;}return set;},[index,streamPages,settings.layout,compare,copy.id]);
useEffect(()=>{setSelected(new Set());setManage(false);setRangeStart(1);setRangeEnd(Math.min(copy.pages.length,24));setFeedback(undefined);},[copy.id]);
useEffect(()=>{setPageViews({});setActual({});setFeedback(undefined);seenTranslated.current.clear();},[scopeBase]);
useEffect(()=>{if(!viewport.current)return;const observer=new ResizeObserver(([entry])=>{preserve();setViewportSize({width:entry.contentRect.width,height:entry.contentRect.height});});observer.observe(viewport.current);return()=>observer.disconnect();},[!!page]);
const frame=(p:Page)=>pageFrame(p,viewportSize,settings.fit,zoom,compare);
const contentWidth=streamPages.reduce((width,p)=>Math.max(width,frame(p.page).width),0);
useLayoutEffect(()=>{restore();},[viewportSize,settings.fit,zoom,compare,settings.layout,!!page]);
useEffect(()=>()=>{clearTimeout(hideTimer.current);},[]);
useEffect(()=>{if(!immersive||panel||feedback||shortcuts){setHidden(false);clearTimeout(hideTimer.current);return;}reveal();},[immersive,panel,feedback,shortcuts]);
function reveal(){setHidden(false);clearTimeout(hideTimer.current);if(immersive&&!panel&&!feedback&&!shortcuts)hideTimer.current=setTimeout(()=>{if(!root.current?.querySelector('.nc-reader-controls :focus'))setHidden(true);},2400);}
useEffect(()=>{function key(e:KeyboardEvent){const t=e.target as HTMLElement;if(t.closest('input,select,textarea,[contenteditable="true"],dialog,[role="group"]')||e.ctrlKey||e.metaKey||e.altKey||document.querySelector('dialog[open]'))return;let next:number|undefined;if(e.key==='ArrowRight')next=indexRef.current+(settings.direction==='rtl'?-1:1);if(e.key==='ArrowLeft')next=indexRef.current+(settings.direction==='rtl'?1:-1);if(e.key==='PageDown'||e.key==='j')next=indexRef.current+1;if(e.key==='PageUp'||e.key==='k')next=indexRef.current-1;if(e.key==='Home')next=0;if(e.key==='End')next=copy.pages.length-1;if(next!=null){e.preventDefault();jump(next);}if(e.key.toLowerCase()==='o'){setPreference('original');setCompare(false);}if(e.key.toLowerCase()==='f'){e.preventDefault();void fullscreen();}if(e.key==='Escape'){setPanel(undefined);reveal();}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[settings.direction,settings.layout,copy,immersive,panel,index,pageViews]);
useEffect(()=>{
 const upcoming=copy.pages.slice(index);
 const recent=[...sequence].filter(c=>c.id!==copy.id).sort((a,b)=>(b.lastReadAt??0)-(a.lastReadAt??0)).slice(0,3).flatMap(c=>c.pages);
 const ordered=[...new Map([...upcoming,...recent,...copy.pages.slice(0,index)].map(p=>[p.id,p])).values()];
 const nearby=streamPages.filter(p=>decodedSet.has(p.key)).map(p=>p.page);
 onReadingWindow(ordered,nearby);
},[index,copy.pages,sequence,decodedSet,streamPages,onReadingWindow]);
async function fullscreen(){if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen().catch(()=>notify('此浏览器暂时无法进入全屏。'));}
async function exportPage(){if(!page)return;const key=shown?.key??page.blobKey;if(!key){notify('当前图片尚未就绪。');return;}try{const blob=await getBlob(key);if(!blob)throw Error('本地图片已清理，请重新获取。');const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${copy.title}-${index+1}-${shownJob?`${shownJob.mode}-${shownJob.target_language}`:'original'}.${blob.type==='image/jpeg'?'jpg':blob.type==='image/webp'?'webp':'png'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){notify((e as Error).message);}}
function movePage(pageId:string,delta:number){preserve();const pages=[...copy.pages];const at=pages.findIndex(p=>p.id===pageId);const to=at+delta;if(to<0||to>=pages.length)return;[pages[at],pages[to]]=[pages[to],pages[at]];savePosition(copy.id,copy.manifestRevision+1,anchor.current);update({...copy,manifestRevision:copy.manifestRevision+1,pages});setIndex(Math.max(0,pages.findIndex(p=>p.id===page?.id)));requestAnimationFrame(restore);}
function togglePanel(next:Panel){reveal();setPanel(v=>v===next?undefined:next);}
function setPreference(preference:PageView['preference']){if(page)setPageViews(views=>({...views,[pageKey(copy,page.id)]:{...resolvePageView(views[pageKey(copy,page.id)]??initialView,settings.translationMode),preference}}));}
function selectView(value:'original'|Mode){
  if(!page)return;
  preserve();
  setPageViews(views=>({...views,[pageKey(copy,page.id)]:{mode:value==='original'?mode:value,preference:value==='original'?'original':'translation'}}));
  if(value==='original')setCompare(false);
  else if(!pageTranslation(page,value,settings.language,userId,apiOrigin).ready&&recoveryEnabled)onRecover(value,[page]);
}
function translate(rerun=false,p=page,translationMode=mode){if(p)onTranslate(translationMode,[p],rerun);}
if(!page)return <div className="nc-reader"><header className="nc-reader-top"><button className="icon-button" aria-label="返回我的漫画" onClick={onBack}><Icon name="arrow" style={{transform:'rotate(180deg)'}}/></button><button className="icon-button" aria-label="打开目录" onClick={()=>togglePanel('directory')}><Icon name="list"/></button><h1>{copy.title}</h1></header><div className="nc-empty"><h2>{sourceStatus??'这份副本还没有可读页面'}</h2>{copy.sourceEntryId?<><button className="button primary" onClick={onAcquire}>授权并继续采集</button><button className="button secondary" onClick={onPauseAcquire}>暂停采集</button></>:<button className="button primary" onClick={onImport}>导入漫画</button>}<button className="button secondary" onClick={()=>setPanel('directory')}>查看作品目录</button></div>{panel==='directory'&&<><button className="nc-drawer-scrim" aria-label="关闭阅读面板" onClick={()=>setPanel(undefined)}/><aside className="nc-reader-drawer left" aria-label="漫画目录"><div className="nc-drawer-title"><h2>目录</h2><button className="icon-button" aria-label="关闭面板" onClick={()=>setPanel(undefined)}><Icon name="close"/></button></div><ComicDirectory directory={directory??{title:copy.title,entries:[],catalogCount:0}} index={0} pageCount={0} onNavigate={onNavigate} onCatalog={onCatalog}><p>页面尚未就绪</p></ComicDirectory></aside></>}</div>;
const task=translation!.latest;
const preparing=preparingPages.includes(page.id);
const stateNote=preparing?'正在准备本页翻译':pending?.status==='awaiting_upload'?'原图尚未上传，请保持本机页面打开':pending?.status==='validating_upload'?'服务器正在校验原图':pending?.status==='outcome_unknown'?'结果待核实':pending?.status==='queued'?(shownJob?.mode==='classic'&&mode==='redraw'?'先看常规译图':'排队中'):pending?.status==='running'?(shownJob?.mode==='classic'&&mode==='redraw'?'先看常规译图':shownJob?'正在更新译图':'正在翻译，先读原图'):translation!.expired?'最新译图已过期或删除':task?.status==='failed'?'本页翻译失败':task?.status==='no_text'?'未检测到文字':task?.status==='cancelled'?'翻译已取消':shownJob?.quality_flags?.includes('unrecognized_regions')?'部分文字保留原文':translation!.ready&&!shownJob?'译图已就绪':translation!.result?.output_asset_id&&!translation!.ready?'正在恢复译图':'';
return <div ref={root} className={`nc-reader ${immersive?'is-immersive':''} ${hidden?'controls-hidden':''}`} data-background={settings.readerBackground} onPointerMove={e=>{
  const target=e.target as HTMLElement;
  if(target.closest('.nc-reader-status'))return;
  const bounds=e.currentTarget.getBoundingClientRect();
  if(target.closest('.nc-reader-controls')||e.clientY-bounds.top<8||bounds.bottom-e.clientY<8)reveal();
}} onFocusCapture={e=>{if((e.target as HTMLElement).closest('.nc-reader-controls'))reveal();}}>
<header className="nc-reader-top nc-reader-controls"><button className="icon-button" aria-label="返回我的漫画" onClick={()=>{preserve();persist();onBack();}}><Icon name="arrow" style={{transform:'rotate(180deg)'}}/></button><button className="icon-button nc-directory-entry" aria-label="打开目录" aria-expanded={panel==='directory'} onClick={()=>togglePanel('directory')}><Icon name="list"/></button><h1 title={copy.title}>{copy.title}</h1><button className="button secondary nc-queue-link" onClick={onOpenQueue}><Icon name="list" size={18}/><span>翻译队列</span></button><button className="button secondary nc-mode-button" aria-label={`默认翻译 · ${modeLabels[settings.translationMode]} · ${language}`} title="默认翻译设置" aria-expanded={panel==='translation'} onClick={()=>togglePanel('translation')}><Icon name={settings.translationMode==='classic'?'globe':'spark'} size={18}/><span>{modeLabels[settings.translationMode]} · {language}</span><Icon name="chevron" size={15}/></button><button className="icon-button" aria-label="阅读设置" aria-expanded={panel==='settings'} onClick={()=>togglePanel('settings')}><Icon name="settings"/></button></header>
{sourceStatus&&<div className="nc-source-status" role="status"><span>{sourceStatus}</span><button onClick={onAcquire}>授权并继续</button><button onClick={onPauseAcquire}>暂停采集</button></div>}<div className="nc-auto-status" role="status" hidden={!priorityStatus}><span>{priorityStatus}</span><button className="button secondary small" onClick={onClaimReading}>优先当前阅读</button></div>
<PageTranslationBar page={page} number={index+1} mode={mode} selectedView={preference==='translation'?mode:preference==='original'?'original':shownJob?.mode??'original'} shownJob={shownJob} languageId={settings.language} ownerId={userId} origin={apiOrigin} note={stateNote} preparing={preparing} busy={busy} caps={caps} onView={selectView} onTranslate={value=>{preserve();setPageViews(views=>({...views,[pageKey(copy,page.id)]:{mode:value,preference:'translation'}}));const t=pageTranslation(page,value,settings.language,userId,apiOrigin);translate(!!t.latest,page,value);}} onProgress={()=>setPanel('translation')} onFeedback={()=>shownJob&&setFeedback({job:{...shownJob},page,number:index+1})}/>

<div className="nc-reading-viewport" ref={viewport} onScroll={scroll} data-decoded-pages={decodedSet.size} data-page-count={copy.pages.length} onClick={e=>{if(e.target===e.currentTarget||(e.target as HTMLElement).classList.contains('nc-reading-surface')){if(panel)setPanel(undefined);else reveal();}}}>
<div className="nc-reading-surface" style={{minWidth:contentWidth+24}}>{stream.map((chapter,chapterIndex)=><div className="nc-stream-chapter" key={chapter.id} data-copy-id={chapter.id}>{chapterIndex>0&&<div className="nc-chapter-heading"><span>接着阅读</span><h2>{chapter.title}</h2></div>}{chapter.pages.map((p,n)=>{if(settings.layout==='single'&&n!==index)return null;const pageView=viewFor(p,chapter);const identity=scope(p,chapter);const cellKey=pageKey(chapter,p.id);const wantTranslation=pageView.preference==='translation'||pageView.preference==='auto'&&(settings.autoShowTranslation||seenTranslated.current.has(identity));const {key:targetKey,job:targetJob}=readingImage(p,pageView.mode,wantTranslation,settings.language,userId,apiOrigin,!initialView);
const {width,height}=frame(p);return <div className="nc-manga-page" key={cellKey} ref={node=>{if(node)cells.current.set(cellKey,node);else cells.current.delete(cellKey);}} data-page-id={p.id} data-page-index={n} style={{width}}><div className={`nc-page-picture ${compare?'comparison':''}`} style={{height}}>{decodedSet.has(cellKey)?<>{compare&&<div className="nc-comparison-pane"><BlobPicture scope={`${cellKey}:compare`} blobKey={p.blobKey} alt={`第 ${n+1} 页`} onImport={onImport} error={p.fetchError}/></div>}<div className="nc-comparison-pane"><BlobPicture scope={identity} blobKey={targetKey} job={targetJob} alt={`第 ${n+1} 页`} error={p.fetchError} sourceUrl={chapter.sourceUrl} onImport={onImport} onShown={image=>{if(image?.job)seenTranslated.current.add(identity);setActual(prev=>prev[cellKey]?.key===image?.key&&prev[cellKey]?.scope===image?.scope?prev:{...prev,[cellKey]:image});}}/></div></>:<div className="nc-image-placeholder"><Icon name="image"/><span>第 {n+1} 页 · 滚动到此处时加载</span></div>}</div></div>;})}<div className="nc-reader-end" ref={node=>{if(node)ends.current.set(chapter.id,node);else ends.current.delete(chapter.id);}}>
<span aria-hidden="true">✦</span>
{!chapter.pages.length?<><p>{directory?.entries.find(e=>e.copyId===chapter.id)?.error??directory?.entries.find(e=>e.copyId===chapter.id)?.status??'正在准备这一话的页面…'}</p><button className="button secondary" onClick={()=>{preserve();persist();onNavigate(chapter.id);}}>查看采集状态</button></>:!completeManifest(chapter)?<><p>当前已展示 {chapter.pages.length} 页，等待补齐这一话。</p><small>页面清单完整后会自动接上下一话</small></>:settings.layout==='single'&&index<copy.pages.length-1?<p>第 {index+1} 页</p>:<p>{chapterIndex<stream.length-1?'继续下滑，阅读下一话':nextOf(chapter)?'继续阅读下一话':'已到当前内容末尾'}</p>}
</div></div>)}</div></div>
{panel&&<><button className="nc-drawer-scrim" aria-label="关闭阅读面板" onClick={()=>setPanel(undefined)}/><aside className={`nc-reader-drawer ${panel==='directory'?'left':'right'}`} aria-label={{directory:'漫画目录',translation:'翻译选项',settings:'阅读设置'}[panel]}><div className="nc-drawer-title"><h2>{{directory:'目录',translation:'翻译',settings:'阅读设置'}[panel]}</h2><button className="icon-button" aria-label="关闭面板" onClick={()=>setPanel(undefined)}><Icon name="close"/></button></div>
{panel==='directory'?<ComicDirectory directory={directory??{title:copy.title,entries:[],catalogCount:0}} index={index} pageCount={copy.pages.length} onNavigate={(id,pageId)=>{preserve();persist();onNavigate(id,pageId);}} onCatalog={onCatalog}><div className="nc-directory-intro"><span>第 {index+1} / {copy.pages.length} 页</span><button className="text-link" onClick={()=>setManage(v=>!v)}>{manage?'完成管理':'管理页面'}</button></div><ThumbnailDirectory pages={copy.pages} index={index} mode={settings.translationMode} language={settings.language} ownerId={userId} origin={apiOrigin} selected={selected} manage={manage} onSelect={id=>setSelected(prev=>{const next=new Set(prev);if(next.has(id))next.delete(id);else next.add(id);return next;})} onJump={n=>{jump(n);if(window.innerWidth<760)setPanel(undefined);}} onMove={movePage} onRemove={setRemovePage}/><div className="nc-directory-footer"><button className={`button ${selected.size?'primary':'secondary'} full`} onClick={()=>{setManage(true);setPanel('translation');}}>{selected.size?`翻译选中的 ${selected.size} 页`:'选择翻译范围'}</button></div></ComicDirectory>:<div className="nc-drawer-content">
{panel==='translation'?<><Choice label="默认翻译方式" value={settings.translationMode} options={([{id:'classic',label:'常规翻译'},{id:'redraw',label:'AI 重绘'}] as const)} onChange={translationMode=>{if(!supportsLanguage(caps,translationMode,settings.language)){notify('此目标语言支持常规翻译，暂不支持 AI 重绘。');return;}setSettings(s=>({...s,translationMode}));}}/><p className="nc-muted nc-default-mode-note">用于预存和批量翻译。本页查看方式在阅读区单独切换。{!supportsLanguage(caps,'redraw',settings.language)&&'当前目标语言支持常规翻译，暂不支持 AI 重绘。'}</p>{(caps?.languages.length??fallbackLanguages.length)<=4?<Choice label="目标语言" value={settings.language} options={caps?.languages??fallbackLanguages} onChange={language=>setSettings(s=>({...s,language,translationMode:supportsLanguage(caps,s.translationMode,language)?s.translationMode:'classic'}))}/>:<label className="field">目标语言<select aria-label="翻译目标语言" value={settings.language} onChange={e=>setSettings(s=>({...s,language:e.target.value,translationMode:supportsLanguage(caps,s.translationMode,e.target.value)?s.translationMode:'classic'}))}>{(caps?.languages??fallbackLanguages).map(l=><option key={l.id} value={l.id}>{l.label}</option>)}</select></label>}
<div className="nc-reader-option"><div><b>完成后自动显示译图</b><p>手动查看原图时，保持你的选择。</p></div><button role="switch" aria-checked={settings.autoShowTranslation} aria-label="完成后自动显示译图" className={`switch ${settings.autoShowTranslation?'on':''}`} onClick={()=>setSettings(s=>({...s,autoShowTranslation:!s.autoShowTranslation}))}><i/></button></div>
<section className="nc-current-task"><h3>当前第 {index+1} 页 · {modeLabels[mode]}</h3><b>{(preparing||pending&&pending.status!=='outcome_unknown')&&<TaskActivity waiting={!preparing&&pending?.status==='queued'}/>} {preparing?'正在准备翻译':pending?taskText(pending):taskText(task)}</b>{pending?.status==='running'&&<p>{phaseLabels[pending.phase]??'正在处理这一页'}</p>}{(pending??task)?.error&&<p className="nc-attention">{(pending??task)!.error!.message}</p>}{pending?.status==='outcome_unknown'&&<p>请求结果正在核实。此页暂停重复提交，其余页面可以继续阅读。</p>}{shownJob&&<p>{shownJob.mode!==mode?'当前保留常规译图，AI 重绘就绪后显示。':shownJob.id===translation!.result?.id?'当前显示最新译图。':'当前显示已有译图，新结果读取完成后更新。'}{shownJob.settlement==='released'||shownJob.settlement==='free'?'本页未扣页数额度。':''}</p>}{page.ownerId===userId&&page.apiOrigin===apiOrigin&&page.translationError&&<p className="nc-attention">{page.translationError}</p>}{translation!.expired&&<p>最新译图已过期或删除，可重新翻译。</p>}<div className="nc-stack-actions">{translation!.ready&&<button className="button secondary" onClick={()=>{setPreference('translation');setPanel(undefined);}}>查看最新译图</button>}{pending&&['awaiting_upload','validating_upload','queued','running'].includes(pending.status)?<button className="button secondary" disabled={pending.cancel_requested} onClick={()=>void onCancel(pending)}>{pending.cancel_requested?'正在停止':'停止此页任务'}</button>:!pending&&<button className="button primary" disabled={!modeEnabled||busy} onClick={()=>translate(!!task)}><Icon name={task?'refresh':'globe'} size={17}/>{task?'重新翻译 · 查看范围':'翻译本页'}</button>}{shownJob&&<button className="text-link" onClick={()=>setFeedback({job:{...shownJob},page,number:index+1})}>反馈这页译图 · 免费</button>}</div></section>
<details className="nc-reader-details" open={selected.size>0||manage}><summary>翻译更多页面{selected.size?` · 已选 ${selected.size} 页`:''}</summary><div className="nc-range"><label>起始页<input aria-label="翻译起始页" type="number" min={1} max={copy.pages.length} value={rangeStart} onChange={e=>setRangeStart(Number(e.target.value))}/></label><span>—</span><label>结束页<input aria-label="翻译结束页" type="number" min={rangeStart} max={copy.pages.length} value={rangeEnd} onChange={e=>setRangeEnd(Number(e.target.value))}/></label></div><button className="button secondary full" onClick={()=>{const start=Math.max(1,Math.min(copy.pages.length,Math.trunc(rangeStart)||1));const end=Math.max(start,Math.min(copy.pages.length,Math.trunc(rangeEnd)||start));setSelected(new Set(copy.pages.slice(start-1,end).map(p=>p.id)));}}>选中范围</button>{!!selected.size&&<div className="nc-stack-actions"><button className="button primary full" disabled={!caps?.modes.find(m=>m.id===settings.translationMode)?.enabled||busy} onClick={()=>onTranslate(settings.translationMode,copy.pages.filter(p=>selected.has(p.id)))}>翻译选中 {selected.size} 页 · 查看范围</button><button className="text-link" onClick={()=>setSelected(new Set())}>清除选择</button></div>}</details>
<section className="nc-current-task"><h3>提前准备这一章</h3><p>最多 {realtimeLimit} 页获得实时阅读优先。预存任务在后台持续处理；已确认清单会根据阅读位置调整本人顺序。</p><button className="button primary full" disabled={!caps?.modes.find(m=>m.id===settings.translationMode)?.enabled||busy} onClick={()=>onTranslate(settings.translationMode,copy.pages)}><Icon name="upload" size={17}/>预存本章 {copy.pages.length} 页</button><button className="button secondary full" style={{marginTop:8}} onClick={onOpenQueue}>管理两种翻译队列</button></section><div className="nc-recover"><button className="button secondary full" onClick={()=>onRecover(mode)} disabled={recovering||!recoveryEnabled}><Icon name="refresh" size={17}/>{recovering?'正在恢复…':'查找已有翻译'}</button><p role="status">{recoveryStatus||'登录后按原图标识恢复此漫画的翻译。'}</p></div>
</>:<><Choice label="阅读布局" value={settings.layout} options={[{id:'continuous',label:'连续阅读'},{id:'single',label:'单页阅读'}]} onChange={layout=>{preserve();setSettings(s=>({...s,layout}));}}/><Choice label="阅读方向" value={settings.direction} options={[{id:'rtl',label:'从右向左'},{id:'ltr',label:'从左向右'}]} onChange={direction=>setSettings(s=>({...s,direction}))}/><Choice label="图片适应方式" value={settings.fit} options={[{id:'window',label:'适应窗口'},{id:'width',label:'铺满宽度'}]} onChange={fit=>{preserve();setSettings(s=>({...s,fit}));}}/><div className="nc-reader-option"><b>缩放</b><div className="nc-inline"><button className="icon-button" aria-label="缩小" disabled={zoom<=40} onClick={()=>{preserve();setZoom(z=>z-10);}}><Icon name="minus"/></button><span>{zoom}%</span><button className="icon-button" aria-label="放大" disabled={zoom>=200} onClick={()=>{preserve();setZoom(z=>z+10);}}><Icon name="plus"/></button></div></div><Choice label="阅读背景" value={settings.readerBackground} options={[{id:'gray',label:'浅灰'},{id:'paper',label:'纸白'},{id:'night',label:'夜色'}]} onChange={readerBackground=>setSettings(s=>({...s,readerBackground}))}/><div className="nc-reader-option"><div><b>并排对照</b><p>原图与当前模式最新译图</p></div><button className={`switch ${compare?'on':''}`} role="switch" aria-label="并排对照" aria-checked={compare} onClick={()=>{preserve();setCompare(v=>!v);if(!compare)setPreference('translation');}}><i/></button></div><div className="nc-reader-option"><div><b>沉浸阅读</b><p>空闲时收起工具，轻点空白处唤回。</p></div><button className={`switch ${immersive?'on':''}`} role="switch" aria-label="沉浸阅读" aria-checked={immersive} onClick={()=>setImmersive(v=>!v)}><i/></button></div><div className="nc-stack-actions"><button className="button secondary" onClick={()=>void fullscreen()}><Icon name="expand"/>全屏阅读</button><button className="button secondary" onClick={()=>void exportPage()}><Icon name="download"/>保存当前图片</button><button className="button secondary" onClick={()=>setShortcuts(true)}><Icon name="keyboard"/>键盘快捷键</button></div></>}
</div>}</aside></>}
<footer className="nc-reader-bottom nc-reader-controls"><div className="nc-page-navigation"><button className="icon-button" aria-label="上一页" disabled={index===0} onClick={()=>jump(index-1)}><Icon name="chevron" style={{transform:'rotate(180deg)'}}/></button><label><input aria-label="跳转页码" type="number" min={1} max={copy.pages.length} value={index+1} onChange={e=>jump(Number(e.target.value)-1)}/><span>/ {copy.pages.length}</span></label><button className="icon-button" aria-label="下一页" disabled={index>=copy.pages.length-1&&!next} onClick={()=>jump(index+1)}><Icon name="chevron"/></button></div><div className="nc-seek" onPointerLeave={()=>setSeekPreview(undefined)}><div className="nc-seek-track"><span style={{width:`${(index+1)/copy.pages.length*100}%`}}/></div><input type="range" aria-label="阅读进度" aria-valuetext={`第 ${index+1} 页，共 ${copy.pages.length} 页`} min={1} max={copy.pages.length} step={1} value={index+1} disabled={copy.pages.length===1} onChange={e=>jump(Number(e.target.value)-1)} onPointerMove={e=>{const bounds=e.currentTarget.getBoundingClientRect();setSeekPreview(Math.round(Math.max(0,Math.min(1,(e.clientX-bounds.left)/bounds.width))*(copy.pages.length-1)));}}/>{seekPreview!=null&&<span className="nc-seek-preview" style={{left:`${copy.pages.length===1?0:seekPreview/(copy.pages.length-1)*100}%`}}>第 {seekPreview+1} 页</span>}</div><span className="nc-read-percent">{Math.round((index+1)/copy.pages.length*100)}%</span></footer>
{hidden&&<button className="nc-reveal" aria-label="显示阅读工具" onClick={reveal}><Icon name="settings" size={20}/></button>}
{feedback&&<FeedbackForm key={feedback.job.id} api={api} job={feedback.job} pageNumber={feedback.number} onClose={()=>setFeedback(undefined)} canRerun={!pageTranslation(copy.pages.find(p=>p.id===feedback.page.id)??feedback.page,feedback.job.mode,feedback.job.target_language,userId,apiOrigin).pending&&!!caps?.modes.find(m=>m.id===feedback.job.mode)?.enabled&&!busy} onRerun={()=>{const p=copy.pages.find(p=>p.id===feedback.page.id);setFeedback(undefined);if(p)translate(true,p,feedback.job.mode);}}/>}
{shortcuts&&<Modal title="阅读快捷键" onClose={()=>setShortcuts(false)}><div className="shortcut-list"><p><span>← / →</span><b>按设置方向翻页</b></p><p><span>Page Up / Page Down</span><b>上一页 / 下一页</b></p><p><span>Home / End</span><b>首 / 末页</b></p><p><span>O</span><b>查看原图</b></p><p><span>F</span><b>切换全屏</b></p><p><span>Esc</span><b>关闭面板、唤回工具</b></p></div></Modal>}
{removePage&&<Modal title="移除这一页？" subtitle="从本地清单移除图片。已提交的服务器任务仍会保留。" onClose={()=>setRemovePage(undefined)}><button className="button danger full" onClick={async()=>{try{const keys=[removePage.blobKey,...Object.values(removePage.outputBlobs)].filter((key):key is string=>!!key);const pages=copy.pages.filter(p=>p.id!==removePage.id);const next=Math.max(0,Math.min(index,pages.length-1));anchor.current={pageId:pages[next]?.id??'',relativeOffset:0};savePosition(copy.id,copy.manifestRevision+1,anchor.current);const changed={...copy,manifestRevision:copy.manifestRevision+1,pages,...anchor.current};await saveCopy(changed);update(changed);await collectUnusedBlobs(keys);setIndex(next);setSelected(s=>{const n=new Set(s);n.delete(removePage.id);return n;});setRemovePage(undefined);}catch(e){notify((e as Error).message);}}}>确认移除</button></Modal>}
</div>;
}
function Choice<T extends string>({label,value,options,onChange}:{label:string;value:T;options:readonly {id:T;label:string}[];onChange:(value:T)=>void}){
  return <div className="field"><span>{label}</span><div className="segmented nc-reader-choices" role="group" aria-label={label}>{options.map(option=><button key={option.id} className={value===option.id?'active':''} aria-pressed={value===option.id} onClick={()=>onChange(option.id)}>{option.label}</button>)}</div></div>;
}
