import {translationNotice} from '../translation/notice';
import {useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {Icon} from '../icons';
import {Modal} from '../ui/components';
import type {Api} from '../api';
import {fallbackLanguages,supportsLanguage,languageLabel,modeLabels,type Capabilities,type ReadingCopy,type Job,type Mode,type Page,type Settings} from '../types';
import {getBlob,collectUnusedBlobs,saveCopy,savePosition} from '../library/store';
import {BlobPicture,type ShownImage} from './Images';
import {pageTranslation,readingImage,resolvePageView,type PageView} from './presentation';
import {pageFrame} from './geometry';
import {ImageTranslationStatus} from './ImageTranslationStatus';
import type {ReadingTarget,TranslationState} from '../translation/automatic';
import {FeedbackForm} from '../ui/Feedback';
import {useChapterStream,pageKey,completeManifest} from './useChapterStream';
import {ThumbnailDirectory} from './ThumbnailDirectory';
import {ComicDirectory} from './ComicDirectory';
import type {ReadingDirectory} from '../library/directory';
import {PageTranslationBar} from './PageTranslationBar';
type Props={directory?:ReadingDirectory;onCatalog?:()=>void;initialView?:PageView;onMarkRead:(id:string)=>Promise<void>;sequence:ReadingCopy[];onActiveCopy:(id:string)=>void;onLoadCopy:(id:string)=>void;sourceStatus?:string;onAcquire:()=>void;onPauseAcquire:()=>void;onNavigate:(id:string,pageId?:string)=>void;copy:ReadingCopy;settings:Settings;setSettings:(s:Settings|((s:Settings)=>Settings))=>void;update:(copy:ReadingCopy)=>void;onBack:()=>void;onRetry:(page:Page,mode:Mode,copyId?:string)=>void|Promise<void>;onUpgrade:()=>void;onLogin:()=>void;translationState:(copyId:string,page:Page,mode:Mode)=>TranslationState|undefined;onImport:()=>void;notify:(message:string)=>void;onReadingWindow:(targets:ReadingTarget[],visiblePages:Page[],immediate?:boolean)=>void;caps?:Capabilities;userId?:string;apiOrigin:string;api:Api;busy:boolean;};
type Panel='directory'|'translation'|'settings';
export function Reader({directory,onCatalog,initialView,onMarkRead,sourceStatus,onAcquire,onPauseAcquire,sequence,onActiveCopy,onLoadCopy,onNavigate,copy,settings,setSettings,update,onBack,onRetry,onUpgrade,onLogin,translationState,onImport,notify,onReadingWindow,caps,userId,apiOrigin,api,busy}:Props){
const {index,setIndex,indexRef,anchor,viewport,cells,ends,stream,next,nextOf,preserve,persist,restore,scroll,jump,navigationReason}=useChapterStream({copy,sequence,layout:settings.layout,update,onActiveCopy,onLoadCopy,onMarkRead,notify});
const [panel,setPanel]=useState<Panel>();const [zoom,setZoom]=useState(100);const [pageViews,setPageViews]=useState<Record<string,PageView>>({});const [compare,setCompare]=useState(false);
const [manage,setManage]=useState(false);const [removePage,setRemovePage]=useState<Page>();const [shortcuts,setShortcuts]=useState(false);
const [feedback,setFeedback]=useState<{job:Job;page:Page;number:number}>();const [actual,setActual]=useState<Record<string,ShownImage|undefined>>({});
const [immersive,setImmersive]=useState(false);const [hidden,setHidden]=useState(false);const hideTimer=useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
const root=useRef<HTMLDivElement>(null);const [viewportSize,setViewportSize]=useState({width:900,height:700});
const page=copy.pages[Math.min(index,copy.pages.length-1)];const viewFor=(p:Page,c=copy)=>resolvePageView(pageViews[pageKey(c,p.id)]??initialView,settings.translationMode);const mode=page?viewFor(page).mode:settings.translationMode;const preference=page?viewFor(page).preference:'auto';const language=caps?.languages.find(l=>l.id===settings.language)?.label??languageLabel(settings.language);
const scopeBase=`${userId??''}:${apiOrigin}:${settings.language}`;const scope=(p:Page,c=copy)=>`${scopeBase}:${pageKey(c,p.id)}`;
const shown=page&&actual[pageKey(copy,page.id)]?.scope===scope(page)?actual[pageKey(copy,page.id)]:undefined;const shownJob=shown?.job;
const streamPages=useMemo(()=>stream.flatMap(c=>c.pages.map(p=>({page:p,key:pageKey(c,p.id),copyId:c.id}))),[stream]);
const decodedSet=useMemo(()=>{const set=new Set<string>();let pixels=0;const current=streamPages.findIndex(p=>p.key===pageKey(copy,page?.id??''));for(const delta of [0,1,-1,2,-2]){const item=streamPages[current+delta];if(!item||settings.layout==='single'&&delta!==0)continue;const pagePixels=item.page.width*item.page.height*(compare?2:1);if(pixels+pagePixels>32_000_000&&set.size)continue;set.add(item.key);pixels+=pagePixels;}return set;},[index,streamPages,settings.layout,compare,copy.id]);
useEffect(()=>{setManage(false);setFeedback(undefined);},[copy.id]);
useEffect(()=>{setPageViews({});setActual({});setFeedback(undefined);},[scopeBase]);
useEffect(()=>{if(!viewport.current)return;const observer=new ResizeObserver(([entry])=>{preserve();setViewportSize({width:entry.contentRect.width,height:entry.contentRect.height});});observer.observe(viewport.current);return()=>observer.disconnect();},[!!page]);
const frame=(p:Page)=>pageFrame(p,viewportSize,settings.fit,zoom,compare);
const contentWidth=streamPages.reduce((width,p)=>Math.max(width,frame(p.page).width),0);
useLayoutEffect(()=>{restore();},[viewportSize,settings.fit,zoom,compare,settings.layout,!!page]);
useEffect(()=>()=>{clearTimeout(hideTimer.current);},[]);
useEffect(()=>{if(!immersive||panel||feedback||shortcuts){setHidden(false);clearTimeout(hideTimer.current);return;}reveal();},[immersive,panel,feedback,shortcuts]);
useEffect(()=>{
 if(panel!=='translation')return;
 const bubble=root.current?.querySelector<HTMLElement>('.nc-translation-popover');
 const trigger=root.current?.querySelector<HTMLButtonElement>('.nc-translation-trigger');
 bubble?.querySelector<HTMLButtonElement>('[aria-pressed="true"]')?.focus();
 function outside(e:PointerEvent){const target=e.target as Node;if(!bubble?.contains(target)&&!trigger?.contains(target))setPanel(undefined);}
 function escape(e:KeyboardEvent){if(e.key==='Escape'){e.preventDefault();e.stopPropagation();setPanel(undefined);trigger?.focus();}}
 document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape,true);
 return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape,true);};
},[panel]);
function reveal(){setHidden(false);clearTimeout(hideTimer.current);if(immersive&&!panel&&!feedback&&!shortcuts)hideTimer.current=setTimeout(()=>{if(!root.current?.querySelector('.nc-reader-controls :focus'))setHidden(true);},2400);}
useEffect(()=>{function key(e:KeyboardEvent){const t=e.target as HTMLElement;if(t.closest('input,select,textarea,[contenteditable="true"],dialog,[role="group"]')||e.ctrlKey||e.metaKey||e.altKey||document.querySelector('dialog[open]'))return;let next:number|undefined;if(e.key==='ArrowRight')next=indexRef.current+(settings.direction==='rtl'?-1:1);if(e.key==='ArrowLeft')next=indexRef.current+(settings.direction==='rtl'?1:-1);if(e.key==='PageDown'||e.key==='j')next=indexRef.current+1;if(e.key==='PageUp'||e.key==='k')next=indexRef.current-1;if(e.key==='Home')next=0;if(e.key==='End')next=copy.pages.length-1;if(next!=null){e.preventDefault();jump(next);}if(e.key.toLowerCase()==='o'){setPreference('original');setCompare(false);}if(e.key.toLowerCase()==='f'){e.preventDefault();void fullscreen();}if(e.key==='Escape'){setPanel(undefined);reveal();}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[settings.direction,settings.layout,copy,immersive,panel,index,pageViews]);
useEffect(()=>{
 const start=streamPages.findIndex(p=>p.key===pageKey(copy,page?.id??''));
 const targets=streamPages.slice(Math.max(0,start),Math.max(0,start)+3).filter(p=>resolvePageView(pageViews[p.key]??initialView,settings.translationMode).preference!=='original').map(p=>({...p,mode:resolvePageView(pageViews[p.key]??initialView,settings.translationMode).mode}));
 onReadingWindow(targets,streamPages.filter(p=>decodedSet.has(p.key)).map(p=>p.page),navigationReason.current==='direct');
},[index,copy.id,streamPages,decodedSet,pageViews,settings.translationMode,initialView,onReadingWindow]);
useEffect(()=>()=>onReadingWindow([],[]),[onReadingWindow]);
async function fullscreen(){if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen().catch(()=>notify('此浏览器暂时无法进入全屏。'));}
async function exportPage(){if(!page)return;const key=shown?.key??page.blobKey;if(!key){notify('当前图片尚未就绪。');return;}try{const blob=await getBlob(key);if(!blob)throw Error('本地图片已清理，请重新获取。');const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${copy.title}-${index+1}-${shownJob?`${shownJob.mode}-${shownJob.target_language}`:'original'}.${blob.type==='image/jpeg'?'jpg':blob.type==='image/webp'?'webp':'png'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){notify((e as Error).message);}}
function movePage(pageId:string,delta:number){preserve();const pages=[...copy.pages];const at=pages.findIndex(p=>p.id===pageId);const to=at+delta;if(to<0||to>=pages.length)return;[pages[at],pages[to]]=[pages[to],pages[at]];savePosition(copy.id,copy.manifestRevision+1,anchor.current);update({...copy,manifestRevision:copy.manifestRevision+1,pages});setIndex(Math.max(0,pages.findIndex(p=>p.id===page?.id)));requestAnimationFrame(restore);}
function togglePanel(next:Panel){reveal();setPanel(v=>v===next?undefined:next);}
function setPreference(preference:PageView['preference']){if(page)setPageViews(views=>({...views,[pageKey(copy,page.id)]:{...resolvePageView(views[pageKey(copy,page.id)]??initialView,settings.translationMode),preference}}));}
function selectView(value:'original'|Mode){
  if(!page)return;
  preserve();
  setPageViews(views=>({...views,[pageKey(copy,page.id)]:{mode:value==='original'?mode:value,preference:value==='original'?'original':'translation'}}));
  if(value==='original')setCompare(false);
}
if(!page)return <div className="nc-reader"><nav className="nc-reader-rail left nc-reader-controls" aria-label="阅读导航"><button className="icon-button" aria-label="返回我的漫画" onClick={onBack}><Icon name="arrow" style={{transform:'rotate(180deg)'}}/></button><button className="icon-button" aria-label="打开目录" onClick={()=>togglePanel('directory')}><Icon name="list"/></button></nav><div className="nc-empty"><h1>{copy.title}</h1><h2>{sourceStatus??'这份副本还没有可读页面'}</h2>{copy.sourceEntryId?<><button className="button primary" onClick={onAcquire}>授权并继续采集</button><button className="button secondary" onClick={onPauseAcquire}>暂停采集</button></>:<button className="button primary" onClick={onImport}>导入漫画</button>}<button className="button secondary" onClick={()=>setPanel('directory')}>查看作品目录</button></div>{panel==='directory'&&<><button className="nc-drawer-scrim" aria-label="关闭阅读面板" onClick={()=>setPanel(undefined)}/><aside className="nc-reader-drawer left" aria-label="漫画目录"><div className="nc-drawer-title"><h2>目录</h2><button className="icon-button" aria-label="关闭面板" onClick={()=>setPanel(undefined)}><Icon name="close"/></button></div><ComicDirectory directory={directory??{title:copy.title,entries:[],catalogCount:0}} index={0} pageCount={0} onNavigate={onNavigate} onCatalog={onCatalog}><p>页面尚未就绪</p></ComicDirectory></aside></>}</div>;
return <div ref={root} className={`nc-reader ${immersive?'is-immersive':''} ${hidden?'controls-hidden':''}`} data-background={settings.readerBackground} onPointerMove={e=>{
  const target=e.target as HTMLElement;
  const bounds=e.currentTarget.getBoundingClientRect();
  if(target.closest('.nc-reader-controls')||e.clientX-bounds.left<8||bounds.right-e.clientX<8)reveal();
}} onFocusCapture={e=>{if((e.target as HTMLElement).closest('.nc-reader-controls'))reveal();}}>
<nav className="nc-reader-rail left nc-reader-controls" aria-label="阅读导航">
<button aria-label="返回我的漫画" title="返回我的漫画" onClick={()=>{preserve();persist();onBack();}}><Icon name="arrow" style={{transform:'rotate(180deg)'}}/><span>书架</span></button>
<button aria-label="打开目录" title={sourceStatus?`${copy.title} · ${sourceStatus}`:copy.title} aria-expanded={panel==='directory'} onClick={()=>togglePanel('directory')}><Icon name="list"/><span>目录</span>{sourceStatus&&<i className="nc-rail-notice" aria-hidden="true"/>}</button>
<span className="nc-rail-divider"/>
<div className="nc-reader-navigation"><button aria-label="上一页" title="上一页" disabled={index===0} onClick={()=>jump(index-1)}><Icon name="chevron" style={{transform:'rotate(-90deg)'}}/></button><label><input aria-label="跳转页码" type="number" min={1} max={copy.pages.length} value={index+1} onChange={e=>jump(Number(e.target.value)-1)}/><span>/ {copy.pages.length}</span></label><input className="nc-reader-progress" type="range" aria-label="阅读进度" aria-valuetext={`第 ${index+1} 页，共 ${copy.pages.length} 页`} min={1} max={copy.pages.length} step={1} value={index+1} disabled={copy.pages.length===1} onChange={e=>jump(Number(e.target.value)-1)}/><button aria-label="下一页" title="下一页" disabled={index>=copy.pages.length-1&&!next} onClick={()=>jump(index+1)}><Icon name="chevron" style={{transform:'rotate(90deg)'}}/></button></div>
</nav>
<PageTranslationBar selectedView={preference==='original'?'original':mode} shownJob={shownJob} onView={selectView} onFeedback={()=>shownJob&&setFeedback({job:{...shownJob},page,number:index+1})} translationLabel={`默认翻译 · ${modeLabels[settings.translationMode]} · ${language}`} panel={panel} onPanel={togglePanel}/>
<div className="nc-reading-viewport" ref={viewport} onScroll={scroll} data-decoded-pages={decodedSet.size} data-page-count={copy.pages.length} onClick={e=>{if(e.target===e.currentTarget||(e.target as HTMLElement).classList.contains('nc-reading-surface')){if(panel)setPanel(undefined);else reveal();}}}>
<div className="nc-reading-surface" style={{minWidth:contentWidth+24}}>{stream.map((chapter,chapterIndex)=><div className="nc-stream-chapter" key={chapter.id} data-copy-id={chapter.id}>{chapterIndex>0&&<div className="nc-chapter-heading"><span>接着阅读</span><h2>{chapter.title}</h2></div>}{chapter.pages.map((p,n)=>{if(settings.layout==='single'&&n!==index)return null;const pageView=viewFor(p,chapter);const identity=scope(p,chapter);const cellKey=pageKey(chapter,p.id);const wantTranslation=pageView.preference!=='original';const {key:targetKey,job:targetJob}=readingImage(p,pageView.mode,wantTranslation,settings.language,userId,apiOrigin,!initialView);
const {width,height}=frame(p);return <div className="nc-manga-page" key={cellKey} ref={node=>{if(node)cells.current.set(cellKey,node);else cells.current.delete(cellKey);}} data-page-id={p.id} data-page-index={n} style={{width}}><div className={`nc-page-picture ${compare?'comparison':''}`} style={{height}}>{decodedSet.has(cellKey)?<>{compare&&<div className="nc-comparison-pane"><BlobPicture scope={`${cellKey}:compare`} blobKey={p.blobKey} alt={`第 ${n+1} 页`} onImport={onImport} error={p.fetchError}/></div>}<div className="nc-comparison-pane"><BlobPicture scope={identity} blobKey={targetKey} job={targetJob} alt={`第 ${n+1} 页`} error={p.fetchError} sourceUrl={chapter.sourceUrl} onImport={onImport} onShown={image=>{setActual(prev=>prev[cellKey]?.key===image?.key&&prev[cellKey]?.scope===image?.scope?prev:{...prev,[cellKey]:image});}}/></div></>:<div className="nc-image-placeholder"><Icon name="image"/><span>第 {n+1} 页 · 滚动到此处时加载</span></div>}{decodedSet.has(cellKey)&&pageView.preference!=='original'&&<ImageTranslationStatus state={translationState(chapter.id,p,pageView.mode)} onUpgrade={onUpgrade} onLogin={onLogin} onRetry={()=>onRetry(p,pageView.mode,chapter.id)}/>}</div></div>;})}<div className="nc-reader-end" ref={node=>{if(node)ends.current.set(chapter.id,node);else ends.current.delete(chapter.id);}}>
<span aria-hidden="true">✦</span>
{!chapter.pages.length?<><p>{directory?.entries.find(e=>e.copyId===chapter.id)?.error??directory?.entries.find(e=>e.copyId===chapter.id)?.status??'正在准备这一话的页面…'}</p><button className="button secondary" onClick={()=>{preserve();persist();onNavigate(chapter.id);}}>查看采集状态</button></>:!completeManifest(chapter)?<><p>当前已展示 {chapter.pages.length} 页，等待补齐这一话。</p><small>页面清单完整后会自动接上下一话</small></>:settings.layout==='single'&&index<copy.pages.length-1?<p>第 {index+1} 页</p>:<p>{chapterIndex<stream.length-1?'继续下滑，阅读下一话':nextOf(chapter)?'继续阅读下一话':'已到当前内容末尾'}</p>}
</div></div>)}</div></div>
{panel&&<>{panel!=='translation'&&<button className="nc-drawer-scrim" aria-label="关闭阅读面板" onClick={()=>setPanel(undefined)}/>}<aside id={panel==='translation'?'nc-translation-settings':undefined} role={panel==='translation'?'dialog':undefined} className={panel==='translation'?'nc-translation-popover nc-reader-controls':`nc-reader-drawer ${panel==='directory'?'left':'right'}`} aria-label={{directory:'漫画目录',translation:'翻译选项',settings:'阅读设置'}[panel]}><div className="nc-drawer-title"><h2>{{directory:'目录',translation:'翻译设置',settings:'阅读设置'}[panel]}</h2><button className="icon-button" aria-label="关闭面板" onClick={()=>{setPanel(undefined);if(panel==='translation')root.current?.querySelector<HTMLButtonElement>('.nc-translation-trigger')?.focus();}}><Icon name="close"/></button></div>
{panel==='directory'&&sourceStatus&&<div className="nc-source-status" role="status"><span>{sourceStatus}</span><button onClick={onAcquire}>授权并继续</button><button onClick={onPauseAcquire}>暂停采集</button></div>}
{panel==='directory'?<ComicDirectory directory={directory??{title:copy.title,entries:[],catalogCount:0}} index={index} pageCount={copy.pages.length} onNavigate={(id,pageId)=>{preserve();persist();onNavigate(id,pageId);}} onCatalog={onCatalog}><div className="nc-directory-intro"><span>第 {index+1} / {copy.pages.length} 页</span><button className="text-link" onClick={()=>setManage(v=>!v)}>{manage?'完成管理':'管理页面'}</button></div><ThumbnailDirectory pages={copy.pages} index={index} mode={settings.translationMode} language={settings.language} ownerId={userId} origin={apiOrigin} manage={manage} onJump={n=>{jump(n);if(window.innerWidth<760)setPanel(undefined);}} onMove={movePage} onRemove={setRemovePage}/></ComicDirectory>:<div className="nc-drawer-content">
{panel==='translation'?<><Choice label="翻译方式" value={settings.translationMode} options={([{id:'classic',label:'常规翻译'},{id:'redraw',label:'AI 重绘'}] as const)} onChange={translationMode=>{if(!supportsLanguage(caps,translationMode,settings.language)){notify('此目标语言支持常规翻译，暂不支持 AI 重绘。');return;}setSettings(s=>({...s,translationMode}));}}/>{(caps?.languages.length??fallbackLanguages.length)<=4?<Choice label="目标语言" value={settings.language} options={caps?.languages??fallbackLanguages} onChange={language=>setSettings(s=>({...s,language,translationMode:supportsLanguage(caps,s.translationMode,language)?s.translationMode:'classic'}))}/>:<label className="field">目标语言<select aria-label="翻译目标语言" value={settings.language} onChange={e=>setSettings(s=>({...s,language:e.target.value,translationMode:supportsLanguage(caps,s.translationMode,e.target.value)?s.translationMode:'classic'}))}>{(caps?.languages??fallbackLanguages).map(l=><option key={l.id} value={l.id}>{l.label}</option>)}</select></label>}
<p className="nc-muted nc-default-mode-note">停稳后自动翻译当前页与后两页。</p></>:<><Choice label="阅读布局" value={settings.layout} options={[{id:'continuous',label:'连续阅读'},{id:'single',label:'单页阅读'}]} onChange={layout=>{preserve();setSettings(s=>({...s,layout}));}}/><Choice label="阅读方向" value={settings.direction} options={[{id:'rtl',label:'从右向左'},{id:'ltr',label:'从左向右'}]} onChange={direction=>setSettings(s=>({...s,direction}))}/><Choice label="图片适应方式" value={settings.fit} options={[{id:'window',label:'适应窗口'},{id:'width',label:'铺满宽度'}]} onChange={fit=>{preserve();setSettings(s=>({...s,fit}));}}/><div className="nc-reader-option"><b>缩放</b><div className="nc-inline"><button className="icon-button" aria-label="缩小" disabled={zoom<=40} onClick={()=>{preserve();setZoom(z=>z-10);}}><Icon name="minus"/></button><span>{zoom}%</span><button className="icon-button" aria-label="放大" disabled={zoom>=200} onClick={()=>{preserve();setZoom(z=>z+10);}}><Icon name="plus"/></button></div></div><Choice label="阅读背景" value={settings.readerBackground} options={[{id:'gray',label:'浅灰'},{id:'paper',label:'纸白'},{id:'night',label:'夜色'}]} onChange={readerBackground=>setSettings(s=>({...s,readerBackground}))}/><div className="nc-reader-option"><div><b>并排对照</b><p>原图与当前模式最新译图</p></div><button className={`switch ${compare?'on':''}`} role="switch" aria-label="并排对照" aria-checked={compare} onClick={()=>{preserve();setCompare(v=>!v);if(!compare)setPreference('translation');}}><i/></button></div><div className="nc-reader-option"><div><b>沉浸阅读</b><p>空闲时收起工具，轻点空白处唤回。</p></div><button className={`switch ${immersive?'on':''}`} role="switch" aria-label="沉浸阅读" aria-checked={immersive} onClick={()=>setImmersive(v=>!v)}><i/></button></div><div className="nc-stack-actions"><button className="button secondary" onClick={()=>void fullscreen()}><Icon name="expand"/>全屏阅读</button><button className="button secondary" onClick={()=>void exportPage()}><Icon name="download"/>保存当前图片</button><button className="button secondary" onClick={()=>setShortcuts(true)}><Icon name="keyboard"/>键盘快捷键</button></div></>}
</div>}</aside></>}

{hidden&&<button className="nc-reveal" aria-label="显示阅读工具" onClick={reveal}><Icon name="settings" size={20}/></button>}
{feedback&&<FeedbackForm key={feedback.job.id} api={api} job={feedback.job} pageNumber={feedback.number} onClose={()=>setFeedback(undefined)} canRerun={!pageTranslation(copy.pages.find(p=>p.id===feedback.page.id)??feedback.page,feedback.job.mode,feedback.job.target_language,userId,apiOrigin).pending&&!!caps?.modes.find(m=>m.id===feedback.job.mode)?.enabled&&!busy} onRerun={()=>{const p=copy.pages.find(p=>p.id===feedback.page.id);setFeedback(undefined);if(p){setPageViews(views=>({...views,[pageKey(copy,p.id)]:{mode:feedback.job.mode,preference:'translation'}}));void Promise.resolve(onRetry(p,feedback.job.mode)).catch(error=>notify(translationNotice({kind:'error',message:error.message}).label));}}}/>}
{shortcuts&&<Modal title="阅读快捷键" onClose={()=>setShortcuts(false)}><div className="shortcut-list"><p><span>← / →</span><b>按设置方向翻页</b></p><p><span>Page Up / Page Down</span><b>上一页 / 下一页</b></p><p><span>Home / End</span><b>首 / 末页</b></p><p><span>O</span><b>查看原图</b></p><p><span>F</span><b>切换全屏</b></p><p><span>Esc</span><b>关闭面板、唤回工具</b></p></div></Modal>}
{removePage&&<Modal title="移除这一页？" subtitle="从本地清单移除图片。已提交的服务器任务仍会保留。" onClose={()=>setRemovePage(undefined)}><button className="button danger full" onClick={async()=>{try{const keys=[removePage.blobKey,...Object.values(removePage.outputBlobs)].filter((key):key is string=>!!key);const pages=copy.pages.filter(p=>p.id!==removePage.id);const next=Math.max(0,Math.min(index,pages.length-1));anchor.current={pageId:pages[next]?.id??'',relativeOffset:0};savePosition(copy.id,copy.manifestRevision+1,anchor.current);const changed={...copy,manifestRevision:copy.manifestRevision+1,pages,...anchor.current};await saveCopy(changed);update(changed);await collectUnusedBlobs(keys);setIndex(next);setRemovePage(undefined);}catch(e){notify((e as Error).message);}}}>确认移除</button></Modal>}
</div>;
}
function Choice<T extends string>({label,value,options,onChange}:{label:string;value:T;options:readonly {id:T;label:string}[];onChange:(value:T)=>void}){
  return <div className="field"><span>{label}</span><div className="segmented nc-reader-choices" role="group" aria-label={label}>{options.map(option=><button key={option.id} className={value===option.id?'active':''} aria-pressed={value===option.id} onClick={()=>onChange(option.id)}>{option.label}</button>)}</div></div>;
}
